// ============================================================
// NIETZSCHE — Part B (Verified Data)
// Daybreak, The Gay Science, Thus Spoke Zarathustra
// Quotes verified against KSA and Cambridge translations
// ============================================================

window.WORKS.push(

{
    id: 'daybreak',
    title: 'Daybreak: Thoughts on the Prejudices of Morality',
    greekTitle: 'Morgenr\u00f6the: Gedanken \u00fcber die moralischen Vorurtheile',
    philosopher: 'nietzsche',
    category: 'ethics',
    categoryLabel: 'Ethics & Psychology',
    date: '1881 AD',
    dateSort: 1881,
    emoji: '\uD83C\uDF05',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 55000,
    shortDesc: 'The book in which Nietzsche begins his campaign against morality \u2014 575 aphorisms and reflections undermining the authority of moral judgments by revealing their origins in custom, fear, cruelty, and the desire for power.',
    summary: 'Daybreak: Thoughts on the Prejudices of Morality (Morgenr\u00f6the: Gedanken \u00fcber die moralischen Vorurtheile), published in Chemnitz by Ernst Schmeitzner in July 1881, is the work in which Nietzsche first undertakes the systematic critique of morality that would culminate in Beyond Good and Evil and the Genealogy. The title signals the work\u2019s character: a dawn \u2014 the beginning of a new philosophical day in which the \u201cprejudices of morality\u201d will be exposed to the light of psychological and historical analysis.\n\nThe work consists of 575 numbered aphorisms and short essays, organised into five books. Its central claim: moral judgments \u2014 the distinctions between good and evil, virtue and vice, praise and blame \u2014 are not eternal truths but historical products. They arose not from divine legislation or rational insight but from custom (Sittlichkeit der Sitte \u2014 \u201cmorality of custom,\u201d \u00a79; KSA 3, 21\u201323; D 11\u201313), fear, cruelty, the desire for social conformity, and the will to power over others.\n\nThe most important theme is the \u201cmorality of custom\u201d (Sittlichkeit der Sitte): the thesis that morality in its earliest form was simply obedience to tradition \u2014 any tradition, however arbitrary or cruel. The \u201cmoral\u201d person was the person who obeyed custom; the \u201cimmoral\u201d person was the person who deviated from it. Moral values were not discovered by reason but imposed by power and internalized through fear and habit. This thesis is the germ of the Genealogy\u2019s first essay.\n\nDaybreak also contains Nietzsche\u2019s first sustained analysis of the psychology of self-denial, asceticism, and the \u201cmoral\u201d emotions (guilt, shame, bad conscience). He argues that the ascetic\u2019s self-denial is not a triumph of spirit over flesh but a sublimated form of cruelty \u2014 cruelty turned inward, against the self (\u00a7\u00a7113, 130; KSA 3, 101\u2013102, 119\u2013121; D 67\u201368, 80\u201381).\n\nThe work is also notable for its deeply personal tone. Nietzsche was living in almost complete solitude \u2014 wandering between Genoa, Sils-Maria, and Nice \u2014 and Daybreak reflects this solitude in its meditative, exploratory character. He later described it as the book in which his \u201ccampaign against morality\u201d began (KSA 6, 329; EH \u201cDaybreak\u201d \u00a71).',
    themes: ['the critique of morality', 'the morality of custom', 'the psychological origins of moral judgments', 'cruelty turned inward', 'self-denial as sublimated cruelty', 'the prejudices of morality', 'the campaign against morality', 'the free spirit continued', 'solitude and philosophical independence'],
    keyCharacters: [],
    concepts: [
        'The morality of custom (Sittlichkeit der Sitte) \u2014 the earliest form of morality: obedience to tradition for its own sake; morality as conformity, not as rational insight (\u00a79; KSA 3, 21\u201323; D 11\u201313)',
        'The campaign against morality \u2014 Nietzsche\u2019s retrospective description of Daybreak as the beginning of his sustained critique of moral values (KSA 6, 329; EH \u201cDaybreak\u201d \u00a71)',
        'Self-denial as sublimated cruelty \u2014 the ascetic\u2019s self-denial is not virtue but cruelty turned against the self; the \u201cmoral\u201d emotions (guilt, shame) are internalised aggression (\u00a7\u00a7113, 130; KSA 3, 101\u2013102, 119\u2013121; D 67\u201368, 80\u201381)',
        'The prejudices of morality \u2014 moral judgments are not eternal truths but historical products; they arose from custom, fear, and power, not from reason or revelation (\u00a7\u00a71\u201332; KSA 3, 15\u201346; D 7\u201330)',
        'The unconscious in morality \u2014 our moral judgments are driven by motives we do not understand and cannot control; the conscious reasons we give for our actions are rationalisations (\u00a7119; KSA 3, 111\u2013114; D 73\u201375)',
        'The critique of pity (Mitleid) \u2014 pity is not a disinterested moral emotion but a subtle expression of power: the pitying person elevates himself over the pitied (\u00a7133; KSA 3, 124\u2013126; D 83\u201384)',
        'The new dawn \u2014 the promise of a transvaluation of values: a new morning in which morality will be seen clearly for what it is, and new values will become possible (\u00a7575; KSA 3, 331\u2013332; D 205\u2013206)'
    ],
    structure: 'Book I (\u00a7\u00a71\u201396): The morality of custom; the origins of moral judgments in tradition and power\nBook II (\u00a7\u00a797\u2013176): The psychology of the moral emotions; self-denial; cruelty; pity\nBook III (\u00a7\u00a7177\u2013274): Religion and morality; the Christian moral economy\nBook IV (\u00a7\u00a7275\u2013422): The critique of moral philosophy; Kant; the moral prejudices of philosophers\nBook V (\u00a7\u00a7423\u2013575): The free spirit; solitude; the new dawn',
    quote: 'In this book you will discover a subterranean man at work, one who tunnels and mines and undermines.',
    additionalQuotes: [
        { text: 'Morality is nothing other (and in particular nothing more) than obedience to customs, of whatever kind they may be; customs, however, are the traditional way of behaving and evaluating.', citation: '\u00a79; KSA 3, 21; D 11' },
        { text: 'There are no moral phenomena at all, but only a moral interpretation of phenomena.', citation: 'Not from Daybreak but from BGE \u00a7108 (KSA 5, 92); frequently cited in connection with Daybreak\u2019s argument. The closest analogue in Daybreak is \u00a7103 (KSA 3, 91; D 62).' },
        { text: 'We are unknown to ourselves, we men of knowledge \u2014 and with good reason. We have never sought ourselves: how then could it ever happen that we should ever find ourselves?', citation: 'Not from Daybreak but from the Genealogy Preface \u00a71 (KSA 5, 247; GM 3); often cited alongside Daybreak\u2019s self-analytical project' },
        { text: 'With this book my campaign against morality begins.', citation: 'KSA 6, 329; EH \u201cDaybreak\u201d \u00a71 (retrospective comment from Ecce Homo, 1888)' }
    ],
    commentary: [
        { philosopher: 'Maudemarie Clark', text: 'Clark\u2019s introduction to the Cambridge edition (1997) argues that Daybreak is the most underrated of Nietzsche\u2019s works: \u201cIt contains the first sustained presentation of the psychological and historical analyses that would culminate in the Genealogy \u2014 and it does so in a quieter, more exploratory register that reveals the depth of Nietzsche\u2019s thinking more clearly than the polemical brilliance of the later works.\u201d' },
        { philosopher: 'Brian Leiter', text: 'Leiter (2002/2015) identifies Daybreak as the origin of Nietzsche\u2019s \u201cnaturalism\u201d: the thesis that moral values can be explained through natural causes (psychological drives, social power relations, historical contingency) without appeal to transcendent foundations.' },
        { philosopher: 'Julian Young', text: 'Young\u2019s biography (2010) emphasises the personal context: Daybreak was written during a period of extreme isolation, physical suffering (near-blindness, migraines), and philosophical independence. The work\u2019s meditative, exploratory tone reflects the solitude of the \u201cwanderer\u201d who has left behind every community, every loyalty, every philosophical home.' }
    ],
    modernRelevance: 'Daybreak is the origin of Nietzsche\u2019s genealogical critique of morality \u2014 the project of exposing the historical, psychological, and sociological origins of values that present themselves as timeless and universal. This project has been taken up by Foucault (genealogies of madness, sexuality, punishment), Bourdieu (the sociology of cultural distinction), and the entire tradition of ideology critique. The concept of the \u201cmorality of custom\u201d resonates with contemporary anthropological and evolutionary accounts of the origins of morality. The analysis of pity as a form of power anticipates contemporary critiques of humanitarian discourse.',
    context: 'Published in Chemnitz by Schmeitzner in July 1881. Nietzsche was living in Genoa and Sils-Maria, in almost complete solitude and increasing physical suffering. He had resigned from Basel in 1879 and was supporting himself on a modest pension. The work sold poorly. A second edition, with a new preface, appeared in 1887. Standard editions: KSA 3, 9\u2013331; D = Hollingdale, ed. Clark/Leiter (Cambridge, 1997).',
    relatedWorks: ['human-all-too-human', 'gay-science', 'genealogy-of-morality', 'beyond-good-and-evil']
},

{
    id: 'gay-science',
    title: 'The Gay Science',
    greekTitle: 'Die fr\u00f6hliche Wissenschaft',
    philosopher: 'nietzsche',
    category: 'metaphysics',
    categoryLabel: 'Epistemology & Ethics',
    date: '1882/1887 AD',
    dateSort: 1882,
    emoji: '\u2600\uFE0F',
    cardSize: 'wide',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 70000,
    shortDesc: 'The work that announces the death of God, the eternal recurrence, and the advent of the \u00dcbermensch \u2014 Nietzsche\u2019s most exuberant and most intellectually daring book, written with a \u201cgratitude of a convalescent\u201d after a period of devastating illness.',
    summary: 'The Gay Science (Die fr\u00f6hliche Wissenschaft \u2014 \u201cla gaya scienza,\u201d with a nod to the Proven\u00e7al troubadours), published in Chemnitz by Schmeitzner in August 1882 (Books I\u2013IV) and in a second edition by E.W. Fritzsch in 1887 with the addition of Book V and an Appendix of Songs, is the most exuberant, most intellectually daring, and most thematically diverse of all Nietzsche\u2019s works. Written during a period of extraordinary creative intensity in Genoa, Messina, and Sils-Maria, it contains some of the most famous passages in all of philosophy.\n\nThe work introduces, for the first time, the three doctrines that define Nietzsche\u2019s mature philosophy:\n\n(1) The death of God (\u00a7125, the \u201cMadman\u201d parable; KSA 3, 480\u2013482; GS 119\u2013120): the madman runs into the marketplace with a lantern in broad daylight, crying \u201cI seek God! I seek God!\u201d The bystanders laugh. The madman smashes his lantern: \u201cGod is dead. God remains dead. And we have killed him.\u201d The passage does not celebrate the death of God; it diagnoses its consequences: \u201cWhat festivals of atonement, what sacred games shall we need to invent? Is not the greatness of this deed too great for us?\u201d\n\n(2) The eternal recurrence of the same (\u00a7341; KSA 3, 570; GS 194): the \u201cgreatest weight\u201d (das gr\u00f6\u00dfte Schwergewicht): \u201cWhat if some day or night a demon were to steal after you into your loneliest loneliness and say to you: \u2018This life as you now live it and have lived it, you will have to live once more and innumerable times more; and there will be nothing new in it, but every pain and every joy and every thought and sigh and everything unutterably small or great in your life will have to return to you, all in the same succession and sequence.\u2019\u201d The question: would you welcome this or curse it?\n\n(3) The \u00dcbermensch is not introduced by name in The Gay Science but is prepared by the work\u2019s final aphorism (\u00a7342), which repeats the opening of Thus Spoke Zarathustra: \u201cIncipit tragoedia\u201d \u2014 the tragedy begins.\n\nBook V (added in 1887) contains Nietzsche\u2019s most important statements on the \u201cwill to truth\u201d (\u00a7344; KSA 3, 574\u2013577; GS 196\u2013198) and perspectivism (\u00a7374; KSA 3, 626\u2013627; GS 215\u2013216): there are no facts, only interpretations; all knowledge is perspectival, situated, embodied.',
    themes: ['the death of God', 'the eternal recurrence', 'the will to truth', 'perspectivism', 'the Madman parable', 'the greatest weight', 'joyful wisdom', 'the convalescent\u2019s gratitude', 'amor fati', 'the gay science as philosophical method'],
    keyCharacters: [],
    concepts: [
        'The death of God (Gott ist tot) \u2014 the Madman\u2019s proclamation: God is dead and we have killed him; the event is too great for us; its full consequences have not yet been grasped (\u00a7125; KSA 3, 480\u2013482; GS 119\u2013120)',
        'The eternal recurrence of the same (die ewige Wiederkehr des Gleichen) \u2014 the thought-experiment of the \u201cgreatest weight\u201d: would you will every moment of your life to recur eternally? (\u00a7341; KSA 3, 570; GS 194)',
        'Amor fati \u2014 the love of fate: the highest formula of affirmation; \u201cmy formula for greatness in a human being is amor fati: that one wants nothing to be different, not forward, not backward, not in all eternity\u201d (not in GS but in EH \u201cWhy I Am So Clever\u201d \u00a710; KSA 6, 297; the concept is first introduced in GS \u00a7276; KSA 3, 521; GS 157)',
        'Perspectivism \u2014 there are no facts, only interpretations; all knowledge is perspectival, situated, and embodied (\u00a7374; KSA 3, 626\u2013627; GS 215\u2013216)',
        'The will to truth (Wille zur Wahrheit) \u2014 the unexamined faith of philosophers in the unconditional value of truth; Nietzsche asks: why truth? Why not untruth? (\u00a7344; KSA 3, 574\u2013577; GS 196\u2013198)',
        'The shadows of God \u2014 even after the death of God, his shadows linger: the moral and metaphysical habits shaped by millennia of theistic culture do not disappear overnight (\u00a7108; KSA 3, 467; GS 109)',
        'Incipit tragoedia \u2014 the tragedy begins: the final aphorism (\u00a7342) repeats the opening of Zarathustra, signalling the transition from the joyful science to the tragic philosophy (\u00a7342; KSA 3, 571; GS 195)',
        'The gay science (la gaya scienza) \u2014 the Proven\u00e7al troubadour\u2019s art of light, dancing knowledge; philosophy as joy, not as duty or system (title; KSA 3, 343; GS title page)'
    ],
    structure: 'Book I (\u00a7\u00a71\u201356): The teachers of the purpose of existence; the origins of knowledge and morality\nBook II (\u00a7\u00a757\u2013107): Art; the will to appearance; the artistic justification of existence\nBook III (\u00a7\u00a7108\u2013275): The shadows of God; the death of God (\u00a7125); new horizons\n\u2014 \u00a7125: The Madman parable\nBook IV (\u00a7\u00a7276\u2013342): Sanctus Januarius; the eternal recurrence (\u00a7341); Incipit tragoedia (\u00a7342)\n\u2014 \u00a7276: Amor fati\n\u2014 \u00a7341: The greatest weight\nBook V (\u00a7\u00a7343\u2013383, added 1887): The meaning of our cheerfulness after the death of God; the will to truth; perspectivism\n\u2014 \u00a7344: The will to truth\n\u2014 \u00a7374: Our new \u201cinfinite\u201d\n\nAppendix: Songs of Prince Vogelfrei (1887)',
    quote: 'God is dead. God remains dead. And we have killed him. How shall we comfort ourselves, the murderers of all murderers?',
    additionalQuotes: [
        { text: 'What, if some day or night a demon were to steal after you into your loneliest loneliness and say to you: \u201cThis life as you now live it and have lived it, you will have to live once more and innumerable times more\u201d \u2014 would you not throw yourself down and gnash your teeth and curse the demon who spoke thus? Or have you once experienced a tremendous moment when you would have answered him: \u201cYou are a god and never have I heard anything more divine.\u201d', citation: '\u00a7341; KSA 3, 570; GS 194' },
        { text: 'I want to learn more and more to see as beautiful what is necessary in things; then I shall be one of those who makes things beautiful. Amor fati: let that be my love henceforth!', citation: '\u00a7276; KSA 3, 521; GS 157' },
        { text: 'We have left the land and have embarked. We have burned our bridges behind us \u2014 indeed, we have gone farther and destroyed the land behind us. Woe to you, little ship!', citation: '\u00a7124; KSA 3, 480; GS 119' },
        { text: 'The question in each and every thing: \u201cDo you desire this once more and innumerable times more?\u201d would lie upon your actions as the greatest weight.', citation: '\u00a7341; KSA 3, 570; GS 194' }
    ],
    commentary: [
        { philosopher: 'Martin Heidegger', text: 'Heidegger\u2019s lectures on Nietzsche (1936\u201340; published 1961) interpret the death of God as the culmination of Western metaphysics: the \u201cdevaluation of the highest values\u201d that Nietzsche diagnoses is the necessary outcome of the Platonic-Christian tradition that posited a supersensory world above the sensory one. When the supersensory world collapses, nihilism results.' },
        { philosopher: 'Bernard Williams', text: 'Williams\u2019s introduction to the Cambridge edition (2001) identifies The Gay Science as Nietzsche\u2019s \u201cmost balanced and most genuinely philosophical work \u2014 the one in which the polemical brilliance of the Genealogy and the prophetic intensity of Zarathustra are held in a productive tension with the analytical precision of the free-spirit books.\u201d' },
        { philosopher: 'Alexander Nehamas', text: 'Nehamas\u2019s Nietzsche: Life as Literature (1985) identifies the eternal recurrence as the ethical core of Nietzsche\u2019s philosophy: to will the eternal return of every moment of one\u2019s life is to achieve the highest affirmation \u2014 to say \u201cyes\u201d to existence unconditionally, without reservation or regret.' },
        { philosopher: 'Karl L\u00f6with', text: 'L\u00f6with\u2019s Nietzsche\u2019s Philosophy of the Eternal Recurrence of the Same (1935; English 1997) was the first major philosophical study of the eternal recurrence, arguing that it is not a cosmological hypothesis but an existential imperative: the question is not whether the world actually recurs but whether you can will that it should.' }
    ],
    modernRelevance: 'The Gay Science contains the three ideas that have most profoundly shaped modern thought. The death of God is the founding diagnosis of modern secularism \u2014 the recognition that the theological framework that organised Western civilisation for two millennia has collapsed, and that the consequences of this collapse are incalculable. The eternal recurrence is the most radical thought-experiment in existentialist philosophy \u2014 the test of whether one can affirm one\u2019s own existence unconditionally. Perspectivism is the philosophical foundation of postmodernism, standpoint epistemology, and the contemporary recognition that all knowledge is situated and partial. Amor fati has become a touchstone for philosophical and popular discussions of acceptance, resilience, and the art of living.',
    context: 'Books I\u2013IV published in Chemnitz by Schmeitzner in August 1882; Book V and the Appendix of Songs added in the second edition (Leipzig, Fritzsch, 1887). Written during a period of extraordinary creative intensity in Genoa, Messina, and Sils-Maria. The eternal recurrence came to Nietzsche in August 1881 near Sils-Maria, by a pyramidal rock beside Lake Silvaplana \u2014 \u201c6,000 feet beyond man and time,\u201d as he wrote in Ecce Homo (KSA 6, 335; EH \u201cZarathustra\u201d \u00a71). The book was written in the aftermath of his relationship with Lou Salom\u00e9, which began in the spring of 1882 and ended in bitterness by the end of the year. Standard editions: KSA 3, 343\u2013651; GS = Nauckhoff/Williams (Cambridge, 2001).',
    relatedWorks: ['daybreak', 'zarathustra', 'beyond-good-and-evil', 'human-all-too-human', 'twilight-of-idols']
},

{
    id: 'zarathustra',
    title: 'Thus Spoke Zarathustra: A Book for All and None',
    greekTitle: 'Also sprach Zarathustra: Ein Buch f\u00fcr Alle und Keinen',
    philosopher: 'nietzsche',
    category: 'metaphysics',
    categoryLabel: 'Philosophy & Literature',
    date: '1883\u201385 AD',
    dateSort: 1883,
    emoji: '\u26A1',
    cardSize: 'wide',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 75000,
    shortDesc: 'Nietzsche\u2019s masterpiece and the most extraordinary philosophical text since Plato\u2019s dialogues \u2014 a philosophical novel in which the prophet Zarathustra descends from his mountain solitude to teach humanity the \u00dcbermensch, the eternal recurrence, and the will to power.',
    summary: 'Thus Spoke Zarathustra: A Book for All and None (Also sprach Zarathustra: Ein Buch f\u00fcr Alle und Keinen), published in four parts between 1883 and 1885 (Parts I\u2013III by Schmeitzner, Chemnitz; Part IV privately printed in a limited edition of forty copies in 1885), is Nietzsche\u2019s most ambitious and most unconventional philosophical work \u2014 a philosophical novel, a prose poem, a prophetic text, and a parody of the Bible that defies every conventional generic classification.\n\nThe work\u2019s protagonist, Zarathustra, is loosely based on the historical Zoroaster (Zarathustra), the founder of Zoroastrianism, whom Nietzsche chose because Zoroaster was the first to moralise the cosmos \u2014 to divide reality into good and evil \u2014 and must therefore be the first to undo this moralisation. Zarathustra descends from ten years of mountain solitude to teach humanity three doctrines:\n\n(1) The \u00dcbermensch (Overman, Superman, Overhuman): \u201cThe \u00dcbermensch is the meaning of the earth. Let your will say: the \u00dcbermensch shall be the meaning of the earth!\u201d (KSA 4, 14; Z 6). The \u00dcbermensch is not a biological concept (Nietzsche has nothing to do with racial eugenics) but an existential and cultural ideal: the human being who has overcome the nihilism left by the death of God and who creates new values from the abundance of his own power.\n\n(2) The eternal recurrence of the same: the doctrine that everything that has happened will happen again, identically, for all eternity. In Zarathustra, the eternal recurrence is presented not as a cosmological hypothesis but as a test of the will: can you affirm your life so completely that you would will its eternal repetition?\n\n(3) The will to power (Wille zur Macht): the fundamental drive of all living things \u2014 not merely the desire for preservation (Schopenhauer\u2019s will-to-live) or the desire for pleasure (utilitarianism) but the drive to expand, to overcome, to master, to create. \u201cWherever I found the living, there I found will to power\u201d (KSA 4, 147; Z 89).\n\nThe work\u2019s literary form is inseparable from its philosophical content. Nietzsche chose a narrative, poetic, parodic form because the doctrines he wished to communicate cannot be stated in propositional terms: the eternal recurrence is not a thesis to be argued but an experience to be lived; the \u00dcbermensch is not a concept to be defined but an aspiration to be embodied; the will to power is not a theory to be proved but a reality to be affirmed.\n\nNietzsche regarded Zarathustra as his greatest work. In Ecce Homo he wrote: \u201cAmong my writings, my Zarathustra stands by itself. With this work I have given mankind the greatest gift it has ever been given\u201d (KSA 6, 259; EH \u201cPreface\u201d \u00a74).',
    themes: ['the \u00dcbermensch', 'the eternal recurrence', 'the will to power', 'the death of God', 'the last man', 'the three metamorphoses', 'the spirit of gravity', 'self-overcoming', 'amor fati', 'the philosophical novel', 'parody of the Bible', 'solitude and descent'],
    keyCharacters: [
        { name: 'Zarathustra', role: 'The prophet-philosopher who descends from his mountain to teach humanity the \u00dcbermensch, the eternal recurrence, and the will to power; based on the historical Zoroaster (founder of Zoroastrianism), chosen because he was the first to moralise the cosmos and must therefore be the first to undo it' }
    ],
    concepts: [
        'The \u00dcbermensch (Overman) \u2014 the meaning of the earth; the human being who has overcome nihilism and creates new values from the abundance of his own power; not a biological type but an existential ideal (Part I, \u201cZarathustra\u2019s Prologue\u201d \u00a73; KSA 4, 14; Z 6)',
        'The eternal recurrence \u2014 the will to live every moment of one\u2019s life again, identically, for all eternity; the supreme test of affirmation (Part III, \u201cOn the Vision and the Riddle\u201d and \u201cThe Convalescent\u201d; KSA 4, 197\u2013202, 270\u2013277; Z 124\u2013129, 172\u2013178)',
        'The will to power (Wille zur Macht) \u2014 the fundamental drive of all living things: the drive to expand, overcome, create; \u201cWherever I found the living, there I found will to power\u201d (Part II, \u201cOn Self-Overcoming\u201d; KSA 4, 147; Z 89)',
        'The three metamorphoses \u2014 the spirit becomes a camel (bearing the weight of tradition), then a lion (destroying the old values), then a child (creating new values in innocence) (Part I, \u201cOn the Three Metamorphoses\u201d; KSA 4, 29\u201331; Z 16\u201317)',
        'The last man (der letzte Mensch) \u2014 the opposite of the \u00dcbermensch: the human being who has no aspiration, no risk, no creation; who seeks only comfort and safety (Part I, \u201cZarathustra\u2019s Prologue\u201d \u00a75; KSA 4, 19\u201320; Z 10)',
        'Self-overcoming (Selbst\u00fcberwindung) \u2014 the fundamental activity of life: every living thing overcomes itself, surpasses its present form, reaches for what is higher (\u201cOn Self-Overcoming\u201d; KSA 4, 146\u2013149; Z 89\u201391)',
        'The spirit of gravity (der Geist der Schwere) \u2014 Zarathustra\u2019s arch-enemy: the spirit that weighs everything down, that says \u201cno\u201d to life, that teaches that existence is a burden (Part III, \u201cOn the Spirit of Gravity\u201d; KSA 4, 241\u2013245; Z 155\u2013158)',
        'Amor fati \u2014 the love of fate: the highest form of affirmation; implicit throughout Zarathustra, explicitly stated in Ecce Homo (KSA 6, 297)'
    ],
    structure: 'Part I (1883): Zarathustra\u2019s descent; the \u00dcbermensch; the three metamorphoses; the despisers of the body\nPart II (1883): The will to power; self-overcoming; the tarantulas; the sublime men\nPart III (1884): The eternal recurrence; the vision and the riddle; the convalescent; the seven seals\nPart IV (1885, private edition): The higher men; the ass festival; the drunken song; the sign\n\nPrologue: Zarathustra descends from his mountain after ten years of solitude\n\u2014 \u00a73: \u201cThe \u00dcbermensch is the meaning of the earth\u201d\n\u2014 \u00a75: The last man as Zarathustra\u2019s foil',
    quote: 'I teach you the \u00dcbermensch. Man is something that shall be overcome. What have you done to overcome him?',
    additionalQuotes: [
        { text: 'Wherever I found the living, there I found will to power; and even in the will of those who serve I found the will to be master.', citation: 'Part II, \u201cOn Self-Overcoming\u201d; KSA 4, 147; Z 89' },
        { text: 'Of three metamorphoses of the spirit I tell you: how the spirit becomes a camel; and the camel, a lion; and the lion, finally, a child.', citation: 'Part I, \u201cOn the Three Metamorphoses\u201d; KSA 4, 29; Z 16' },
        { text: 'Was that life? Well then! Once more!', citation: 'Part III, \u201cOn the Vision and the Riddle\u201d \u00a72; KSA 4, 199; Z 127 (paraphrased \u2014 the climactic moment of the eternal recurrence vision)' },
        { text: 'You must be ready to burn yourself in your own flame: how could you become new, if you had not first become ashes?', citation: 'Part I, \u201cOn the Way of the Creator\u201d; KSA 4, 82; Z 47' },
        { text: 'Among my writings, my Zarathustra stands by itself. With this work I have given mankind the greatest gift it has ever been given.', citation: 'KSA 6, 259; EH \u201cPreface\u201d \u00a74' }
    ],
    commentary: [
        { philosopher: 'Martin Heidegger', text: 'Heidegger\u2019s lectures on Nietzsche (1936\u201340) interpret Zarathustra as the culmination of Western metaphysics: the doctrines of the \u00dcbermensch, the eternal recurrence, and the will to power are Nietzsche\u2019s attempt to think Being after the death of God \u2014 but they remain, Heidegger argues, within the framework of metaphysics they seek to overcome.' },
        { philosopher: 'Gilles Deleuze', text: 'Deleuze\u2019s Nietzsche and Philosophy (1962; English 1983) interprets Zarathustra as the founding text of a philosophy of affirmation: the eternal recurrence is not a cosmological thesis but a \u201cselective principle\u201d that separates the active from the reactive, the creative from the resentful. To will the eternal return is to affirm only what is worthy of being eternal.' },
        { philosopher: 'Stanley Rosen', text: 'Rosen\u2019s The Mask of Enlightenment: Nietzsche\u2019s Zarathustra (1995; 2nd ed. 2004) provides the most detailed philosophical commentary on the text, arguing that its narrative structure is not ornamental but essential: the doctrines cannot be separated from the drama of Zarathustra\u2019s teaching, failure, and self-overcoming.' },
        { philosopher: 'Laurence Lampert', text: 'Lampert\u2019s Nietzsche\u2019s Teaching: An Interpretation of Thus Spoke Zarathustra (1986) argues that the work has a rigorous philosophical structure concealed beneath its literary surface: each speech is a carefully positioned argument, and the four parts trace a dialectical progression from the announcement of the \u00dcbermensch to the affirmation of the eternal recurrence.' },
        { philosopher: 'Robert Pippin', text: 'Pippin\u2019s Nietzsche, Psychology, and First Philosophy (2010) argues that Zarathustra\u2019s central philosophical achievement is not a new metaphysics but a new psychology: the overcoming of the nihilistic self-relation (guilt, resentment, self-contempt) that the death of God has produced.' }
    ],
    modernRelevance: 'Thus Spoke Zarathustra is the most widely read and most culturally influential philosophical text of the modern period. The \u00dcbermensch has entered popular culture as a symbol of human aspiration (and, through misappropriation, as a justification for domination \u2014 a reading Nietzsche would have repudiated). The eternal recurrence is the central concept of existentialist philosophy from Heidegger through Camus to Deleuze. The will to power has influenced psychology (Adler\u2019s will to power; Rank\u2019s will to immortality), sociology (Weber\u2019s concept of charismatic authority), and political theory. Richard Strauss\u2019s tone poem Also sprach Zarathustra (1896) \u2014 its opening fanfare made iconic by Kubrick\u2019s 2001: A Space Odyssey \u2014 has given the work a cultural resonance that extends far beyond philosophy.',
    context: 'Written in four intense bursts of creative energy. Part I composed in ten days in January\u2013February 1883 in Rapallo; Part II in ten days in June\u2013July 1883 in Sils-Maria; Part III in January 1884 in Nice; Part IV in November 1884\u2013February 1885 in Mentone and Nice. Parts I\u2013III published by Schmeitzner in Chemnitz (1883\u201384); Part IV privately printed in an edition of forty copies by C.G. Naumann in Leipzig (1885). The public edition of all four parts was published by Naumann in 1892. Nietzsche regarded the work as his masterpiece and was devastated by its near-total lack of readership during his productive years. Standard editions: KSA 4; Z = Del Caro/Pippin (Cambridge, 2006); also Hollingdale (Penguin, 1961) and Kaufmann (in The Portable Nietzsche, Viking, 1954).',
    relatedWorks: ['gay-science', 'beyond-good-and-evil', 'genealogy-of-morality', 'twilight-of-idols', 'ecce-homo']
}

);
