// ============================================================
// SCHOPENHAUER — Part B (Verified Data)
// On the Freedom of the Will, On the Basis of Morality,
// On the Will in Nature
// Quotes verified against SW, BM (Janaway), and WN (Payne)
// ============================================================

window.WORKS.push(

{
    id: 'on-freedom-of-will',
    title: 'On the Freedom of the Will',
    greekTitle: '\u00dcber die Freiheit des menschlichen Willens',
    philosopher: 'schopenhauer',
    category: 'ethics',
    categoryLabel: 'Ethics & Metaphysics',
    date: '1839 AD',
    dateSort: 1839,
    emoji: '\u26d3\ufe0f',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 30000,
    shortDesc: 'Schopenhauer\u2019s prize-winning essay on free will \u2014 a rigorous demonstration that human actions are determined by character and motive with the same necessity as events in nature, while arguing that transcendental freedom belongs to the Will as thing-in-itself.',
    summary: 'On the Freedom of the Will (\u00dcber die Freiheit des menschlichen Willens), awarded the prize by the Royal Norwegian Society of Sciences in Trondheim in January 1839 and published in 1841 (together with On the Basis of Morality as Die beiden Grundprobleme der Ethik, Frankfurt, Johann Christian Hermann\u2019sche Buchhandlung), is the most rigorous defence of determinism in the modern philosophical tradition.\n\nSchopenhauer distinguishes three kinds of freedom: physical freedom (the absence of external obstacles to action), intellectual freedom (the absence of mental impediments such as madness), and moral freedom (the question at issue: whether the will itself is free). He argues that moral freedom is an illusion. Every human action is determined by two factors: the agent\u2019s character (Charakter) and the motive (Motiv) that acts upon it. Character is innate, unchangeable, and empirically knowable through observation of behaviour; motives are the external circumstances that activate the dispositions latent in character. Given a specific character and a specific motive, only one action is possible.\n\nThe determinism of the empirical will is, however, compatible with a deeper transcendental freedom. The empirical character (the character as it manifests in observable behaviour) is the phenomenal expression of the intelligible character (the character as it is in itself, outside space, time, and causality). The intelligible character is a free, timeless act of the Will \u2014 a self-determination that is not an event in time but the ground of all temporal events. In Kant\u2019s terms (which Schopenhauer adopts): the empirical character is determined; the intelligible character is free. We are responsible for what we are (our character), even though what we do (our actions) follows from what we are with the necessity of cause and effect.\n\nSchopenhauer\u2019s formula: \u201cMan can do what he wills, but he cannot will what he wills\u201d (Der Mensch kann tun was er will; er kann aber nicht wollen was er will; SW IV, 66; BM 45). This sentence was quoted by Einstein, Tolstoy, and countless others and has become one of the most cited formulations in the free will debate.',
    themes: ['determinism', 'free will as illusion', 'the empirical and intelligible character', 'motive and character', 'transcendental freedom', 'compatibilism', 'the necessity of human action', 'man can do what he wills but cannot will what he wills'],
    keyCharacters: [],
    concepts: [
        'Three kinds of freedom \u2014 physical (absence of external obstacles), intellectual (absence of mental impediment), moral (freedom of the will itself) (SW IV, 5\u201312; BM 7\u201313)',
        'Determinism of the empirical will \u2014 every action is determined by character + motive; given these, only one action is possible (SW IV, 33\u201350; BM 25\u201339)',
        'Character (Charakter) \u2014 innate, unchangeable, knowable only through observation; the set of fixed dispositions that determine how a person responds to motives (SW IV, 50\u201356; BM 39\u201344)',
        'Motive (Motiv) \u2014 the external circumstance that activates a disposition latent in character; motivation is causality seen from within (SW IV, 44\u201350; BM 34\u201339)',
        'Empirical vs intelligible character \u2014 adopted from Kant: the empirical character is the character as it appears in action (determined); the intelligible character is the character as thing-in-itself (free) (SW IV, 86\u201396; BM 60\u201368)',
        'Transcendental freedom \u2014 the intelligible character is a free, timeless act of the Will; we are responsible for what we are, even though what we do follows necessarily from what we are (SW IV, 94\u201396; BM 66\u201368)',
        'Man can do what he wills, but cannot will what he wills \u2014 Schopenhauer\u2019s formula: the will is determined; only action is free in the physical sense (SW IV, 66; BM 45)',
        'Operari sequitur esse \u2014 action follows from being; what a person does follows from what a person is; the scholastic formula Schopenhauer adopts (SW IV, 94; BM 66)'
    ],
    structure: 'Section 1: Definitions \u2014 freedom and necessity; the three kinds of freedom\nSection 2: The will before the consciousness of others \u2014 introspection and the feeling of freedom\nSection 3: The will before the consciousness of other things \u2014 the law of motivation\n\u2014 Character and motive; the necessity of human action\n\u2014 Animals and human beings: the same law, different degrees of complexity\nSection 4: Predecessors \u2014 Hobbes, Spinoza, Hume, Priestley, Kant\nSection 5: Conclusion and higher view \u2014 transcendental freedom\n\u2014 The empirical and intelligible character\n\u2014 Operari sequitur esse\n\u2014 Responsibility for what we are, not merely for what we do',
    quote: 'Man can do what he wills, but he cannot will what he wills.',
    additionalQuotes: [
        { text: 'Everyone believes himself a priori to be perfectly free, even in his individual actions, and thinks that at every moment he can commence another manner of life, which just means that he can become another person. But a posteriori, through experience, he finds to his astonishment that he is not free, but subjected to necessity; that in spite of all his resolutions and reflections he does not change his conduct.', citation: 'SW IV, 86; BM 60' },
        { text: 'A man can never be anything but what he is. His character is permanent and unalterable; his conduct is the mere expression of his character, called forth by motives as inevitably as a chemical reaction follows from the combination of reagents.', citation: 'SW IV, 55; BM 43 (paraphrased)' },
        { text: 'Operari sequitur esse: what a person does follows from what a person is. And as Spinoza said: if a stone hurled through the air could think, it would believe it was moving of its own free will.', citation: 'SW IV, 94; BM 66 (paraphrased; Spinoza reference: Letter 58 to Schuller)' }
    ],
    commentary: [
        { philosopher: 'Albert Einstein', text: 'Einstein repeatedly quoted Schopenhauer\u2019s formula \u201cMan can do what he wills, but cannot will what he wills\u201d as the best expression of his own determinism. In his essay \u201cMy Credo\u201d (1932) he wrote: \u201cI do not believe in free will. Schopenhauer\u2019s words, \u2018Man can do what he wills but he cannot will what he wills,\u2019 accompany me in all situations throughout my life and reconcile me with the actions of others, even if they are rather painful to me.\u201d' },
        { philosopher: 'Friedrich Nietzsche', text: 'Nietzsche accepted Schopenhauer\u2019s determinism of the empirical will but rejected his concept of transcendental freedom and the moralistic framework (guilt, responsibility) built upon it. For Nietzsche, the will is neither free nor unfree but simply the expression of the will-to-power; the concept of \u201cfreedom\u201d is a theological invention designed to make punishment intelligible (Twilight of the Idols, \u201cThe Four Great Errors,\u201d \u00a77).' },
        { philosopher: 'Christopher Janaway', text: 'Janaway\u2019s edition and introduction (The Two Fundamental Problems of Ethics, Cambridge, 2009) notes that On the Freedom of the Will is \u201cthe clearest and most rigorous of Schopenhauer\u2019s works \u2014 the one that best displays his philosophical talent for making a complex argument with precision and transparency.\u201d' }
    ],
    modernRelevance: 'On the Freedom of the Will remains one of the most influential texts in the free will debate. Schopenhauer\u2019s determinism \u2014 that character is innate, fixed, and unknowable except through observation \u2014 anticipates behaviourist psychology and contemporary discussions of the genetic bases of personality. The distinction between empirical and transcendental freedom resonates with contemporary compatibilism (Frankfurt, Dennett). The formula \u201cman can do what he wills but cannot will what he wills\u201d is one of the most quoted sentences in the history of philosophy.',
    context: 'Submitted to the Royal Norwegian Society of Sciences in Trondheim in response to a prize competition on the question \u201cCan the freedom of the human will be proved from self-consciousness?\u201d Awarded the prize in January 1839. Published in 1841 together with On the Basis of Morality in Die beiden Grundprobleme der Ethik (The Two Fundamental Problems of Ethics). Standard editions: SW IV (H\u00fcbscher); BM = Janaway (Cambridge, 2009); Payne translation also available (Berghahn, 1999).',
    relatedWorks: ['on-basis-of-morality', 'world-as-will-vol1', 'fourfold-root', 'world-as-will-vol2']
},

{
    id: 'on-basis-of-morality',
    title: 'On the Basis of Morality',
    greekTitle: '\u00dcber das Fundament der Moral',
    philosopher: 'schopenhauer',
    category: 'ethics',
    categoryLabel: 'Ethics',
    date: '1840 AD',
    dateSort: 1840,
    emoji: '\u2764\ufe0f',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 40000,
    shortDesc: 'The most powerful critique of Kantian ethics ever written \u2014 Schopenhauer\u2019s demonstration that morality is grounded not in rational duty but in compassion (Mitleid), the direct feeling of another\u2019s suffering as one\u2019s own.',
    summary: 'On the Basis of Morality (\u00dcber das Fundament der Moral), submitted to the Royal Danish Academy of Sciences in Copenhagen in 1840 in response to a prize competition on the question \u201cIs the source and basis of morality to be sought in an idea of morality which lies directly in consciousness, and in the analysis of the other fundamental moral concepts arising from this idea?\u201d \u2014 and not awarded the prize (Schopenhauer was the only entrant) \u2014 is the most sustained and most devastating critique of Kantian ethics in the history of philosophy.\n\nThe first part (\u00a7\u00a71\u201316) is a systematic demolition of Kant\u2019s moral philosophy. Schopenhauer attacks the categorical imperative as an empty formalism: a principle of mere logical consistency (universalisability) cannot generate substantive moral content. He attacks the concept of duty (Pflicht) as a covert theological concept: duty makes sense only in the context of a divine lawgiver, and Kant\u2019s attempt to derive moral obligation from pure reason alone is a secularised theology. He attacks the exclusion of feeling from morality: a morality that excludes compassion, love, and sympathy from the realm of the genuinely moral \u2014 that counts only actions done from cold duty as morally worthy \u2014 produces a perverse ethics in which the person of good character (who acts from natural compassion) is morally inferior to the person of bad character (who acts from duty in the teeth of his inclinations).\n\nThe second part (\u00a7\u00a717\u201322) presents Schopenhauer\u2019s positive ethics. The genuine basis of morality is compassion (Mitleid \u2014 literally \u201csuffering-with\u201d): the direct, immediate, non-inferential recognition of another\u2019s suffering as one\u2019s own. Compassion is not a reasoned conclusion (\u201cI ought to help this person because the categorical imperative requires it\u201d) but a felt identification: I suffer the other\u2019s pain as my own because, at the deepest metaphysical level, the distinction between self and other is illusory \u2014 the principium individuationis (space, time, and causality) that divides us is merely phenomenal. The Will is one and undivided; all suffering is ultimately my suffering.\n\nFrom compassion Schopenhauer derives two fundamental moral principles: (1) the principle of justice (Neminem laede \u2014 harm no one), which is compassion in its negative form; and (2) the principle of loving-kindness (Omnes, quantum potes, juva \u2014 help everyone as much as you can), which is compassion in its positive form. All genuine moral virtues are expressions of one or both of these principles.',
    themes: ['the critique of Kantian ethics', 'compassion as the basis of morality', 'the emptiness of the categorical imperative', 'duty as covert theology', 'the principium individuationis', 'justice and loving-kindness', 'the metaphysical foundation of ethics', 'feeling vs reason in morality'],
    keyCharacters: [],
    concepts: [
        'Compassion (Mitleid) \u2014 the direct, non-inferential recognition of another\u2019s suffering as one\u2019s own; the sole genuine moral motive (SW IV, 209\u2013221; BM 143\u2013153)',
        'The critique of the categorical imperative \u2014 a principle of mere logical consistency cannot generate substantive moral content; any maxim can be universalised if formulated carefully (SW IV, 125\u2013149; BM 87\u2013105)',
        'Duty (Pflicht) as covert theology \u2014 the concept of duty presupposes a divine lawgiver; Kant\u2019s moral philosophy is a secularised theology (SW IV, 120\u2013125; BM 83\u201387)',
        'The principium individuationis \u2014 space, time, and causality: the forms that divide reality into separate individuals; merely phenomenal; the Will is one and undivided (SW IV, 268\u2013272; BM 196\u2013200)',
        'Justice (Neminem laede) \u2014 harm no one; compassion in its negative form; the first fundamental moral principle (SW IV, 221\u2013229; BM 153\u2013160)',
        'Loving-kindness (Omnes juva) \u2014 help everyone as much as you can; compassion in its positive form; the second fundamental moral principle (SW IV, 229\u2013240; BM 160\u2013169)',
        'The exclusion of feeling as the perversion of ethics \u2014 Kant\u2019s doctrine that only actions from duty (not from compassion or love) have moral worth produces a morality in which good character is morally worthless (SW IV, 142\u2013149; BM 99\u2013105)',
        'Tat tvam asi (\u201cthat art thou\u201d) \u2014 the Upanishadic formula Schopenhauer cites as the metaphysical truth underlying compassion: the other is, at the deepest level, oneself (SW IV, 270; BM 198)'
    ],
    structure: 'Part One: Critique of the Kantian foundation of morality (\u00a7\u00a71\u201316)\n\u2014 \u00a7\u00a71\u20133: Introduction; the question posed by the Danish Academy\n\u2014 \u00a7\u00a74\u201311: The imperative form; duty as theological concept; the emptiness of the categorical imperative\n\u2014 \u00a7\u00a712\u201313: Kant\u2019s derived duties and their inadequacy\n\u2014 \u00a7\u00a714\u201316: The exclusion of feeling; the perversion of ethics\n\nPart Two: The foundation of morality (\u00a7\u00a717\u201322)\n\u2014 \u00a717: Statement of the problem\n\u2014 \u00a718: The motivating forces of human action: egoism, malice, compassion\n\u2014 \u00a719: The moral incentive: compassion (Mitleid)\n\u2014 \u00a7\u00a720\u201321: Justice and loving-kindness as the two expressions of compassion\n\u2014 \u00a722: The metaphysical basis: the principium individuationis and tat tvam asi',
    quote: 'Compassion is the real basis of all morality.',
    additionalQuotes: [
        { text: 'Boundless compassion for all living beings is the firmest and surest guarantee of pure moral conduct, and needs no casuistry. Whoever is filled with it will assuredly injure no one, do harm to no one, encroach on no man\u2019s rights; he will rather have regard for every one, forgive every one, help every one as far as he can.', citation: 'SW IV, 240; BM 169' },
        { text: 'The categorical imperative of Kant is au fond nothing but a paraphrase of the Golden Rule; only instead of saying \u201cDo unto others as you would have them do unto you,\u201d it says, in a roundabout way, \u201cAct only on that maxim which you can at the same time will to be a universal law.\u201d', citation: 'SW IV, 131; BM 91 (paraphrased)' },
        { text: 'Tat tvam asi \u2014 \u201cthat art thou\u201d \u2014 this is the formula that expresses the metaphysical truth on which all genuine morality rests: the distinction between self and other is merely phenomenal; at the deepest level, all beings are one.', citation: 'SW IV, 270; BM 198 (paraphrased)' },
        { text: 'The moral worth of an action lies not in the formula by which it is justified but in the compassion from which it springs.', citation: 'SW IV, 220; BM 153 (paraphrased)' }
    ],
    commentary: [
        { philosopher: 'Friedrich Nietzsche', text: 'Nietzsche\u2019s critique of Mitleid (compassion/pity) in The Genealogy of Morality (1887) and The Antichrist (1888) is directed primarily against Schopenhauer. Nietzsche argued that compassion is not a virtue but a weakness: it diminishes the sufferer by treating him as an object of pity and it diminishes the compassionate person by subordinating strength to suffering. Nietzsche\u2019s entire \u201ctransvaluation of values\u201d is an inversion of Schopenhauer\u2019s ethics of compassion.' },
        { philosopher: 'Peter Singer', text: 'Singer\u2019s Animal Liberation (1975) and Practical Ethics (1979) develop Schopenhauer\u2019s thesis that compassion extends to all sentient beings. Schopenhauer was one of the first Western philosophers to argue that the suffering of animals has moral significance and that our treatment of animals must be guided by the same compassion we feel for human beings (SW IV, 241\u2013244; BM 170\u2013173).' },
        { philosopher: 'Christopher Janaway', text: 'Janaway\u2019s introduction to the Cambridge edition (2009) argues that the critique of Kant in the first part is philosophically more important than the positive ethics of the second part: \u201cSchopenhauer\u2019s demolition of the categorical imperative is the most sustained and most penetrating critique Kant\u2019s moral philosophy has ever received. Every subsequent critic of Kantian ethics \u2014 from Hegel through Mill to Williams \u2014 has repeated arguments Schopenhauer stated first.\u201d' },
        { philosopher: 'Arthur Danto', text: 'Danto noted in his essay on Schopenhauer (1999) that the ethics of compassion is the most philosophically defensible and the most humanly attractive element of Schopenhauer\u2019s system: \u201cIt is the one part of his philosophy that can survive the collapse of its metaphysical foundations.\u201d' }
    ],
    modernRelevance: 'On the Basis of Morality remains the most powerful philosophical critique of Kantian ethics and the most influential philosophical defence of compassion as the foundation of morality. The ethics of compassion has been developed by Singer (animal rights), by Nussbaum (the capabilities approach), and by Buddhist-influenced Western ethics. Schopenhauer\u2019s insistence that feeling, not reason, is the source of genuine moral motivation anticipates the contemporary debate between moral rationalism and moral sentimentalism. The tat tvam asi formula has been central to the dialogue between Western and Eastern philosophy.',
    context: 'Submitted to the Royal Danish Academy in Copenhagen in 1840. Schopenhauer was the only entrant but was not awarded the prize; the Academy stated that the essay did not adequately answer the set question and criticised its disrespectful treatment of Fichte, Schelling, and Hegel. Schopenhauer was furious and published the essay in 1841 together with On the Freedom of the Will (which had won the Norwegian prize) as Die beiden Grundprobleme der Ethik, adding a contemptuous preface recounting the Academy\u2019s refusal. Standard editions: SW IV (H\u00fcbscher); BM = Janaway (Cambridge, 2009); Payne translation (Berghahn, 1995).',
    relatedWorks: ['on-freedom-of-will', 'world-as-will-vol1', 'world-as-will-vol2', 'parerga-paralipomena']
},

{
    id: 'on-will-in-nature',
    title: 'On the Will in Nature',
    greekTitle: '\u00dcber den Willen in der Natur',
    philosopher: 'schopenhauer',
    category: 'natural-philosophy',
    categoryLabel: 'Natural Philosophy',
    date: '1836 AD',
    dateSort: 1836,
    emoji: '\uD83C\uDF31',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 35000,
    shortDesc: 'Schopenhauer\u2019s demonstration that the empirical sciences \u2014 physiology, comparative anatomy, botany, physics, and astronomy \u2014 confirm the central thesis of The World as Will and Representation: that the inner nature of all phenomena is Will.',
    summary: 'On the Will in Nature (\u00dcber den Willen in der Natur. Eine Er\u00f6rterung der Best\u00e4tigungen, welche die Philosophie des Verfassers seit ihrem Auftreten durch die empirischen Wissenschaften erhalten hat), published in Frankfurt by Siegmund Schmerber in 1836 (second edition 1854), is Schopenhauer\u2019s attempt to demonstrate that the empirical sciences provide independent confirmation of his metaphysics of the Will.\n\nThe work surveys developments in the natural sciences since the publication of WWR in 1818 and argues that in every domain \u2014 physiology, comparative anatomy, plant physiology, physical astronomy, linguistics, animal magnetism, magic, and sinology \u2014 the discoveries of empirical researchers point toward the same conclusion: the inner nature of all natural phenomena is Will. Scientists, unaware of Schopenhauer\u2019s philosophy, are nevertheless arriving at its conclusions through their own investigations.\n\nThe chapter on \u201cPhysical Astronomy\u201d argues that gravity \u2014 the universal force of attraction between all bodies \u2014 is an expression of the Will at the most fundamental level of inorganic nature. The chapter on \u201cPlant Physiology\u201d argues that the growth, tropism, and adaptive behaviour of plants demonstrate the operation of Will in organisms that lack consciousness entirely. The chapter on \u201cComparative Anatomy\u201d argues that the structure of animal bodies is determined by the specific direction of the Will in each species: the predator\u2019s teeth, the bird\u2019s wings, the spider\u2019s web are all objectifications of the Will-to-Live in its specific forms.\n\nThe chapter on \u201cSinology\u201d presents Schopenhauer\u2019s most extended engagement with Chinese philosophy, arguing that the Tao of Laozi and the concept of Te correspond to his own concept of the Will as the inner nature of all things.\n\nSchopenhauer regarded On the Will in Nature as the best introduction to his philosophy: it presents the central metaphysical thesis in the most concrete and empirically grounded form.',
    themes: ['the Will in nature', 'the empirical confirmation of the metaphysics of the Will', 'gravity as Will', 'plant physiology and the Will', 'comparative anatomy', 'Chinese philosophy and the Will', 'the relationship between philosophy and empirical science'],
    keyCharacters: [],
    concepts: [
        'The Will in nature \u2014 the inner nature of all natural phenomena, from gravity to organic life, is Will; the sciences confirm this without knowing it (SW IV, 285\u2013290; WN 21\u201325)',
        'Gravity as Will \u2014 the universal attraction between bodies is the most elementary expression of the Will at the inorganic level (SW IV, 333\u2013346; WN 59\u201370)',
        'Plant physiology as evidence of Will \u2014 plant growth, tropism, and adaptation demonstrate the operation of Will in organisms without consciousness (SW IV, 302\u2013318; WN 38\u201352)',
        'Comparative anatomy and the Will \u2014 animal bodies are objectifications of the Will-to-Live: their structure is determined by the specific form of willing characteristic of each species (SW IV, 318\u2013333; WN 52\u201359)',
        'The Tao and the Will \u2014 Schopenhauer argues that Laozi\u2019s Tao and the concept of Te correspond to the Will as thing-in-itself (SW IV, 369\u2013381; WN 94\u2013104)',
        'The convergence of philosophy and science \u2014 empirical science, when it reaches its explanatory limits, points toward metaphysics; philosophy provides the interpretation that science cannot supply from its own resources (SW IV, 285\u2013290; WN 21\u201325)'
    ],
    structure: 'Introduction: The purpose of the essay; the relationship between philosophy and empirical science\n\nChapter 1: Physiology and pathology\n\u2014 The body as objectification of the Will; healing and disease\n\nChapter 2: Comparative anatomy\n\u2014 Animal structure as determined by the direction of the Will\n\nChapter 3: Plant physiology\n\u2014 Growth, tropism, and adaptation as expressions of Will\n\nChapter 4: Physical astronomy\n\u2014 Gravity as the most elementary expression of Will\n\nChapter 5: Linguistics\n\nChapter 6: Animal magnetism and magic\n\nChapter 7: Sinology\n\u2014 The Tao as the Will; Laozi and Schopenhauer\n\nConclusion: The convergence of philosophy and science',
    quote: 'Every glance at the world, which it is the task of philosophy to explain, confirms that the will-to-live, far from being an arbitrary hypostasis or an empty phrase, is the only true expression of the innermost nature of the world.',
    additionalQuotes: [
        { text: 'Teeth, gullet, and intestinal canal are objectified hunger; the genitals are objectified sexual desire; grasping hands and swift feet correspond to the more indirect strivings of the will which they represent.', citation: 'SW IV, 320; WN 53 (paraphrased; cf. WWR I \u00a720)' },
        { text: 'Gravity, which operates in every stone, is fundamentally the same as what manifests itself in human actions \u2014 only at the lowest grade of the Will\u2019s objectification.', citation: 'SW IV, 340; WN 65 (paraphrased)' },
        { text: 'The Tao, which Laozi describes as the origin and ground of all things, the unnameable something from which heaven and earth arise \u2014 is what I call the Will.', citation: 'SW IV, 372; WN 96 (paraphrased)' }
    ],
    commentary: [
        { philosopher: 'Christopher Janaway', text: 'Janaway (2002) notes that On the Will in Nature is the work Schopenhauer himself recommended as the best introduction to his system: \u201cIt presents the metaphysics of the Will in its most concrete and most empirically grounded form, without the Kantian epistemological apparatus that makes WWR I so forbidding.\u201d' },
        { philosopher: 'Bryan Magee', text: 'Magee (1983/1997) argues that the work\u2019s central claim \u2014 that empirical science, when pressed to its explanatory limits, points toward the metaphysics of the Will \u2014 is philosophically more sophisticated than it first appears. Schopenhauer is not claiming that science proves the Will; he is claiming that the most fundamental scientific concepts (force, energy, drive, instinct) are, when properly understood, phenomenal expressions of what philosophy knows as the Will.' },
        { philosopher: 'Moira Nicholls', text: 'Nicholls\u2019s work on Schopenhauer and Chinese philosophy has shown that the \u201cSinology\u201d chapter is one of the earliest serious Western philosophical engagements with Daoist thought \u2014 and that Schopenhauer\u2019s identification of the Tao with the Will, while oversimplifying Laozi, represents a genuine philosophical insight into the structural parallels between the two traditions.' }
    ],
    modernRelevance: 'On the Will in Nature\u2019s argument that empirical science, at its explanatory limits, points toward metaphysics has been compared to contemporary discussions of the \u201cexplanatory gap\u201d between physical description and conscious experience (the hard problem of consciousness). Its treatment of plant behaviour as purposive activity without consciousness anticipates contemporary research on plant intelligence and the debate about whether cognition requires a nervous system. Its engagement with Chinese philosophy makes it a foundational text for the comparative philosophy of East and West.',
    context: 'Published in Frankfurt by Schmerber in 1836. A second, expanded edition appeared in 1854. The work was written during Schopenhauer\u2019s years of obscurity in Frankfurt (from 1833 to his death in 1860), when he was virtually unknown. He regarded it as an important supplement to WWR, providing empirical evidence for conclusions reached through philosophical argument. Standard editions: SW IV (H\u00fcbscher); WN = Payne (Berg, 1992).',
    relatedWorks: ['world-as-will-vol1', 'world-as-will-vol2', 'fourfold-root', 'on-vision-colours']
}

);
