/* DATA PART 16b — Critique of Practical Reason + Groundwork of the Metaphysics of Morals (Kant) */
window.WORKS.push(

{
    id: 'critique-practical-reason',
    title: 'Critique of Practical Reason',
    greekTitle: 'Kritik der praktischen Vernunft',
    philosopher: 'kant',
    category: 'ethics',
    categoryLabel: 'Ethics',
    date: '1788 AD',
    dateSort: 1788,
    emoji: '⭐',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 75000,
    shortDesc: 'The second Critique — Kant\'s systematic demonstration that pure reason is practical, that the moral law is a fact of reason known with absolute certainty, and that morality requires rational faith in God, freedom, and immortality.',
    summary: 'The Critique of Practical Reason, published in 1788, is the second of Kant\'s three Critiques and the systematic foundation of his moral philosophy. Where the first Critique had shown that theoretical reason cannot prove the existence of God, freedom, or the immortality of the soul, the second Critique demonstrates that practical reason — reason in its capacity to determine the will — not only presupposes these ideas but provides rational grounds for believing in them. The moral law, Kant argues, is not derived from experience, from divine command, or from any conception of the good; it is a "fact of reason" (Faktum der Vernunft) — a fundamental datum of rational consciousness that every rational being recognizes as unconditionally binding.\n\nThe work is structured as a mirror image of the first Critique. The Analytic of Pure Practical Reason establishes the supreme principle of morality — the categorical imperative — and argues that this principle is the only one that a pure practical reason could adopt, because any principle grounded in desire, inclination, or the pursuit of happiness would be merely contingent. The moral law commands unconditionally, regardless of what any particular agent wants; its authority derives not from its consequences but from its form — its universalizability.\n\nThe Analytic also contains Kant\'s theory of moral motivation. He argues that the only genuinely moral motive is respect (Achtung) for the moral law itself — a unique feeling produced by reason\'s awareness of its own legislative authority. Actions done from inclination, however benevolent, have no genuine moral worth; only actions done from duty deserve moral praise.\n\nThe Dialectic of Pure Practical Reason addresses the postulates of practical reason. Kant argues that morality commits us to the belief that virtue and happiness can ultimately be united in the "highest good" (summum bonum). Since this unity is not achievable in this life, practical reason requires us to postulate the immortality of the soul (to allow for infinite progress toward moral perfection) and the existence of God (as the being who can guarantee the ultimate harmony of virtue and happiness).\n\nThe work concludes with one of the most famous passages in all of philosophy: "Two things fill the mind with ever new and increasing admiration and reverence, the more often and more steadily one reflects on them: the starry heavens above me and the moral law within me."',
    themes: ['The Moral Law as Fact of Reason', 'The Categorical Imperative', 'Duty and Inclination', 'Respect for the Moral Law', 'Autonomy of the Will', 'The Highest Good', 'The Postulates of Practical Reason', 'God, Freedom, and Immortality', 'The Primacy of Practical Reason'],
    keyCharacters: [],
    concepts: [
        'The fact of reason (Faktum der Vernunft) — the moral law is not derived from anything more fundamental but is immediately recognized by every rational being as unconditionally binding',
        'The categorical imperative — act only according to that maxim through which you can at the same time will that it become a universal law',
        'Autonomy of the will — the will is a law to itself; genuine morality consists in self-legislation, not obedience to external authority',
        'Heteronomy — the corruption of morality that results from grounding the moral law in desire, inclination, divine command, or any external source',
        'Duty (Pflicht) — the necessity of acting from respect for the moral law, regardless of inclination',
        'Respect (Achtung) — the unique moral feeling produced by reason\'s awareness of the moral law; not an empirical emotion but a rational affect',
        'The highest good (summum bonum) — the union of virtue and happiness; the complete object of pure practical reason',
        'The postulates of practical reason — freedom (as the condition of moral agency), immortality (as the condition of infinite moral progress), God (as the guarantor of the highest good)'
    ],
    structure: 'Preface: The relation of the second Critique to the first; the primacy of practical reason\n\nPart One: Analytic of Pure Practical Reason\n— Chapter I: The principles of pure practical reason; the moral law as its fundamental law; the categorical imperative; autonomy vs heteronomy\n— Chapter II: The concept of an object of pure practical reason (the good and the evil)\n— Chapter III: The incentives of pure practical reason (the feeling of respect)\n\nPart Two: Dialectic of Pure Practical Reason\n— The antinomy of practical reason: virtue and happiness\n— The highest good as the complete object of practical reason\n— The postulates: immortality, freedom, God\n— The primacy of practical over theoretical reason\n\nConclusion: The starry heavens and the moral law',
    quote: 'Two things fill the mind with ever new and increasing admiration and reverence, the more often and more steadily one reflects on them: the starry heavens above me and the moral law within me.',
    additionalQuotes: [
        { text: 'Act so that the maxim of your will could always hold at the same time as a principle of a universal legislation.', citation: 'Critique of Practical Reason, §7' },
        { text: 'Duty! Thou sublime and mighty name that dost embrace nothing charming or insinuating but requirest submission — and yet seekest not to move the will by threatening, but merely holdest forth a law which of itself finds entrance into the mind.', citation: 'Critique of Practical Reason, Part I, Chapter III' },
        { text: 'Freedom is the ratio essendi of the moral law, and the moral law is the ratio cognoscendi of freedom.', citation: 'Critique of Practical Reason, Preface, footnote' }
    ],
    commentary: [
        { philosopher: 'G.W.F. Hegel', text: 'Hegel\'s critique of the second Critique in the Philosophy of Right (1820) is the most consequential objection to Kantian ethics in the history of philosophy. Kant established the autonomy of morality — the principle that the will is a law to itself — and this, Hegel acknowledged, is his imperishable contribution to ethics. But his formalism is empty: the categorical imperative, without content drawn from the ethical life (Sittlichkeit) of actual communities, can determine nothing. Hegel\'s famous example — the wrongness of property-theft cannot be derived from the categorical imperative alone, because one can universalize the maxim "steal if necessary" without formal contradiction — is designed to show that Kant\'s moral law gives us the form of morality without its substance. The substance comes only from the concrete ethical institutions of family, civil society, and the state, whose rational articulation is the task of political philosophy rather than pure moral theory.' },
        { philosopher: 'Friedrich Schiller', text: 'Schiller\'s famous epigram — "Gladly I serve my friends, but alas I do it with pleasure. Hence I am plagued with doubt that I am not a virtuous person" — is the sharpest and most entertaining criticism of the second Critique\'s claim that only actions done from duty, not from inclination, have moral worth. Schiller\'s point is that Kant\'s moral psychology is not just austere but psychologically incoherent: if acting from love, compassion, or natural benevolence has no moral worth, then the person of excellent character — whose virtuous actions flow naturally from a cultivated moral sensibility — is morally inferior to the person who does the right thing in the teeth of reluctance. Kant\'s response — that the person of good inclinations has "legality" even if not "morality" — has never fully satisfied critics, and the debate about the role of inclination and emotion in moral life initiated by Schiller\'s epigram has shaped moral philosophy from Hegel through the British Idealists to contemporary virtue ethics.' },
        { philosopher: 'John Rawls', text: 'Rawls\'s A Theory of Justice (1971) and his later Kantian Constructivism in Moral Theory (1980) are the most influential twentieth-century development of the moral philosophy of the second Critique. Rawls argued that Kant\'s categorical imperative, properly understood, is not an empty formalism but a substantive procedure of construction from which the principles of justice can be derived. His own device of the "original position" — behind the veil of ignorance — is a Kantian device: it models the perspective of a rational agent who chooses principles of justice without knowledge of the particular facts about themselves that would make any principle biased in their favour. The resulting principles of justice are Kantian in their structure: they express the equal dignity of persons as free and equal rational beings, they are universalizable, and they constitute the rational terms of cooperation for a society of persons who regard each other as ends in themselves.' },
        { philosopher: 'Christine Korsgaard', text: 'Korsgaard\'s Creating the Kingdom of Ends (1996) and Self-Constitution: Agency, Identity, and Integrity (2009) develop the second Critique\'s account of the fact of reason into a constructivist metaethics that grounds the authority of the moral law in the structure of rational agency itself. Korsgaard\'s central insight — anticipated in the second Critique but not fully developed there — is that the categorical imperative is not merely a formal principle for testing maxims but an expression of what it means to be a unified rational agent. A rational agent must act on principles, and the principles she acts on must be capable of being endorsed from the standpoint of her rational nature as a whole. The moral law is the expression of this requirement at its most general: it is what rational self-constitution demands. This neo-Kantian constructivism has been the most influential approach to metaethics in Anglophone moral philosophy since the 1990s.' },
        { philosopher: 'Friedrich Nietzsche', text: 'Nietzsche\'s critique of the categorical imperative in Beyond Good and Evil (1886) and The Genealogy of Morality (1887) is the most radical and the most philosophically penetrating challenge the second Critique has ever faced. Nietzsche argued that the categorical imperative smells of cruelty — that it is the morality of the herd elevated to a metaphysical principle. The demand that everyone act as everyone else would act, that individuality be sacrificed to the universality of law, is for Nietzsche a covert expression of ressentiment: the revenge of the weak on the strong, of the mediocre on the exceptional. The moral law\'s claim to absolute authority is not a deliverances of pure reason but a piece of historical psychology — the latest form of the ascetic ideal, the self-denial and self-torture that European culture has called morality since Paul. Nietzsche\'s genealogy of Kantian duty does not refute the second Critique on its own terms, but it raises the question that Kant never adequately addressed: why should we believe that the structure of rational agency, as Kant describes it, gives us genuine moral content rather than the historically conditioned prejudices of a particular cultural moment?' }
    ],
    modernRelevance: 'The Critique of Practical Reason remains the most influential work of ethical theory in the Western philosophical tradition. The categorical imperative — in its universalizability formulation, its humanity formulation, and its kingdom of ends formulation — structures contemporary moral philosophy, political theory, human rights law, and bioethics. Rawls\'s A Theory of Justice is explicitly Kantian in its foundations; Habermas\'s discourse ethics is a communicative reformulation of the categorical imperative; Korsgaard\'s constructivism develops the second Critique\'s account of rational agency into a complete ethical theory. Kant\'s doctrine of autonomy — self-legislation, the capacity to give oneself the moral law — is the philosophical foundation of modern liberal democracy and of the concept of human dignity enshrined in international law.',
    context: 'Kant published the Critique of Practical Reason in 1788, seven years after the first Critique and three years after the Groundwork. It was written relatively quickly — in a few months, compared to the decade-long gestation of the first Critique — and reflects the confidence of a philosopher who had found his system. The work was better received than the first Critique, partly because Kant\'s reputation had grown enormously and partly because its central doctrine — the absolute authority of the moral law — spoke to a wider audience. The famous concluding sentence about the starry heavens and the moral law is inscribed on Kant\'s tombstone in Königsberg.',
    relatedWorks: ['critique-pure-reason', 'groundwork-metaphysics-morals', 'critique-judgment', 'metaphysics-of-morals', 'religion-boundaries-reason']
},

{
    id: 'groundwork-metaphysics-morals',
    title: 'Groundwork of the Metaphysics of Morals',
    greekTitle: 'Grundlegung zur Metaphysik der Sitten',
    philosopher: 'kant',
    category: 'ethics',
    categoryLabel: 'Ethics',
    date: '1785 AD',
    dateSort: 1785,
    emoji: '📐',
    cardSize: 'normal',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 30000,
    shortDesc: 'The single most influential work of moral philosophy ever written — Kant\'s derivation of the supreme principle of morality from the concept of a rational will, yielding the categorical imperative and the absolute dignity of persons as ends in themselves.',
    summary: 'The Groundwork of the Metaphysics of Morals, published in 1785, is the most widely read, most frequently taught, and most deeply influential work in the history of moral philosophy. In fewer than a hundred pages, Kant accomplishes what no philosopher before him had achieved: a rigorous derivation of the supreme principle of morality from the bare concept of a rational will.\n\nThe First Section begins from common moral knowledge and analyses it to reveal its underlying structure. Kant argues that the only thing that is good without qualification is a good will — a will that acts from duty, from recognition of and submission to the moral law. From this analysis Kant extracts the concept of duty and the first formulation of the categorical imperative: act only according to that maxim you can simultaneously will as universal law.\n\nThe Second Section introduces the distinction between hypothetical imperatives (which command conditionally) and categorical imperatives (which command unconditionally). Kant then derives three formulations of the categorical imperative, which he claims are equivalent expressions of the same fundamental principle. The Formula of Universal Law: "Act only according to that maxim through which you can at the same time will that it become a universal law." The Formula of Humanity: "Act so that you treat humanity, whether in your own person or in that of another, always as an end and never merely as a means." The Formula of the Kingdom of Ends: "Act according to maxims of a universally legislating member of a merely possible kingdom of ends."\n\nThese three formulations — universalizability, the dignity of persons, and the ideal moral community — are the pillars of Kantian ethics and, arguably, of modern moral consciousness itself. The concept of human dignity — that every rational being has an absolute, unconditional worth that may never be traded away — is Kant\'s most consequential contribution to civilization.',
    themes: ['The Good Will', 'Duty and Inclination', 'The Categorical Imperative', 'Universalizability', 'Humanity as an End in Itself', 'The Kingdom of Ends', 'Autonomy and Dignity', 'Hypothetical vs Categorical Imperatives', 'Freedom and Morality'],
    keyCharacters: [],
    concepts: [
        'The good will — the only thing good without qualification; the will that acts from duty rather than inclination',
        'Maxim — the subjective principle of an action; the rule the agent follows in acting, which must be universalizable to be morally permissible',
        'The categorical imperative (Formula of Universal Law) — act only according to that maxim you can simultaneously will as a universal law',
        'The categorical imperative (Formula of Humanity) — treat humanity in every person always as an end, never merely as a means',
        'The categorical imperative (Formula of the Kingdom of Ends) — act as a legislating member of a universal kingdom of rational ends',
        'Hypothetical vs categorical imperatives — conditional commands dependent on desires vs unconditional commands binding on all rational beings',
        'Autonomy — the will\'s property of being a law to itself; the ground of human dignity and the source of the moral law\'s authority',
        'Dignity (Würde) — the absolute, unconditional, incomparable worth of every rational being; what has dignity is beyond all price',
        'The kingdom of ends (Reich der Zwecke) — the ideal moral community in which every rational being is simultaneously legislator and subject'
    ],
    structure: 'Preface: The need for a pure moral philosophy; the distinction between empirical and a priori ethics\n\nSection I: Transition from common rational moral cognition to philosophical moral cognition\n— The good will and its unconditional goodness\n— Duty, inclination, and the motive of respect\n— The first formulation of the categorical imperative (universal law)\n\nSection II: Transition from popular moral philosophy to the metaphysics of morals\n— Hypothetical and categorical imperatives\n— The three formulations of the categorical imperative\n— Four examples: false promising, suicide, neglect of talents, refusal of aid\n— Autonomy and dignity; the kingdom of ends\n\nSection III: Transition from the metaphysics of morals to the critique of pure practical reason\n— Freedom and the moral law; the reciprocity thesis\n— The phenomenal self and the noumenal self',
    quote: 'Act so that you treat humanity, whether in your own person or in the person of any other, always at the same time as an end, never merely as a means.',
    additionalQuotes: [
        { text: 'Nothing in the world — indeed nothing even beyond the world — can possibly be conceived which could be called good without qualification except a good will.', citation: 'Groundwork, Section I, 4:393' },
        { text: 'Act only according to that maxim through which you can at the same time will that it become a universal law.', citation: 'Groundwork, Section II, 4:421' },
        { text: 'In the kingdom of ends everything has either a price or a dignity. What has a price can be replaced by something else as its equivalent; what is raised above all price and therefore admits of no equivalent has a dignity.', citation: 'Groundwork, Section II, 4:434' }
    ],
    commentary: [
        { philosopher: 'G.W.F. Hegel', text: 'Hegel\'s critique of the Groundwork is one of the most productive disputes in the history of ethics. He acknowledged that Kant\'s concept of autonomy — the will as a law to itself — is the most important philosophical contribution to morality since Aristotle. But he argued that the categorical imperative, in its abstract universalizability formulation, is an empty formalism: it cannot determine any specific moral content without drawing on the concrete ethical substance of actual social life. Any maxim can be universalized if formulated with sufficient care; the categorical imperative alone cannot tell us what to do. The real source of moral content is Sittlichkeit — the ethical life of families, civil society, and the state — which provides the substantive norms that the categorical imperative can only ratify after the fact. Hegel\'s critique launched the communitarian tradition in ethics that runs through Bradley, T.H. Green, and contemporary communitarians like Sandel and MacIntyre.' },
        { philosopher: 'Alasdair MacIntyre', text: 'MacIntyre\'s After Virtue (1981) mounted the most philosophically ambitious twentieth-century critique of the Groundwork\'s project. He argued that the Groundwork fails on its own terms: Kant cannot derive substantive moral content from the purely formal requirement of universalizability. Any maxim can be universalized if described with sufficient specificity, so the categorical imperative functions as a mirror that reflects whatever content the agent brings to it. More fundamentally, MacIntyre argued that the entire Enlightenment project of grounding morality in universal reason — of which the Groundwork is the supreme achievement — is historically unintelligible: moral concepts have their proper home in particular traditions and practices, and abstract them from those traditions and they lose their meaning. The Groundwork\'s morality of pure reason is not a discovery of the permanent truth of ethics but the historically specific morality of the Enlightenment, now deracinated from the tradition that gave it sense.' },
        { philosopher: 'Allen Wood', text: 'Wood\'s Kant\'s Ethical Thought (1999) and Kantian Ethics (2008) are the most philosophically comprehensive and sympathetic reconstructions of the Groundwork\'s project in contemporary scholarship. Wood argues that the Formula of Humanity — "treat persons always as ends, never merely as means" — is the single most important sentence in the history of ethics, and that it generates substantive moral content far beyond what the universalizability formula alone can provide. On Wood\'s reading, the Formula of Humanity grounds human rights, condemns exploitation, and establishes the absolute worth of every person in a way that is independent of any contingent cultural norms. Wood also argues that the Groundwork\'s kingdom of ends — the ideal moral community of rational beings who legislate universal laws — is not a utopian fiction but a practical ideal that gives direction to moral and political life.' },
        { philosopher: 'Martha Nussbaum', text: 'Nussbaum\'s engagement with the Groundwork in Creating Capabilities (2011) and her earlier work on Aristotelian ethics represents the most important feminist critique of Kantian moral theory. Nussbaum agrees with Kant that every person has a dignity that must be respected, but she argues that the Groundwork\'s account of what dignity consists in is too thin: it focuses on rational agency while neglecting the embodied, emotional, and social dimensions of human life that are equally constitutive of personhood. A theory of justice adequate to the full range of human capabilities — including health, emotion, affiliation, play, and political participation — requires more than the categorical imperative; it requires an account of what it means to live a fully human life, which is Aristotelian rather than Kantian in its structure. Nevertheless, Nussbaum credits Kant with the most consequential philosophical insight in modern ethics: that every human being has a dignity that admits of no equivalent and that grounds the absolute prohibition on treating persons as mere instruments.' }
    ],
    modernRelevance: 'The Groundwork is not merely historically influential — it is the active foundation of contemporary moral philosophy, political theory, and international law. The Universal Declaration of Human Rights (1948), the European Convention on Human Rights (1950), and the German Basic Law (1949 — which opens with "Human dignity shall be inviolable") are all explicitly or implicitly Kantian documents. The categorical imperative, in its universalizability formulation, is the basis of contractualist ethical theories from Rawls through Scanlon. The humanity formulation structures contemporary bioethics, informed consent doctrine, and the prohibition on treating persons as mere instruments. The concept of autonomy is the philosophical foundation of liberal democracy, the doctrine of individual rights, and consent-based political legitimacy.',
    context: 'Kant published the Groundwork in 1785, between the first and second editions of the Critique of Pure Reason. He described it as a preliminary work — a "groundwork" that would lay the foundation for the full metaphysics of morals he planned to write later (which appeared in 1797). Despite its preliminary character, the Groundwork became the most widely read and most influential of all Kant\'s works. Its brevity (compared to the Critiques), its relative accessibility, and the power of its central formulations — especially the humanity formula — made it the text through which most readers first encounter Kant\'s moral philosophy.',
    relatedWorks: ['critique-practical-reason', 'metaphysics-of-morals', 'critique-pure-reason', 'religion-boundaries-reason', 'perpetual-peace']
}

);
