/* DATA PART 20e — Kierkegaard: The Sickness Unto Death + Works of Love + Attack upon Christendom */
window.WORKS.push(

{
    id: 'sickness-unto-death',
    title: 'The Sickness Unto Death',
    greekTitle: 'Sygdommen til D\u00f8den',
    philosopher: 'kierkegaard',
    category: 'metaphysics',
    categoryLabel: 'Psychology & Philosophy of Religion',
    date: '1849 AD',
    dateSort: 1849,
    emoji: '\u2620\uFE0F',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 65000,
    shortDesc: 'The most searching analysis of the human condition in modern philosophy \u2014 Kierkegaard\u2019s account of despair as the universal human sickness, the failure to be oneself before God, and the categories of consciousness and selfhood that determine the depth of one\u2019s despair and the possibility of genuine faith.',
    summary: 'The Sickness Unto Death: A Christian Psychological Exposition for Upbuilding and Awakening (Sygdommen til D\u00f8den: En christelig psychologisk Udvikling til Opbyggelse og Opv\u00e6kkelse), published 30 July 1849 under the pseudonym Anti-Climacus (with Kierkegaard named as editor) by C.A. Reitzel in Copenhagen, is the most concentrated and most psychologically penetrating of Kierkegaard\u2019s works. Anti-Climacus is the inverse of Johannes Climacus: where Climacus examines Christianity from outside without claiming to be a Christian, Anti-Climacus writes as a Christian of extraordinary intensity, from a position Kierkegaard himself considers too high for his own spiritual condition.\n\nThe work opens with one of the most analysed passages in modern philosophy: the definition of the self. \u201cA human being is spirit. But what is spirit? Spirit is the self. But what is the self? The self is a relation that relates itself to itself.\u201d The self is not a simple substance but a structure of relations: it is constituted by the relation between finite and infinite, temporal and eternal, freedom and necessity. But it is not merely a relation \u2014 it is a relation that relates to itself, a self-reflexive structure of consciousness.\n\nDespair \u2014 the \u201csickness unto death\u201d \u2014 is the misrelation within this structure: the failure to be the self that one is, or the refusal to be the self that one is. Despair is universal: every human being who has not grounded their self \u201ctransparently in the power that established it\u201d is in despair, even if they are unaware of it. Indeed, unawareness of despair is its most common form: the person who does not know they are in despair is more deeply in despair than the one who is conscious of it.\n\nKierkegaard\u2019s typology of despair is one of the most finely calibrated in philosophical literature. The analysis moves from the lowest (unconscious despair) through despair at not willing to be oneself (weakness) to the highest and most intense (despair at willing to be oneself \u2014 defiance). The despairing person who defiantly wills to be the self they have constituted, in rebellion against the power that established them, is in the most intense form of despair \u2014 and the closest to genuine selfhood, because they at least know what they are doing.\n\nThe second part of the work analyses despair as sin: despair before God, the refusal of the self to ground itself in God. Sin is not primarily the violation of ethical rules but the existential condition of being in despair before God, of not willing to be transparent in the power that established one. The antidote to sin is not ethical improvement but faith: the willingness to ground the self in God, to allow the relation to God to be the foundation of one\u2019s selfhood.',
    themes: ['the definition of the self', 'despair as the universal human sickness', 'the typology of despair', 'despair in weakness vs despair in defiance', 'sin as despair before God', 'faith as the cure for despair', 'consciousness and depth of despair', 'Anti-Climacus', 'the self as relation of relations'],
    keyCharacters: [
        { name: 'Anti-Climacus', role: 'The pseudonymous author; the inverse of Johannes Climacus; writes as an ideally intense Christian from a position Kierkegaard considers too high for his own spiritual state; the works attributed to Anti-Climacus represent the highest demands of Christianity' }
    ],
    concepts: [
        'The self as a relation that relates itself to itself \u2014 the self is not a substance but a structure: the relation between finite/infinite, temporal/eternal, freedom/necessity; and a self-reflexive consciousness of this relation',
        'Despair \u2014 the misrelation within the self\u2019s structure; the failure or refusal to be the self one is; the universal human condition for those not grounded in God',
        'Despair in not willing to be oneself \u2014 the despair of weakness: flight from the self, refusal to acknowledge one\u2019s own finitude and freedom',
        'Despair in willing to be oneself \u2014 the despair of defiance: the self that wills to constitute itself in rebellion against the power that established it; the most intense form of despair',
        'Consciousness as the measure of despair \u2014 the more conscious of its own condition the despairing self is, the more intense the despair; but also the closer to genuine selfhood',
        'Sin as despair before God \u2014 despair is sin when it is understood before God; sin is not primarily ethical transgression but the existential condition of not grounding the self in God',
        'Faith as the cure for despair \u2014 faith is the condition in which the self is transparent in the power that established it; the opposite of despair; the self that has become itself by grounding itself in God'
    ],
    structure: 'Introduction: The sickness unto death; the definition of despair\n\nPart One: The Sickness Unto Death is Despair\n\u2014 A. Despair is a sickness of the spirit, of the self (definition of the self)\n\u2014 B. The universality of despair\n\u2014 C. The forms of despair\n  \u2014 a. Despair as defined by consciousness\n  \u2014 b. Despair as defined by the constituents of the self\n    \u2014 The despair of infinitude / finitude\n    \u2014 The despair of possibility / necessity\n  \u2014 c. Despair as defined by consciousness continued\n    \u2014 Not willing to be oneself (despair of weakness)\n    \u2014 Willing to be oneself (despair of defiance)\n\nPart Two: Despair is Sin\n\u2014 A. Gradations in the consciousness of sin\n\u2014 B. Socrates\u2019 definition of sin (sin as ignorance; Kierkegaard\u2019s correction)\n\u2014 C. The sin of despairing of the forgiveness of sins\n\u2014 D. The sin against the Holy Spirit',
    quote: 'The formula that describes the state of the self when despair is completely rooted out is this: in relating itself to itself and in willing to be itself, the self rests transparently in the power that established it.',
    additionalQuotes: [
        { text: 'The most common form of despair is not being who you are.', citation: 'The Sickness Unto Death (paraphrased from Part One, C)' },
        { text: 'A human being is spirit. But what is spirit? Spirit is the self. But what is the self? The self is a relation that relates itself to itself.', citation: 'The Sickness Unto Death, Part One, A' },
        { text: 'There is so much talk about wasted lives \u2014 but only that person\u2019s life was wasted who lived on, so deceived by life\u2019s joys or its sorrows that he never became decisively, eternally conscious of himself as spirit, as self.', citation: 'The Sickness Unto Death, Part One, B' }
    ],
    commentary: [
        { philosopher: 'Paul Ricoeur', text: 'Ricoeur\u2019s Oneself as Another (1990) develops the phenomenology of selfhood through an engagement with Kierkegaard\u2019s definition of the self in The Sickness Unto Death. Ricoeur\u2019s distinction between idem-identity (numerical sameness over time) and ipse-identity (self-constancy as a form of promise-keeping) is partly a secularised development of Kierkegaard\u2019s analysis of the self as a relation that relates itself to itself.' },
        { philosopher: 'Ernest Becker', text: 'Becker\u2019s The Denial of Death (1973) is the most consequential secular appropriation of The Sickness Unto Death. Becker argues that despair \u2014 in Kierkegaard\u2019s sense \u2014 is the universal human condition produced by the knowledge of mortality and the impossibility of accepting it. The flight from despair takes the form of the \u201cimmortality projects\u201d through which human beings deny their finitude. Becker\u2019s secular terror management theory is Kierkegaard\u2019s diagnosis of despair translated into evolutionary psychology.' },
        { philosopher: 'Charles Taylor', text: 'Taylor\u2019s The Ethics of Authenticity (1991) and Sources of the Self (1989) draw heavily on The Sickness Unto Death\u2019s analysis of the self as a structure of commitments and its critique of the trivialisation of selfhood in modern culture. Taylor\u2019s account of the \u201cmalaises of modernity\u201d \u2014 the loss of meaning, the self-centredness, the loss of horizon \u2014 is a contemporary development of Kierkegaard\u2019s analysis of despair.' }
    ],
    modernRelevance: 'The Sickness Unto Death is the most influential philosophical analysis of the self and selfhood in the modern period. The opening definition of the self as a relation that relates itself to itself has been taken up by Sartre (the for-itself as self-reflexive consciousness), Heidegger (Dasein as the being for whom its own being is an issue), Ricoeur (narrative identity), and Taylor (the self as constituted by commitments). The typology of despair has influenced clinical psychology (existential psychotherapy), literary criticism (the analysis of character), and theology (Barth, Tillich, Bultmann). The formula for faith \u2014 \u201cresting transparently in the power that established one\u201d \u2014 has been the most discussed formulation of the religious life in Protestant theology since Barth.',
    context: 'Published 30 July 1849 by C.A. Reitzel in Copenhagen under the pseudonym Anti-Climacus, with Kierkegaard named as editor. The pseudonym is significant: Kierkegaard considered Anti-Climacus\u2019s Christianity too demanding for his own spiritual state; he was not the ideal Christian he described, merely the editor of the ideal\u2019s formulation. Standard English translation by Howard and Edna Hong (Princeton, 1980).',
    relatedWorks: ['concluding-unscientific-postscript', 'concept-of-anxiety', 'philosophical-fragments', 'works-of-love']
},

{
    id: 'works-of-love',
    title: 'Works of Love',
    greekTitle: 'Kjerlighedens Gjerninger',
    philosopher: 'kierkegaard',
    category: 'ethics',
    categoryLabel: 'Ethics & Philosophy of Religion',
    date: '1847 AD',
    dateSort: 1847,
    emoji: '\u2665\uFE0F',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 130000,
    shortDesc: 'Kierkegaard\u2019s most sustained ethical work \u2014 a systematic analysis of Christian love (agape) as the unconditional duty to love the neighbour, distinguished sharply from erotic love and friendship (which are preferential and self-interested) and grounded in God\u2019s command rather than natural inclination.',
    summary: 'Works of Love: Some Christian Reflections in the Form of Discourses (Kjerlighedens Gjerninger: Nogle christelige Overveielser i Taleform), published 29 September 1847 under his own name by C.A. Reitzel in Copenhagen, is Kierkegaard\u2019s most sustained and most systematic ethical work. It is one of the few works he published directly under his own name, signalling that it represents his own explicit position rather than a pseudonymous exploration.\n\nThe central distinction: erotic love (Elskov) and friendship (Venskab) are forms of preferential love \u2014 one loves the beloved because of specific qualities, because of attraction, because of shared history. This preferential love, however passionate and genuine, is ultimately a form of self-love: I love in the other what pleases me, what reflects my own values, what satisfies my desires. Christian love \u2014 neighbour-love (N\u00e6stekj\u00e6rlighed) \u2014 is non-preferential: it is owed to every human being as such, regardless of their qualities, regardless of whether they attract or repel, regardless of what one can gain from them.\n\nThe neighbour is whoever is present: \u201cthe neighbour is the first person you see.\u201d There is no hierarchy of neighbours; there is no calculation of merit; there is no expectation of return. This is the structure of agape, the Greek word for divine and unconditional love, as opposed to eros and philia. The duty to love the neighbour is grounded not in the neighbour\u2019s qualities but in God\u2019s command and in the image of God (Guds Billede) that every human being bears.\n\nThe work argues that genuine neighbour-love is actually the deepest form of erotic and friendship love: when one loves the beloved or the friend \u201cas the neighbour,\u201d one loves them unconditionally, free from the conditions that would otherwise make the relationship contingent on qualities that can change. The transformation of preferential love into neighbour-love through the middle term of God is the deepest consummation of the relationship.',
    themes: ['neighbour-love vs erotic love and friendship', 'the distinction between eros and agape', 'the duty to love unconditionally', 'the image of God in every human being', 'God as the middle term in all genuine love', 'the works of love', 'self-love and other-love', 'the Christian concept of the neighbour'],
    keyCharacters: [],
    concepts: [
        'Neighbour-love (N\u00e6stekj\u00e6rlighed) \u2014 unconditional love owed to every human being as such; not based on qualities, attractiveness, or merit; the specifically Christian form of love',
        'The neighbour as whoever is nearest \u2014 the neighbour is not a specific category of person but whoever happens to be present; there is no hierarchy of neighbours',
        'God as the middle term \u2014 genuine love always has God as its middle term; loving the beloved \u201cas the neighbour\u201d means loving them through and in God, unconditionally',
        'The transformation of erotic love \u2014 when preferential love is transformed into neighbour-love, it becomes more genuine, not less; the conditions of attraction and merit are removed',
        'Works of love \u2014 love is not merely a feeling but a practice; the works are the concrete expressions of love in daily life: building up, believing all things, hoping all things, bearing all things'
    ],
    structure: 'Preface\n\nFirst Series (eight deliberations on the command to love)\n\u2014 Love\u2019s Hidden Life and Its Recognisability by Its Fruits\n\u2014 You Shall Love (the command)\n\u2014 You Shall Love the Neighbour\n\u2014 You Shall Love the Neighbour: Love Your Neighbour as Yourself\n\u2014 The Neighbour (who is the neighbour?)\n\u2014 You Shall Love the Neighbour: Love Is a Matter of Conscience\n\nSecond Series (eight more deliberations)\n\u2014 Love Builds Up\n\u2014 Love Believes All Things\n\u2014 Love Hopes All Things\n\u2014 Love Seeks Not Its Own\n\u2014 The Work of Love in Recollecting One Who Is Dead\n\u2014 The Work of Love in Praising Love',
    quote: 'The object of both erotic love and friendship is the I \u2014 but the neighbour is your other-I, that which in the deepest sense is the equality of humanity before God. But equality before God has nothing to do with all this earthly dissimilarity.',
    additionalQuotes: [
        { text: 'To love another person is to help that person to love God.', citation: 'Works of Love, Second Series, \u201cOur Duty to Love the People We See\u201d' },
        { text: 'Love is the fulfilling of the law, says the apostle \u2014 but that also means it is the source and origin of all that is genuine in the law.', citation: 'Works of Love, First Series, Deliberation III (paraphrased)' }
    ],
    commentary: [
        { philosopher: 'Gene Outka', text: 'Outka\u2019s Agape: An Ethical Analysis (1972) is the most comprehensive philosophical analysis of the concept of neighbour-love and uses Works of Love as its primary text. Outka identifies equal regard as the core of agape: the commitment to treat every person as having equal worth regardless of their qualities. He argues that Kierkegaard\u2019s analysis is the most philosophically precise account of this concept in the Christian tradition.' },
        { philosopher: 'M. Jamie Ferreira', text: 'Ferreira\u2019s Love\u2019s Grateful Striving (2001) argues against the standard reading of Works of Love as advocating an austere, duty-bound love that excludes warmth and spontaneity. Kierkegaard\u2019s neighbour-love, Ferreira argues, is not the negation of erotic and friendship love but their deepening and transformation: when love is genuinely unconditional, the beloved or friend is loved more fully, not less.' }
    ],
    modernRelevance: 'Works of Love is the primary philosophical text for discussions of agape, unconditional love, and the ethics of care. Its distinction between preferential and non-preferential love has influenced theological ethics (Nygren\u2019s Agape and Eros), feminist care ethics (Noddings\u2019s distinction between natural and ethical caring), and political philosophy (discussions of impartiality and partiality in ethics). The claim that genuine love requires God as its middle term is the most sustained philosophical argument for the dependence of ethics on religion.',
    context: 'Published 29 September 1847 by C.A. Reitzel in Copenhagen under Kierkegaard\u2019s own name. One of the few works he did not publish pseudonymously. Written during the period of his most intense religious authorship, following the Either/Or and Stages period. Standard English translation by Howard and Edna Hong (Princeton, 1995).',
    relatedWorks: ['sickness-unto-death', 'concluding-unscientific-postscript', 'fear-and-trembling', 'attack-upon-christendom']
},

{
    id: 'attack-upon-christendom',
    title: 'Attack upon Christendom',
    greekTitle: '\u00d8ieblikket (The Moment)',
    philosopher: 'kierkegaard',
    category: 'practical',
    categoryLabel: 'Religious Polemic',
    date: '1854\u201355 AD',
    dateSort: 1854,
    emoji: '\u26A1',
    cardSize: 'normal',
    readingDifficulty: 'Beginner',
    estimatedWordCount: 80000,
    shortDesc: 'Kierkegaard\u2019s final explosion \u2014 the nine numbers of the polemical pamphlet \u201cThe Moment\u201d (and related articles) in which he attacked the Danish State Church as the greatest possible deception, arguing that official Christianity is the enemy of genuine Christianity and that the clergy are paid liars.',
    summary: 'The Attack upon Christendom consists of the articles and pamphlets with which Kierkegaard concluded his literary career. The attack began with an article in the newspaper Faedreland in December 1854, triggered by the eulogy Bishop Hans Lassen Martensen delivered at the funeral of Bishop Jakob Peter Mynster, praising Mynster as a \u201cwitness to the truth.\u201d For Kierkegaard, this was intolerable: Mynster was the representative of official Danish Christianity, a man who lived comfortably, enjoyed wealth and status, and preached a mild bourgeois Christianity that had nothing to do with the New Testament\u2019s demand for suffering, self-denial, and absolute commitment.\n\nBetween May and September 1855, Kierkegaard published nine numbers of the polemical pamphlet \u201cThe Moment\u201d (Oieblikket) at his own expense. He died on 11 November 1855, six weeks after the last number appeared and while the tenth was in preparation. The Attack is his most direct, most violent, and most readable work \u2014 the voice of someone who has spent his entire literary career working up to a confrontation he knew would destroy him.\n\nThe central argument: official Christendom is the precise opposite of genuine Christianity. The New Testament demands poverty, suffering, renunciation of the world, and the willingness to be persecuted. Official Christianity offers social respectability, professional advancement, and a mild ethical code. The clergy are paid by the state to proclaim a Christianity that the state\u2019s citizens will find comfortable \u2014 which means they are paid to suppress genuine Christianity. The most honest thing the established church could do would be to stop calling itself Christian.\n\nKierkegaard does not argue for a different theology but for the honesty to admit the gap between what is officially proclaimed and what the New Testament actually demands. If the clergy admitted they were not witnesses to the truth but merely servants of social order, he could respect them. What he cannot tolerate is the lie: the pretence that comfortable bourgeois Christianity is genuine New Testament Christianity.',
    themes: ['the attack on established Christianity', 'official Christianity vs New Testament Christianity', 'the clergy as paid liars', 'Bishop Martensen and Bishop Mynster', 'witness to the truth', 'the demand of the New Testament', 'Kierkegaard\u2019s death as confirmation', 'the final explosion', 'polemic as a form of truth-telling'],
    keyCharacters: [
        { name: 'Bishop Jakob Peter Mynster', role: 'The late Bishop of Copenhagen whose eulogy triggered the attack; Kierkegaard\u2019s father\u2019s pastor and a family friend; the representative of the established Christianity Kierkegaard attacks' },
        { name: 'Bishop Hans Lassen Martensen', role: 'Mynster\u2019s successor; his eulogy praising Mynster as a \u201cwitness to the truth\u201d triggered Kierkegaard\u2019s public attack; represented the comfortable theology of official Christendom' }
    ],
    concepts: [
        'Christendom vs Christianity \u2014 Christendom is the cultural and institutional form of Christianity in a nominally Christian society; genuine Christianity is the New Testament\u2019s radical demand for self-denial and suffering',
        'The witness to the truth \u2014 Kierkegaard\u2019s standard: a genuine Christian witness is one who suffers for the truth, not one who profits from it; the established clergy are the precise opposite',
        'Official Christianity as the greatest deception \u2014 the established church is more dangerous to genuine Christianity than outright persecution, because it gives the appearance of Christianity while suppressing its reality',
        'The New Testament demand \u2014 the unconditional demand of the New Testament for renunciation, poverty, suffering, and the willingness to be hated; incompatible with bourgeois respectability',
        'The moment (Oieblikket) \u2014 the title of the pamphlet series; the qualitative instant in which the eternal breaks into time; also the title of Kierkegaard\u2019s last public utterance'
    ],
    structure: '\u201cWas Bishop Mynster a Witness to the Truth?\u201d (Faedreland article, December 1854)\nThree further articles in Faedreland (February\u2013March 1855)\nNine numbers of \u201cThe Moment\u201d (Oieblikket), May\u2013September 1855\nNumber 10 of \u201cThe Moment\u201d (unfinished at death; published posthumously)',
    quote: 'The matter is quite simple. The New Testament is very easy to understand. But we human beings are really not very keen on understanding it, we are afraid that if we understood it, it would oblige us too much. Therefore we pretend that it is difficult to understand.',
    additionalQuotes: [
        { text: 'Official Christianity is, from the Christian point of view, a criminal offense \u2014 it is presenting a false version of Christianity as genuine, which is an offense against God and against those who are genuinely seeking.', citation: 'The Moment, No. 1 (paraphrased)' },
        { text: 'What I want is honesty. If that is what the human race, if what this generation wants, then let us be honest and openly, frankly, straightforwardly, directly rebel against Christianity.', citation: 'The Moment, No. 10' }
    ],
    commentary: [
        { philosopher: 'Karl Barth', text: 'Barth\u2019s neo-orthodox theology drew heavily on the Attack upon Christendom as the paradigm of genuine prophetic witness against the accommodation of Christianity to bourgeois culture. Barth\u2019s insistence on the \u201cinfinite qualitative difference\u201d between God and human culture \u2014 the impossibility of identifying any human institution, including the church, with the Kingdom of God \u2014 is the theological development of Kierkegaard\u2019s attack on established Christendom.' },
        { philosopher: 'Dietrich Bonhoeffer', text: 'Bonhoeffer\u2019s concept of \u201ccheap grace\u201d in The Cost of Discipleship (1937) \u2014 the grace that is proclaimed without the demand for repentance, discipleship, and suffering \u2014 is a Lutheran development of Kierkegaard\u2019s attack on official Christianity. Bonhoeffer\u2019s willingness to accept imprisonment and death for his resistance to Nazism was partly grounded in his reading of Kierkegaard on the witness to the truth.' }
    ],
    modernRelevance: 'The Attack upon Christendom is the founding text of the tradition of Christian social criticism that runs through Barth, Bonhoeffer, Tillich, and liberation theology. Its central charge \u2014 that institutional Christianity has become the enemy of the genuine Christianity it professes \u2014 resonates with every generation\u2019s experience of the gap between ecclesiastical institution and prophetic demand. The concept of \u201ccheap grace\u201d (Bonhoeffer\u2019s development) has become one of the most widely used concepts in Christian ethics. The Attack is also the model for a genre of philosophical polemic: the final, concentrated explosion of a lifetime\u2019s argument.',
    context: 'The attack began with an article in Faedreland in December 1854. Nine numbers of The Moment (Oieblikket) appeared between May and September 1855. Kierkegaard collapsed on the street on 2 October 1855 and died in Frederiks Hospital on 11 November 1855, aged forty-two. He refused to receive communion from a pastor of the established church on his deathbed. The standard English translation is by Walter Lowrie (Princeton, 1944; reprinted 1968).',
    relatedWorks: ['works-of-love', 'sickness-unto-death', 'concluding-unscientific-postscript', 'fear-and-trembling']
}

);
