/* DATA PART 20d — Kierkegaard: Concluding Unscientific Postscript + Stages on Life's Way */
window.WORKS.push(

{
    id: 'concluding-unscientific-postscript',
    title: 'Concluding Unscientific Postscript to Philosophical Fragments',
    greekTitle: 'Afsluttende uvidenskabelig Efterskrift til de Philosophiske Smuler',
    philosopher: 'kierkegaard',
    category: 'metaphysics',
    categoryLabel: 'Epistemology & Philosophy of Religion',
    date: '1846 AD',
    dateSort: 1846,
    emoji: '\uD83D\uDCCC',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 300000,
    shortDesc: 'The pseudonymous masterpiece of existentialist philosophy \u2014 Kierkegaard\u2019s most extensive philosophical work, developing the concept of subjective truth (\u201ctruth is subjectivity\u201d), the three stages of existence, the concept of indirect communication, and the critique of Hegelian speculative philosophy as the central obstacle to genuine Christian existence.',
    summary: 'Concluding Unscientific Postscript to Philosophical Fragments: A Mimical-Pathetical-Dialectical Compilation, an Existential Contribution (Afsluttende uvidenskabelig Efterskrift til de Philosophiske Smuler), published 28 February 1846 under the pseudonym Johannes Climacus (with Kierkegaard named on the title page as editor) by C.A. Reitzel in Copenhagen, is the longest, most ambitious, and most philosophically comprehensive of Kierkegaard\u2019s works. It was conceived as a mere appendix to Philosophical Fragments \u2014 hence the title \u2014 but grew to seven times its length.\n\nThe work\u2019s central question is the same as Philosophical Fragments\u2019 but pursued at vastly greater depth: how can I, Johannes Climacus, a thinker in the nineteenth century, acquire an eternal happiness that is based on a contingent historical fact \u2014 namely, the Incarnation? This is Lessing\u2019s problem, stated with maximum precision: how can the \u201cugly broad ditch\u201d between historical contingency and eternal significance be crossed?\n\nThe answer involves the concept of subjective truth \u2014 the most discussed and most misunderstood concept in Kierkegaard\u2019s philosophy. The formula \u201ctruth is subjectivity\u201d does not mean that truth is whatever the individual believes. It means that certain kinds of truth \u2014 specifically, those that bear on existence, commitment, and the meaning of one\u2019s life \u2014 can only be appropriated through a kind of inner transformation, a passionate personal commitment. The opposite \u2014 objective truth \u2014 is the truth of science, mathematics, and history: indifferent to the knower, communicable to anyone, indifferent to whether it is personally appropriated. Subjective truth is the opposite: it demands infinite passion, personal risk, and the willingness to act on uncertainty.\n\nThis leads to the celebrated formula: \u201cSubjectivity is truth; subjectivity is reality.\u201d Even more provocatively: \u201cAn objective uncertainty held fast in an appropriation-process of the most passionate inwardness is the truth, the highest truth attainable for an existing individual.\u201d Faith is not the possession of certainty but the passionate holding of objective uncertainty.\n\nThe Postscript also develops the three stages of existence more fully than any other work: the aesthetic (immediacy, finite ends, the avoidance of boredom), the ethical (the universal, self-choice, duty), and the religious (the absolute relation to the absolute, faith, infinite passion for the eternal). These are not stages through which one automatically progresses but modes of existence between which the individual must choose \u2014 and the transition from each to the next requires a qualitative leap that reason cannot compel.',
    themes: ['subjectivity as truth', 'objective vs subjective thinking', 'the three stages of existence', 'the leap of faith', 'indirect communication', 'the critique of Hegel', 'Lessing\u2019s ditch', 'existential pathos', 'the comic and the tragic', 'Johannes Climacus', 'becoming a Christian in Christendom'],
    keyCharacters: [
        { name: 'Johannes Climacus', role: 'The pseudonymous author; the most developed of Kierkegaard\u2019s pseudonyms; a thinker who examines the philosophical conditions for becoming a Christian without committing to Christianity' }
    ],
    concepts: [
        'Subjectivity is truth \u2014 certain truths (those bearing on existence and commitment) can only be appropriated through passionate personal engagement; the formula does not mean truth is arbitrary',
        'Objective uncertainty held fast in passionate inwardness \u2014 the definition of faith: not the possession of certainty but the passionate commitment to objective uncertainty',
        'The three stages of existence \u2014 the aesthetic (immediacy), the ethical (the universal), and the religious (the absolute relation to the absolute); not a developmental progression but modes between which one must choose',
        'The qualitative leap \u2014 the transition from one stage to another cannot be accomplished by reason or gradual development; it requires a leap that reason cannot compel',
        'Indirect communication \u2014 existential truths cannot be directly communicated because appropriation requires the recipient\u2019s own passionate engagement; they must be communicated through ambiguity, irony, and pseudonymity',
        'The critique of Hegel \u2014 Hegelian speculative philosophy dissolves the existing individual into the system; the Postscript\u2019s most sustained target is the claim to comprehend existence from the standpoint of the Absolute',
        'Becoming a Christian \u2014 the Postscript\u2019s practical question: how does one become a Christian when one already lives in a nominally Christian society? The answer: the task is infinitely more difficult, not easier, in Christendom'
    ],
    structure: 'Introduction: The objective problem concerning the truth of Christianity\n\nPart One: The Objective Problem Concerning the Truth of Christianity\n\u2014 Section 1: The historical point of view\n\u2014 Section 2: The speculative point of view\n\nPart Two: The Subjective Problem\n\u2014 Section 1: Something About Lessing\n\u2014 Section 2: The Subjective Issue or How Subjectivity Must be Constituted in Order that the Problem May Appear to It\n  \u2014 Chapter 1: Becoming Subjective\n  \u2014 Chapter 2: Subjective Truth, Inwardness; Truth is Subjectivity\n  \u2014 Chapter 3: Actual Subjectivity, Ethical Subjectivity; the Subjective Thinker\n  \u2014 Chapter 4: The Problem of the Stages on Existence\u2019s Way\n\u2014 Section 3: The Issue in Fragments: How Can an Eternal Happiness Be Built upon Historical Knowledge?\n\nConclusion and First and Last Declaration (Kierkegaard reveals himself as author of the pseudonymous works)',
    quote: 'The most tremendous thing which has been granted to man is the choice, freedom. And if you desire to save it and keep it, there is only one way: in the very same second unconditionally and in complete resignation to give it back to God, and yourself with it.',
    additionalQuotes: [
        { text: 'Subjectivity is truth. Subjectivity is reality.', citation: 'Concluding Unscientific Postscript, Part Two, Section 2, Chapter 2' },
        { text: 'If I am capable of grasping God objectively, I do not believe, but precisely because I cannot do this I must believe.', citation: 'Concluding Unscientific Postscript, Part Two, Section 2, Chapter 2' },
        { text: 'Christianity did not come into the world as a showy diversion for bored spirits, but as the absolute decision.', citation: 'Concluding Unscientific Postscript, Part Two, Section 3' }
    ],
    commentary: [
        { philosopher: 'Karl Barth', text: 'Barth\u2019s neo-orthodox theology, beginning with the second edition of his Commentary on Romans (1922), is saturated with Kierkegaardian themes drawn from the Postscript: the \u201cinfinite qualitative difference\u201d between God and man; the impossibility of approaching God through human reason or culture; the absolute paradox of the Incarnation; the necessity of faith as the only mode of access to divine truth. Barth acknowledged Kierkegaard as the \u201cfierce \u2018jaundiced\u2019 prophet\u201d who had demolished liberal theology\u2019s complacency.' },
        { philosopher: 'Martin Heidegger', text: 'Heidegger\u2019s Being and Time (1927) is the primary philosophical development of the existential categories introduced in the Postscript. The analysis of existence as always already \u201cmine,\u201d the concept of Dasein as the being for whom its own being is an issue, the distinction between authentic and inauthentic existence, and the analysis of the they-self (das Man) as the flight from the demands of ownmost existence are all developments of Kierkegaard\u2019s analysis of the aesthetic and ethical stages.' },
        { philosopher: 'Alvin Plantinga', text: 'Plantinga\u2019s reformed epistemology \u2014 the argument that belief in God can be \u201cproperly basic,\u201d not derived from evidence or argument \u2014 is partly a development of the Postscript\u2019s analysis of faith as the passionate holding of objective uncertainty. The claim that religious belief does not require rational justification in order to be epistemically warranted is the epistemological dimension of Kierkegaard\u2019s concept of subjective truth.' }
    ],
    modernRelevance: 'The Concluding Unscientific Postscript is the primary text of existentialism as a philosophical movement. Its analysis of subjective truth, authentic existence, and the three stages of existence is the foundation of Heidegger\u2019s fundamental ontology, Sartre\u2019s analysis of bad faith and authentic choice, Jaspers\u2019s boundary situations, and Tillich\u2019s theology of ultimate concern. The concept of indirect communication \u2014 the claim that existential truths cannot be directly taught but must be appropriated through personal engagement \u2014 has influenced pedagogy, rhetoric, and philosophy of language. The critique of Hegel\u2019s speculative philosophy as the great obstacle to genuine existence remains the foundational text for all existentialist critiques of systematic philosophy.',
    context: 'Published 28 February 1846 by C.A. Reitzel in Copenhagen. The First and Last Declaration at the end of the work \u2014 in which Kierkegaard reveals himself as the author of all the pseudonymous works \u2014 was Kierkegaard\u2019s intention to retire from authorship. The Corsair affair (the satirical magazine\u2019s months-long attack on Kierkegaard following his provocation of its editor) changed his mind. Standard English translation by Howard and Edna Hong (Princeton, 1992).',
    relatedWorks: ['philosophical-fragments', 'either-or', 'sickness-unto-death', 'stages-lifes-way']
},

{
    id: 'stages-lifes-way',
    title: 'Stages on Life\u2019s Way',
    greekTitle: 'Stadier paa Livets Vei',
    philosopher: 'kierkegaard',
    category: 'aesthetics',
    categoryLabel: 'Philosophy & Literature',
    date: '1845 AD',
    dateSort: 1845,
    emoji: '\uD83D\uDEE3\uFE0F',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 180000,
    shortDesc: 'The most literarily complex of Kierkegaard\u2019s works \u2014 three elaborately framed explorations of the aesthetic, ethical, and religious stages through a banquet discussion of erotic love, Judge William\u2019s defence of marriage, and \u201cGuilty/Not Guilty,\u201d the most autobiographical of the pseudonymous writings.',
    summary: 'Stages on Life\u2019s Way (Stadier paa Livets Vei), published 30 April 1845 under the editorship of the pseudonym Hilarius Bookbinder by C.A. Reitzel in Copenhagen, is the most architecturally elaborate and most literarily complex of Kierkegaard\u2019s works. It is divided into three parts, each representing one of the three stages of existence \u2014 aesthetic, ethical, and religious \u2014 through a different literary form and pseudonymous voice.\n\nPart One, \u201cIn Vino Veritas: A Recollection\u201d (in wine there is truth), is framed as an account of a banquet gathered by William Afham in a forest at night. Five speakers give speeches on woman and erotic love: a Young Man (in the manner of Plato\u2019s Symposium), Constantin Constantius (from Repetition), Victor Eremita (from Either/Or), the Ladies\u2019 Tailor, and Johannes the Seducer (from Either/Or\u2019s Seducer\u2019s Diary). The banquet ends at dawn; the guests scatter as Judge William and his wife appear on their morning walk.\n\nPart Two, \u201cVariations on the Theme of Marriage: Moral Reflections on Marriage Against the Sophistical Objections of Theophrastus\u201d, is Judge William\u2019s long defence of conjugal love against the aesthete\u2019s objections. The Judge argues that conjugal love is not the diminishment of erotic passion but its highest realisation: the daily renewal of commitment transforms first love into something richer and more enduring.\n\nPart Three, \u201cGuilty?/Not Guilty? A Story of Suffering,\u201d is the most personal and most disturbing section. Written under the pseudonym Frater Taciturnus (\u201cthe Silent Brother\u201d), it consists of the diary of Quidam (\u201cSomewhat\u201d) interleaved with Frater Taciturnus\u2019s reflections. Quidam is in an impossible situation: he loves a young woman but cannot marry her because of some unspecified inner burden (clearly a figure for Kierkegaard\u2019s broken engagement to Regine Olsen and the melancholy he could not share with her). The question \u2014 is Quidam guilty or not guilty? \u2014 is left deliberately unanswered: it points toward the religious stage in which guilt and innocence are finally reckoned.',
    themes: ['the three stages through literary form', 'the banquet and erotic love', 'conjugal love vs erotic passion', 'Guilty/Not Guilty and the broken engagement', 'melancholy and the inability to communicate', 'the religious stage as the resolution of guilt', 'elaborated pseudonymity', 'the Symposium as model'],
    keyCharacters: [
        { name: 'Frater Taciturnus', role: 'The pseudonymous editor of Part Three; his silence and his reflection on Quidam\u2019s situation point toward the religious stage that is beyond the work\u2019s direct presentation' },
        { name: 'Quidam', role: 'The diarist of Part Three; in an impossible relationship; unable to share his inner burden; guilty and not guilty; a figure for Kierkegaard\u2019s own situation with Regine Olsen' }
    ],
    concepts: [
        'The three stages through literary form \u2014 aesthetic (the banquet; erotic love), ethical (the Judge\u2019s defence of marriage), religious (Quidam\u2019s diary; guilt and the absolute)',
        'Conjugal love as the highest form of erotic love \u2014 Judge William\u2019s argument: marriage does not diminish passion but transforms it through repeated free choice into something more enduring',
        'The impossible situation \u2014 Quidam\u2019s predicament: loving someone but being unable to share the inner burden that makes marriage impossible; the ethical demand that cannot be met without the religious resolution',
        'The border between the ethical and the religious \u2014 the work ends at the threshold of the religious stage without crossing it; Quidam\u2019s situation requires more than ethics can provide'
    ],
    structure: 'Editor\u2019s Preface by Hilarius Bookbinder\n\nPart One: In Vino Veritas (A Recollection by William Afham)\n\u2014 Five speeches on woman and love; the banquet\n\nPart Two: Variations on the Theme of Marriage (Judge William\u2019s essay)\n\nPart Three: Guilty?/Not Guilty? (Edited by Frater Taciturnus)\n\u2014 Quidam\u2019s diary (entries at midnight and at 5 AM)\n\u2014 Frater Taciturnus\u2019s \u201cLetter to the Reader\u201d',
    quote: 'It is the duty of the human understanding to understand that there are things which it cannot understand, and what those things are. Human understanding has vulgarly occupied itself with nothing but understanding, but if it would only take the trouble to understand itself at the same time it would simply have to posit the paradox.',
    additionalQuotes: [
        { text: 'In relation to their systems, most systematisers are like a man who builds an enormous castle and lives in a shack next to it; they do not live in their own enormous systematic building.', citation: 'Stages on Life\u2019s Way, Part Three, Frater Taciturnus\u2019s Letter (paraphrased from the Journals)' }
    ],
    commentary: [
        { philosopher: 'Louis Mackey', text: 'Mackey\u2019s Kierkegaard: A Kind of Poet (1971) provides the most sustained literary analysis of Stages on Life\u2019s Way, arguing that its extraordinary architectural complexity \u2014 the nested pseudonyms, the intersecting literary forms, the structural echoes between the three parts \u2014 is not decorative but philosophical: the literary form is the philosophical content, enacting the impossibility of direct communication between the stages.' }
    ],
    modernRelevance: 'Stages on Life\u2019s Way is important primarily as the fullest literary elaboration of the three stages and as the most autobiographically revealing of the pseudonymous works. The \u201cGuilty?/Not Guilty?\u201d section has been read by Kierkegaard\u2019s biographers as the closest he comes to explaining his broken engagement to Regine Olsen. The banquet scene in Part One has been compared to Plato\u2019s Symposium and stands alongside it as one of the great literary performances in philosophical literature.',
    context: 'Published 30 April 1845 by C.A. Reitzel in Copenhagen under the pseudonym Hilarius Bookbinder. Written during the most intensely productive period of Kierkegaard\u2019s authorship, alongside the Postscript. Standard English translation by Howard and Edna Hong (Princeton, 1988).',
    relatedWorks: ['either-or', 'concluding-unscientific-postscript', 'fear-and-trembling', 'repetition']
}

);
