/* DATA PART 20a — Kierkegaard: Either/Or */
window.WORKS.push(
{
    id: 'either-or',
    title: 'Either/Or: A Fragment of Life',
    greekTitle: 'Enten \u2013 Eller. Et Livs-Fragment',
    philosopher: 'kierkegaard',
    category: 'aesthetics',
    categoryLabel: 'Aesthetics & Ethics',
    date: '1843 AD',
    dateSort: 1843,
    emoji: '\uD83C\uDFAD',
    cardSize: 'wide',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 220000,
    shortDesc: 'Kierkegaard\u2019s debut masterpiece \u2014 an elaborate literary performance in two volumes presenting the aesthetic and ethical stages of existence without choosing between them, forcing the reader to make the choice philosophy cannot make for them.',
    summary: 'Either/Or: A Fragment of Life (Enten \u2013 Eller. Et Livs-Fragment), published on 20 February 1843 under the pseudonym Victor Eremita by C.A. Reitzel in Copenhagen, is Kierkegaard\u2019s first major philosophical work and one of the most architecturally complex in the history of philosophy. Kierkegaard was twenty-nine. The work went through two editions in his lifetime and established him immediately as the most original voice in Danish letters.\n\nThe elaborate fictional frame: Victor Eremita (\u201cVictor the Hermit\u201d) claims to have found two bundles of papers in the secret drawer of a writing desk he purchased at auction. Part One contains the papers of \u201cA,\u201d a young aesthete of brilliant but directionless intelligence. Part Two contains the letters and essays of \u201cJudge William,\u201d a magistrate who responds to A with a sustained defence of the ethical life. Victor Eremita professes not to know whether A and the Judge are the same person, different people, or fictional constructions.\n\nPart One (\u201cThe Aesthetic\u201d) is the most diverse and the most celebrated half. It opens with the Diapsalmata \u2014 a collection of aphorisms and fragments, some of the most quoted in the philosophical literature. The centrepiece is \u201cThe Immediate Erotic Stages, or the Musical Erotic\u201d \u2014 a lengthy and brilliant analysis of Mozart\u2019s Don Giovanni as the perfect expression of the immediately erotic, the life of pure sensuous immediacy without reflection. The aesthetic culminates in \u201cThe Seducer\u2019s Diary,\u201d the fictional journal of Johannes the Seducer, a cold and calculating aesthete who orchestrates the seduction of a young woman as a work of art, then abandons her when the conquest is complete. The Seducer\u2019s Diary is the most unsettling portrait of the aesthetic life at its extreme: the reduction of another person to a medium for one\u2019s own self-expression.\n\nPart Two (\u201cThe Ethical\u201d) consists of two long letters from Judge William to A, defending the ethical life against the aesthetic. The Judge\u2019s central argument: the aesthetic life is not genuinely lived because the aesthete never commits \u2014 never chooses himself in his eternal validity. The ethical life begins with the act of self-choice: the recognition that one has a self with obligations, a history, and a future. Marriage is the Judge\u2019s paradigm case: not the romantic passion of the aesthete but the daily renewal of commitment, the transformation of first love into conjugal love through repeated free choice. The work ends without resolution: Victor Eremita does not choose between A and the Judge, and the reader is left with the existential demand \u2014 to choose \u2014 that neither the aesthetic nor the ethical analysis can make on their behalf.',
    themes: ['the aesthetic and ethical stages of existence', 'the aesthete and the ethicist', 'Don Giovanni as the musical erotic', 'the Seducer\u2019s Diary', 'self-choice and commitment', 'marriage as ethical paradigm', 'boredom and the rotation method', 'pseudonymous authorship', 'indirect communication', 'the either/or as existential demand'],
    keyCharacters: [
        { name: 'A (the Aesthete)', role: 'The unnamed author of Part One; brilliant, melancholic, and uncommitted; his life is organised around the avoidance of boredom through aesthetic variation; represented most fully in the Diapsalmata and the Seducer\u2019s Diary' },
        { name: 'Judge William', role: 'The author of Part Two; a magistrate and married man who defends the ethical life against the aesthete; his position represents the second stage of existence: self-choice, commitment, and the transformation of passion into obligation' },
        { name: 'Johannes the Seducer', role: 'The protagonist of the Seducer\u2019s Diary; a cold, calculating aesthete who orchestrates a seduction as a work of art; the most extreme expression of the aesthetic life as the reduction of others to instruments of one\u2019s own self-cultivation' }
    ],
    concepts: [
        'The aesthetic stage of existence \u2014 the life organised around the immediate satisfaction of desire, the cultivation of mood, and the avoidance of boredom; it lacks the continuity and commitment of genuine selfhood',
        'The ethical stage of existence \u2014 the life organised around duty, commitment, and self-choice; the recognition that one has a self with obligations and a history',
        'The Diapsalmata \u2014 the aphoristic opening of Part One: fragments of mood, wit, and despair expressing the aesthetic consciousness at its most articulate and most directionless',
        'Don Giovanni as the musical erotic \u2014 Mozart\u2019s opera as the perfect artistic expression of the immediately erotic; music as the art form of immediacy; Don Giovanni as the paradigm of the aesthetic man',
        'The rotation method (Vexiermetode) \u2014 the aesthete\u2019s strategy for avoiding boredom: vary the stimulus, not the situation; cultivate the accidental; transform every experience into material for reflection',
        'The Seducer\u2019s Diary \u2014 the coldly self-aware journal of Johannes, who seduces Cordelia as a work of art and abandons her when the aesthetic interest is exhausted; the self-refutation of the aesthetic life',
        'Self-choice \u2014 Judge William\u2019s central concept: the ethical life begins when one chooses oneself \u2014 not a different self but one\u2019s actual self, with its history, obligations, and finitude, in its eternal validity',
        'Either/Or as existential demand \u2014 the title is not a logical disjunction but an existential one: the demand to choose between ways of life that cannot be rationally adjudicated from outside; the choice itself constitutes the chooser'
    ],
    structure: 'Editorial Preface by Victor Eremita\n\nPart One: A\u2019s Papers\n\u2014 Diapsalmata (aphorisms)\n\u2014 The Immediate Erotic Stages, or The Musical Erotic (on Mozart\u2019s Don Giovanni)\n\u2014 The Ancient Tragical Motif as Reflected in the Modern\n\u2014 Shadowgraphs (on feminine unhappiness)\n\u2014 The Unhappiest One\n\u2014 The First Love (a comedy review)\n\u2014 The Rotation of Crops (the rotation method; on boredom)\n\u2014 The Seducer\u2019s Diary\n\nPart Two: Judge William\u2019s Letters\n\u2014 Letter I: The Aesthetic Validity of Marriage\n\u2014 Letter II: The Balance Between the Aesthetic and the Ethical in the Development of Personality\n\u2014 Appendix: Ultimatum (a sermon from Jutland)',
    quote: 'Marry, and you will regret it; don\u2019t marry, you will also regret it; marry or don\u2019t marry, you will regret it either way. Laugh at the world\u2019s foolishness, you will regret it; weep over it, you will regret that too; laugh at the world\u2019s foolishness or weep over it, you will regret both.',
    additionalQuotes: [
        { text: 'What is a poet? An unhappy man who hides deep anguish in his heart, but whose lips are so formed that when the sigh and cry pass through them, it sounds like lovely music.', citation: 'Either/Or, Part I, Diapsalmata' },
        { text: 'Boredom is the root of all evil. The history of this can be traced from the very beginning of the world. The gods were bored, and so they created human beings.', citation: 'Either/Or, Part I, \u201cThe Rotation of Crops\u201d' },
        { text: 'People hardly ever make use of the freedom they have, for example freedom of thought; instead they demand freedom of speech as compensation.', citation: 'Either/Or, Part I, Diapsalmata' },
        { text: 'My depression is the most faithful mistress I have known \u2014 no wonder, then, that I return the love.', citation: 'Either/Or, Part I, Diapsalmata' }
    ],
    commentary: [
        { philosopher: 'Jean-Paul Sartre', text: 'Sartre\u2019s Being and Nothingness (1943) develops the existential structure of Either/Or\u2019s analysis of choice into a full ontology of freedom. Sartre\u2019s doctrine of radical freedom \u2014 that existence precedes essence, that we are condemned to choose, that bad faith consists in denying one\u2019s freedom \u2014 is the secularised development of Kierkegaard\u2019s either/or. But Sartre removes the theological dimension: where Kierkegaard\u2019s either/or is ultimately oriented toward the religious stage, Sartre\u2019s either/or opens onto a godless universe in which freedom is absolute and groundless.' },
        { philosopher: 'Theodor Adorno', text: 'Adorno\u2019s Kierkegaard: Construction of the Aesthetic (1933; English 1989) is the first major philosophical study of Either/Or and remains one of the most challenging. Adorno argues that the aesthetic stage, far from being straightforwardly criticised by the ethical, is also a dialectical critique of bourgeois society: the aesthete\u2019s refusal of commitment is the refusal of a society that reduces commitment to contractual obligation. The Seducer\u2019s Diary is not simply the portrait of a monster but a negative theology of freedom.' },
        { philosopher: 'Alasdair MacIntyre', text: 'MacIntyre\u2019s After Virtue (1981) uses Either/Or as the paradigm case of the emotivist culture he diagnoses in modern ethics: the inability to resolve moral disagreements rationally, which MacIntyre traces to the loss of the Aristotelian tradition, is exactly what Kierkegaard\u2019s either/or enacts. But MacIntyre argues that Kierkegaard draws the wrong conclusion: the inability to rationally adjudicate between aesthetic and ethical life is a symptom of cultural pathology, not an eternal structure of human existence.' },
        { philosopher: 'George Pattison', text: 'Pattison\u2019s work on Kierkegaard\u2019s aesthetics argues that the analysis of Don Giovanni in Part One is the most original philosophy of music produced before Nietzsche and Wagner: the claim that music is the art form of immediacy, that it alone can give perfect expression to the erotic as pure sensuous force, anticipates the Wagnerian synthesis of music and drama.' }
    ],
    modernRelevance: 'Either/Or is the founding text of existentialism and one of the most consequential works of philosophical literature in the modern period. Its portrait of the aesthete \u2014 brilliant, uncommitted, bored, self-aware \u2014 is the archetype of the modern intellectual who substitutes irony for engagement. Its analysis of the rotation method anticipates the cultural logic of consumer capitalism: the perpetual stimulation of new desires to replace old ones, the commodification of experience. The Seducer\u2019s Diary has become the standard philosophical reference for discussions of manipulation, consent, and the objectification of persons. The either/or structure \u2014 the demand for a choice that cannot be rationally adjudicated from outside \u2014 is the foundation of existentialist ethics and of all subsequent discussions of commitment, authenticity, and bad faith.',
    context: 'Published 20 February 1843 by C.A. Reitzel in Copenhagen under the pseudonym Victor Eremita. Kierkegaard had recently broken off his engagement to Regine Olsen \u2014 the most significant event of his personal life and a constant presence in his writing. Either/Or is partly a meditation on the decision to break the engagement and partly an exploration of the aesthetic life he renounced in doing so. The work was an immediate sensation in Copenhagen. Kierkegaard published it at his own expense and supervised every detail of its production. The dedication \u2014 to the memory of his father, Michael Pedersen Kierkegaard \u2014 is the only indication that the author is not Victor Eremita.',
    relatedWorks: ['fear-and-trembling', 'stages-lifes-way', 'concluding-unscientific-postscript', 'sickness-unto-death']
}
);
