/* DATA PART 21b — Marx & Engels: The German Ideology + The Communist Manifesto */
window.WORKS.push(

{
    id: 'german-ideology',
    title: 'The German Ideology',
    greekTitle: 'Die deutsche Ideologie',
    philosopher: 'marx',
    category: 'method',
    categoryLabel: 'Historical Materialism',
    date: '1845\u201346 AD',
    dateSort: 1845,
    emoji: '\uD83C\uDFED',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 200000,
    shortDesc: 'The founding document of historical materialism \u2014 Marx and Engels\u2019s systematic critique of post-Hegelian German philosophy and their first full statement of the materialist conception of history: that consciousness does not determine life, but life determines consciousness.',
    summary: 'The German Ideology (Die deutsche Ideologie), written by Marx and Engels in Brussels between autumn 1845 and mid-1846 but unpublished during their lifetimes (first published in full in 1932), is the foundational text of historical materialism \u2014 the materialist conception of history (materialistische Geschichtsauffassung) that would underpin all of Marx\u2019s subsequent work.\n\nThe work is primarily a polemical critique of the Young Hegelians \u2014 Bruno Bauer, Max Stirner, and others \u2014 who, Marx and Engels argue, remain within the idealist presuppositions of German philosophy despite their apparent radicalism. The Young Hegelians criticise ideas with ideas, replacing one set of religious or philosophical conceptions with another. They do not see that ideas are not autonomous forces but expressions of material social relations.\n\nThe positive content is the first systematic statement of historical materialism. The premises Marx and Engels begin with are not arbitrary or dogmatic but the actual material premises of human existence: that human beings must produce their means of subsistence before they can make history. The mode of production \u2014 the way in which human beings organise their productive activity \u2014 determines the form of social life, the legal and political institutions, and the forms of consciousness that develop within it.\n\nThe famous formulation: \u201cLife is not determined by consciousness, but consciousness by life.\u201d Or in its more elaborate form: \u201cThe production of ideas, of conceptions, of consciousness is at first directly interwoven with the material activity and the material intercourse of men. The ideas, the ideational interchanges of men appear at this point directly as the direct efflux of their material behaviour.\u201d\n\nThe work also contains the famous account of ideology: the dominant ideas of every epoch are the ideas of the ruling class, because the ruling class controls the means of mental production as well as the means of material production. The ruling class presents its particular interests as universal interests, its historically contingent ideas as eternal truths \u2014 this is ideology. The camera obscura image: ideology presents the world inverted, as a camera obscura inverts the image it captures.',
    themes: ['historical materialism', 'the materialist conception of history', 'the critique of the Young Hegelians', 'the mode of production', 'base and superstructure', 'ideology', 'the camera obscura', 'life determines consciousness', 'the division of labour', 'class and class consciousness'],
    keyCharacters: [],
    concepts: [
        'Historical materialism \u2014 the materialist conception of history: the mode of production determines the forms of social life, legal and political institutions, and consciousness',
        'Life determines consciousness \u2014 the fundamental inversion of idealism: it is not ideas that drive history but material social relations; consciousness is the expression of material life',
        'The mode of production \u2014 the way in which human beings organise their productive activity; the decisive factor in determining the structure of society at any given historical moment',
        'Base and superstructure \u2014 the economic base (relations of production) determines the superstructure (legal, political, and ideological forms); changes in the base drive changes in the superstructure',
        'Ideology \u2014 the dominant ideas of every epoch are the ideas of the ruling class; ideology presents particular class interests as universal interests and historically contingent arrangements as natural and eternal',
        'The camera obscura \u2014 ideology inverts reality as a camera obscura inverts the image: the real material relations appear as their own inversion in ideological consciousness',
        'The division of labour \u2014 the progressive specialisation of productive activity that is simultaneously the basis of increased productivity and the source of class divisions, alienation, and the separation of intellectual from manual work'
    ],
    structure: 'Volume I: Critique of Modern German Philosophy According to Its Representatives Feuerbach, B. Bauer and Stirner\n\u2014 Part 1: Feuerbach: Opposition of the Materialist and Idealist Outlooks\n  \u2014 The Materialist Conception of History\n  \u2014 History: Fundamental Conditions\n  \u2014 Private Property and Communism\n\u2014 Part 2: Critique of Bruno Bauer\u2014 Part 3: Critique of Max Stirner (the longest section; the \u201cSaint Max\u201d critique)\n\nVolume II: Critique of German Socialism According to Its Various Prophets\n\u2014 The True Socialists',
    quote: 'The ideas of the ruling class are in every epoch the ruling ideas: i.e. the class which is the ruling material force of society is at the same time its ruling intellectual force.',
    additionalQuotes: [
        { text: 'Life is not determined by consciousness, but consciousness by life.', citation: 'The German Ideology, Part I' },
        { text: 'In communist society, where nobody has one exclusive sphere of activity but each can become accomplished in any branch he wishes, society regulates the general production and thus makes it possible for me to do one thing today and another tomorrow, to hunt in the morning, fish in the afternoon, rear cattle in the evening, criticise after dinner, just as I have a mind, without ever becoming hunter, fisherman, shepherd or critic.', citation: 'The German Ideology, Part I (the famous passage on communist society)' },
        { text: 'The production of ideas, of conceptions, of consciousness, is at first directly interwoven with the material activity and the material intercourse of men.', citation: 'The German Ideology, Part I' }
    ],
    commentary: [
        { philosopher: 'G.A. Cohen', text: 'Cohen\u2019s Karl Marx\u2019s Theory of History: A Defence (1978) is the most rigorous analytical reconstruction of the materialist conception of history as first stated in The German Ideology. Cohen argues that the base-superstructure model can be reconstructed as a coherent functional explanation: the superstructure exists and has the character it has because it sustains the base; the relations of production are what they are because they develop the productive forces. This \u201ctechnological determinism\u201d reading was enormously influential in the analytical Marxism of the 1980s.' },
        { philosopher: 'Raymond Williams', text: 'Williams\u2019s Marxism and Literature (1977) provides the most influential cultural-materialist reading of the base-superstructure model from The German Ideology. Williams argues that the model, mechanically applied, reduces culture to mere reflection of economic base; his alternative \u2014 the concepts of hegemony (from Gramsci), residual/dominant/emergent culture, and structures of feeling \u2014 attempts to preserve the insight that cultural production is materially conditioned without reducing it to passive expression.' }
    ],
    modernRelevance: 'The German Ideology is the founding text of the sociology of knowledge: the systematic study of the social conditions of knowledge production. The concept of ideology \u2014 the ruling class\u2019s ideas as the ruling ideas \u2014 has been developed by Lukacs (reification), Gramsci (hegemony), Althusser (ideological state apparatuses), Foucault (power/knowledge), and the entire tradition of ideology critique. The base-superstructure model, however contested, remains the foundational framework for materialist approaches to culture, law, politics, and religion. The passage on communist society \u2014 hunting in the morning, fishing in the afternoon \u2014 is the most quoted utopian vision in Marxist literature.',
    context: 'Written in Brussels, autumn 1845 to mid-1846. Marx and Engels tried unsuccessfully to publish it and eventually \u201cabandoned it to the gnawing criticism of the mice,\u201d as Marx wrote in the 1859 Preface. First published in full in 1932 by the Marx-Engels Institute in Moscow. The standard text is in Marx-Engels Werke, Vol. 3.',
    relatedWorks: ['theses-on-feuerbach', 'communist-manifesto', 'capital-vol1', 'economic-philosophical-manuscripts']
},

{
    id: 'communist-manifesto',
    title: 'The Communist Manifesto',
    greekTitle: 'Manifest der Kommunistischen Partei',
    philosopher: 'marx',
    category: 'practical',
    categoryLabel: 'Political Philosophy',
    date: '1848 AD',
    dateSort: 1848,
    emoji: '\u2764\uFE0F',
    cardSize: 'wide',
    readingDifficulty: 'Beginner',
    estimatedWordCount: 12000,
    shortDesc: 'The most widely read political document in history \u2014 Marx and Engels\u2019s compressed account of bourgeois society\u2019s revolutionary dynamism and its inevitable destruction, the history of all hitherto existing society as the history of class struggles, and the call for the workers of the world to unite.',
    summary: 'The Manifesto of the Communist Party (Manifest der Kommunistischen Partei), written by Marx and Engels in Brussels and London between December 1847 and January 1848 and published in London by the Communist League on 21 February 1848 \u2014 days before the revolutionary outbreak in Paris that spread across Europe \u2014 is the most widely read, most translated, and most politically influential political document in the history of the modern world.\n\nThe Manifesto opens with the most arresting sentence in modern political writing: \u201cA spectre is haunting Europe \u2014 the spectre of communism.\u201d It then delivers, in four short sections and approximately forty pages, a comprehensive theory of history, an analysis of capitalism\u2019s dynamics, and a programme for revolutionary transformation.\n\nSection I, \u201cBourgeois and Proletarians,\u201d is the philosophical and historical core. It opens with the thesis that the history of all hitherto existing society is the history of class struggles. Freeman and slave, patrician and plebeian, lord and serf, guild-master and journeyman: each epoch has been structured by the conflict between oppressor and oppressed. The bourgeoisie \u2014 the modern capitalist class \u2014 is the product of a long historical development from the medieval commune through the emerging market of early modernity to the industrial revolution. The Manifesto\u2019s most memorable passages are those that celebrate the revolutionary dynamism of the bourgeoisie: \u201cThe bourgeoisie, wherever it has got the upper hand, has put an end to all feudal, patriarchal, idyllic relations.\u201d It has \u201cpitilessly torn asunder the motley feudal ties that bound man to his \u2018natural superiors\u2019 and left remaining no other nexus between man and man than naked self-interest, than callous \u2018cash payment.\u2019\u201d The bourgeoisie creates the modern world \u2014 and it creates the proletariat that will destroy it.\n\nSection II defends the communist programme against objections: the abolition of private property (in the means of production, not personal property), the abolition of the family (as a bourgeois institution), the abolition of national distinctions. The ten-point programme of immediate demands includes a progressive income tax, the abolition of inheritance, the centralisation of credit and communication in the hands of the state, and free education.\n\nSection IV ends with the call that has echoed through modern history: \u201cWorking men of all countries, unite!\u201d (literally: \u201cWorkers of all lands, unite!\u201d \u2014 Proletarier aller L\u00e4nder, vereinigt euch!)',
    themes: ['the history of class struggle', 'the revolutionary role of the bourgeoisie', 'the proletariat as the revolutionary class', 'capitalism\u2019s self-destruction', 'the abolition of private property', 'the ten demands', 'workers of the world unite', 'communism vs other socialist currents', 'the spectre of communism'],
    keyCharacters: [],
    concepts: [
        'The history of all hitherto existing society is the history of class struggles \u2014 the fundamental thesis: every historical epoch is structured by conflict between opposing classes',
        'The revolutionary dynamism of the bourgeoisie \u2014 the Manifesto\u2019s most surprising feature: capitalism\u2019s extraordinary capacity for creative destruction; it creates the modern world and the class that will destroy it',
        'The proletariat \u2014 the modern industrial working class: the class that owns nothing but its labour power; the class whose emancipation is simultaneously the emancipation of humanity',
        'The abolition of private property \u2014 not personal property but property in the means of production; the condition for the abolition of class exploitation',
        'All that is solid melts into air \u2014 capitalism\u2019s compulsive drive to revolutionise production, dissolve traditions, and transform everything into a commodity; the permanent revolution of bourgeois society',
        'Workers of all lands, unite! \u2014 the Manifesto\u2019s closing call; the demand for international working-class solidarity as the condition for revolutionary transformation'
    ],
    structure: 'Preface (various editions 1872\u20131883)\n\nI. Bourgeois and Proletarians\n\u2014 The history of class struggle\n\u2014 The revolutionary role of the bourgeoisie\n\u2014 The development of the proletariat\n\u2014 The inevitable contradiction of capitalism\n\nII. Proletarians and Communists\n\u2014 The communist programme\n\u2014 Objections and responses\n\u2014 The ten-point programme\n\nIII. Socialist and Communist Literature\n\u2014 Reactionary socialism; conservative socialism; utopian socialism\n\nIV. Position of the Communists in Relation to the Various Existing Opposition Parties',
    quote: 'A spectre is haunting Europe \u2014 the spectre of communism. All the powers of old Europe have entered into a holy alliance to exorcise this spectre.',
    additionalQuotes: [
        { text: 'The history of all hitherto existing society is the history of class struggles.', citation: 'The Communist Manifesto, Section I' },
        { text: 'The bourgeoisie, wherever it has got the upper hand, has put an end to all feudal, patriarchal, idyllic relations. It has pitilessly torn asunder the motley feudal ties that bound man to his \u201cnatural superiors\u201d, and has left remaining no other nexus between man and man than naked self-interest, than callous \u201ccash payment\u201d.', citation: 'The Communist Manifesto, Section I' },
        { text: 'All that is solid melts into air, all that is holy is profaned, and man is at last compelled to face with sober senses his real conditions of life, and his relations with his kind.', citation: 'The Communist Manifesto, Section I' },
        { text: 'The proletarians have nothing to lose but their chains. They have a world to win. Workers of all lands, unite!', citation: 'The Communist Manifesto, Section IV (closing lines)' }
    ],
    commentary: [
        { philosopher: 'Marshall Berman', text: 'Berman\u2019s All That Is Solid Melts into Air (1982) is the most celebrated cultural reading of the Manifesto. Berman argues that Marx\u2019s portrait of capitalist modernity \u2014 its ceaseless self-destruction and recreation, the dissolution of all fixed relations, the compulsive drive to revolutionise \u2014 is simultaneously the most powerful diagnosis of modernity and the most paradoxical, since communism promises to achieve the stability and community that capitalism perpetually destroys.' },
        { philosopher: 'Eric Hobsbawm', text: 'Hobsbawm\u2019s introduction to the Verso edition (1998) situates the Manifesto in its historical context and assesses its extraordinary predictive record: its account of globalisation, the concentration of capital, the destruction of precapitalist social forms, and the subordination of all social relations to market logic reads as a description of the late twentieth century despite being written in 1848.' },
        { philosopher: 'Gareth Stedman Jones', text: 'Stedman Jones\u2019s Karl Marx: Greatness and Illusion (2016) and his introduction to the Penguin edition of the Manifesto provide the most historically nuanced reading, situating it within the specific political debates of 1847\u201348 and resisting the tendency to read it as a finished, timeless statement of Marxist theory.' }
    ],
    modernRelevance: 'The Communist Manifesto is the most widely read and most politically influential text in modern history. It has been translated into more languages, published in more editions, and claimed by more political movements than any other political document. Its account of capitalism\u2019s revolutionary dynamism \u2014 the compulsion to revolutionise production, to dissolve traditional ties, to subordinate everything to market logic \u2014 is regularly cited by commentators across the political spectrum as the most prescient description of contemporary capitalism. \u201cAll that is solid melts into air\u201d has become the defining phrase for the experience of capitalist modernity. The concept of class struggle, however contested, remains the foundational category of left politics worldwide.',
    context: 'Written in Brussels and London, December 1847 \u2013 January 1848. Marx and Engels had been commissioned by the Communist League at its second congress (November\u2013December 1847) to write a programme. Published in London on 21 February 1848, days before the outbreak of revolution in Paris. Translated into English by Helen Macfarlane and published in George Julian Harney\u2019s Red Republican in 1850. Marx and Engels wrote prefaces to the German editions of 1872 and 1883 and to various translations, noting what they would and would not revise. The most widely used English translation is by Samuel Moore (1888), revised by Engels.',
    relatedWorks: ['german-ideology', 'capital-vol1', 'economic-philosophical-manuscripts', 'civil-war-in-france']
}

);
