/* DATA PART 21a — Marx: Economic and Philosophical Manuscripts of 1844 + Theses on Feuerbach */
window.WORKS.push(

{
    id: 'economic-philosophical-manuscripts',
    title: 'Economic and Philosophical Manuscripts of 1844',
    greekTitle: '\u00d6konomisch-philosophische Manuskripte aus dem Jahre 1844',
    philosopher: 'marx',
    category: 'metaphysics',
    categoryLabel: 'Philosophy & Political Economy',
    date: '1844 AD',
    dateSort: 1844,
    emoji: '\u26D3\uFE0F',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 80000,
    shortDesc: 'The philosophical foundations of Marxism \u2014 Marx\u2019s most humanistic work, developing the concept of alienated labour as the central pathology of capitalism and arguing that the worker\u2019s estrangement from the product, the process, the species-being, and other workers is the condition from which communism promises liberation.',
    summary: 'The Economic and Philosophical Manuscripts of 1844 (also known as the Paris Manuscripts), written in Paris between April and August 1844 and unpublished during Marx\u2019s lifetime (first published in full in 1932 by the Marx-Engels Institute in Moscow), are the most philosophically rich of Marx\u2019s writings and the primary source for humanist interpretations of Marxism. Marx was twenty-six. The manuscripts were written during the same period as his first encounter with Engels (August 1844) and his intensive study of political economy (Smith, Ricardo, Mill) and his critical engagement with Hegel and Feuerbach.\n\nThe manuscripts are organised around the concept of alienated labour (entfremdete Arbeit), which Marx develops through a critique of political economy\u2019s starting assumptions. Political economy, Marx argues, accepts the estrangement of the worker as a natural fact and then explains the system\u2019s workings from within that presupposition. But political economy never asks: why does the worker become poorer the more wealth they produce? Why does labour\u2019s product confront the worker as an alien power? The answer requires going behind political economy to the concrete activity of labour itself.\n\nMarx distinguishes four forms of alienation. First, the worker is alienated from the product of labour: the object the worker produces belongs to another and confronts the worker as an alien, hostile power. The more the worker produces, the more powerful becomes the world of objects that dominates them. Second, the worker is alienated from the act of production itself: labour is not voluntary but coerced; the worker feels themselves only when not working, and not themselves when working; labour is not the satisfaction of a need but a means for satisfying needs outside itself. Third, the worker is alienated from their species-being (Gattungswesen): the human being is distinguished from animals by the fact that they make their life-activity itself an object of consciousness and will \u2014 they produce freely, universally, according to the standards of beauty; capitalism reduces this free productive activity to mere survival. Fourth, the worker is alienated from other workers: the alienation from one\u2019s product, process, and species-being entails the alienation from every other human being.\n\nThe manuscripts also contain extended discussions of private property, money, communism, and Hegel\u2019s philosophy. The critique of Hegel is double-edged: Hegel is right that self-estrangement is the fundamental problem, but wrong to locate it in consciousness rather than in material production. The Phenomenology of Spirit is the philosophical expression of economic alienation, not its analysis.',
    themes: ['alienated labour', 'the four forms of alienation', 'species-being', 'the critique of political economy', 'private property', 'communism as the positive abolition of alienation', 'the critique of Hegel', 'money as the alienated power of humanity', 'human nature and labour', 'Feuerbach and materialism'],
    keyCharacters: [],
    concepts: [
        'Alienated labour (entfremdete Arbeit) \u2014 the condition in which the worker\u2019s productive activity and its products become alien, hostile powers that dominate the worker; the central pathology of capitalism',
        'The four forms of alienation \u2014 from the product (which confronts the worker as alien), from the act of production (which is coerced), from species-being (free universal production reduced to survival), from other workers',
        'Species-being (Gattungswesen) \u2014 the human being\u2019s distinctive capacity to make its own life-activity an object of consciousness; to produce freely, universally, according to beauty; capitalism reduces this to mere animal survival',
        'Private property as the consequence of alienated labour \u2014 private property is not the cause of alienation but its expression and result; the abolition of private property is the abolition of alienation',
        'Communism as the positive abolition of private property \u2014 not mere equalisation of poverty but the genuine appropriation of human essence, the return of the human being to itself as a social being',
        'Money as the alienated power of humanity \u2014 money transforms all human powers and qualities into their opposite; it is the bond of all bonds, the universal pimp; it confounds and exchanges everything',
        'The critique of Hegel \u2014 Hegel is right that alienation is the fundamental problem but wrong to locate it in thought rather than in material productive activity; the Phenomenology is the philosophical expression of economic alienation'
    ],
    structure: 'First Manuscript: Wages of Labour; Profit of Capital; Rent of Land\n\u2014 Estranged Labour (the four forms of alienation)\n\nSecond Manuscript: [mostly missing] The Relation of Private Property\n\nThird Manuscript:\n\u2014 Private Property and Labour\n\u2014 Private Property and Communism\n\u2014 The Power of Money in Bourgeois Society\n\u2014 Critique of Hegel\u2019s Dialectic and General Philosophy\n\u2014 [pages missing from original manuscript]',
    quote: 'The worker becomes poorer the more wealth he produces, the more his production increases in power and extent. The worker becomes an ever cheaper commodity the more commodities he produces. The devaluation of the human world increases in direct relation with the increase in value of the world of things.',
    additionalQuotes: [
        { text: 'The alienation of the worker in his product means not only that his labour becomes an object, an external existence, but that it exists outside him, independently, as something alien to him, and that it becomes a power on its own confronting him.', citation: 'Economic and Philosophical Manuscripts, First Manuscript, \u201cEstranged Labour\u201d' },
        { text: 'Money is the alienated essence of man\u2019s work and existence; this essence dominates him and he worships it.', citation: 'Economic and Philosophical Manuscripts, Third Manuscript, \u201cThe Power of Money\u201d' },
        { text: 'Communism is the positive abolition of private property, of human self-alienation, and thus the real appropriation of human nature through and for man. It is therefore the return of man himself as a social, that is, really human being.', citation: 'Economic and Philosophical Manuscripts, Third Manuscript, \u201cPrivate Property and Communism\u201d' }
    ],
    commentary: [
        { philosopher: 'Louis Althusser', text: 'Althusser\u2019s For Marx (1965; English 1969) is the most consequential theoretical intervention on the Manuscripts. Althusser argued that there is an \u201cepistemological break\u201d (coupure \u00e9pist\u00e9mologique) between the early humanist Marx of the Manuscripts (still within the orbit of Hegelian and Feuerbachian humanism) and the mature scientific Marx of Capital. The concept of alienation is pre-scientific ideology; the categories of Capital are the genuine science of history. This reading provoked an enormous debate and defined the terms of Marxist theory for two decades.' },
        { philosopher: 'Erich Fromm', text: 'Fromm\u2019s Marx\u2019s Concept of Man (1961) is the paradigmatic humanist reading of the Manuscripts, directly opposed to Althusser. Fromm argued that the concept of alienated labour is not a pre-scientific relic but the heart of Marx\u2019s entire project; that Capital is the economic analysis of the same alienation that the Manuscripts analyse philosophically; and that Marx\u2019s true intellectual ancestor is not Hegel alone but the entire tradition of humanist ethics from Aristotle through Spinoza.' },
        { philosopher: 'Georg Luk\u00e1cs', text: 'Luk\u00e1cs\u2019s History and Class Consciousness (1923) \u2014 written before the Manuscripts were published \u2014 reconstructed the concept of reification (Verdinglichung) from Capital that is structurally identical to the alienation of the Manuscripts. When the Manuscripts were published in 1932, they were immediately recognised as the philosophical basis for the approach Luk\u00e1cs had already developed. His later work acknowledged the Manuscripts as the foundation of his own theoretical project.' },
        { philosopher: 'Hannah Arendt', text: 'Arendt\u2019s The Human Condition (1958) engages critically with Marx\u2019s concept of labour and species-being in the Manuscripts. Arendt argues that Marx conflates labour (the biological process of sustaining life, which leaves no lasting products) with work (the fabrication of a durable world) and action (the specifically human activity of political life). The concept of species-being as productive activity misses the distinctively political dimension of human existence.' }
    ],
    modernRelevance: 'The Economic and Philosophical Manuscripts of 1844 are the primary source for humanist Marxism, critical theory, and the philosophical foundations of social criticism. The concept of alienated labour has been developed into the sociology of work (Braverman\u2019s Labour and Monopoly Capital, 1974), the psychology of alienation (Fromm), existentialist Marxism (Sartre\u2019s Critique of Dialectical Reason), and feminist theory (the extension of alienation analysis to domestic labour and reproductive work). The concept of species-being anticipates contemporary discussions of human capabilities (Sen, Nussbaum). The critique of money as the alienated essence of human powers resonates with contemporary discussions of financialisation, commodity fetishism, and the colonisation of human relationships by market logic.',
    context: 'Written in Paris between April and August 1844. Marx had moved to Paris in October 1843 after the suppression of the Rheinische Zeitung, which he had edited. He was studying political economy intensively and was deeply influenced by Feuerbach\u2019s materialist transformation of Hegel. The manuscripts were never completed or published by Marx; he apparently abandoned them when he and Engels began working on The German Ideology (1845\u201346). They were first published in full in 1932 by the Marx-Engels Institute in Moscow, edited by D. Ryazanov. Their publication transformed the interpretation of Marx and generated the debate between humanist and structuralist Marxism that dominated the twentieth century.',
    relatedWorks: ['communist-manifesto', 'german-ideology', 'capital-vol1', 'theses-on-feuerbach']
},

{
    id: 'theses-on-feuerbach',
    title: 'Theses on Feuerbach',
    greekTitle: 'Thesen \u00fcber Feuerbach',
    philosopher: 'marx',
    category: 'method',
    categoryLabel: 'Philosophy of Praxis',
    date: '1845 AD',
    dateSort: 1845,
    emoji: '\u26A1',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 1500,
    shortDesc: 'Eleven theses \u2014 the most concentrated philosophical statement in modern thought, culminating in the most quoted sentence in the history of philosophy: \u201cPhilosophers have only interpreted the world in various ways; the point is to change it.\u201d',
    summary: 'The Theses on Feuerbach, written by Marx in Brussels in the spring of 1845 and first published by Engels in 1888 as an appendix to his Ludwig Feuerbach and the End of Classical German Philosophy, are eleven short theses that constitute the most compressed and most consequential philosophical statement in the Marxist tradition. Marx never published them himself; Engels described them as \u201cthe first document in which is deposited the brilliant germ of the new world outlook.\u201d\n\nThe theses are directed primarily against Feuerbach, whose materialism Marx regards as the best available alternative to Hegelian idealism but as still fundamentally contemplative: Feuerbach\u2019s materialism grasps the world as object, as something to be perceived and understood, but not as human sensuous activity, as practice (Praxis). The fundamental defect of all previous materialism is precisely this: it grasps the world as given, not as made.\n\nThe first thesis states the problem: Feuerbach\u2019s materialism grasps the external world only in the form of the object, not as sensuous human activity \u2014 practice. Therefore, the active side was developed by idealism, but idealism developed it abstractly (in thought) rather than concretely (in practice). The resolution: a materialism that grasps the world as constituted by human sensuous practical activity \u2014 the labour and social practice through which human beings transform both the world and themselves.\n\nThesis 3 states the fundamental problem with previous materialist theories of education and social reform: if human beings are products of circumstances and education, then circumstances must be changed \u2014 but who changes the circumstances? The educator must themselves be educated. Marx\u2019s resolution: the coincidence of changing circumstances and human activity can only be grasped as revolutionary practice (revolutionäre Praxis).\n\nThesis 11 \u2014 the most famous sentence in modern philosophy: \u201cPhilosophers have only interpreted the world in various ways; the point is to change it.\u201d This is not the rejection of philosophy but the demand for a philosophy that is simultaneously theoretical and practical \u2014 that understands the world as constituted by human practice and therefore as changeable through human practice.',
    themes: ['practice (Praxis) as the foundation of knowledge', 'the critique of Feuerbach\u2019s contemplative materialism', 'the coincidence of theory and practice', 'sensuous human activity as the basis of reality', 'revolutionary practice', 'the transformation of philosophy into social criticism', 'the eleventh thesis'],
    keyCharacters: [],
    concepts: [
        'Praxis \u2014 sensuous human activity through which human beings transform the world and themselves; the foundation of a genuinely materialist philosophy that is also transformative',
        'Contemplative materialism \u2014 Feuerbach\u2019s defect: grasps the world as object (to be perceived and understood) but not as practice (to be transformed); the active side is left to idealism',
        'The coincidence of changing circumstances and self-changing \u2014 Thesis 3: human beings are shaped by circumstances AND they change circumstances; the resolution of this apparent paradox is revolutionary practice',
        'The point is to change it \u2014 Thesis 11: philosophy must be not only the interpretation but the transformation of the world; theory and practice must be unified in revolutionary praxis',
        'The human essence as the ensemble of social relations \u2014 Thesis 6: Feuerbach abstracts an individual human essence; the real human essence is the ensemble (Ensemble) of social relations in which human beings exist'
    ],
    structure: 'Eleven theses:\n1. The defect of previous materialism (contemplation vs practice)\n2. The question of human thinking and truth is a practical question\n3. The materialist doctrine of circumstances and education; revolutionary practice\n4. Feuerbach and religious self-estrangement\n5. Feuerbach\u2019s sensuous contemplation; practice and thinking\n6. Feuerbach\u2019s abstraction of the human essence\n7. Religious sentiment as a social product\n8. Social life is essentially practical\n9. The standpoint of intuition vs social humanity\n10. The standpoint of old materialism vs new materialism\n11. Philosophers have only interpreted the world; the point is to change it',
    quote: 'Philosophers have only interpreted the world in various ways; the point is to change it.',
    additionalQuotes: [
        { text: 'The question whether objective truth can be attributed to human thinking is not a question of theory but is a practical question. Man must prove the truth, that is, the reality and power, the this-sidedness of his thinking, in practice.', citation: 'Theses on Feuerbach, Thesis 2' },
        { text: 'Feuerbach resolves the religious world into its secular basis. But the fact that the secular basis lifts off from itself and establishes itself in the clouds as an independent realm can only be explained by the inner strife and intrinsic contradictoriness of this secular basis.', citation: 'Theses on Feuerbach, Thesis 4' }
    ],
    commentary: [
        { philosopher: 'Antonio Gramsci', text: 'Gramsci\u2019s Prison Notebooks (1929\u201335) develop the concept of praxis from the Theses into a comprehensive philosophy of history and politics. Gramsci\u2019s \u201cphilosophy of praxis\u201d \u2014 his term for Marxism, partly for prison censor evasion \u2014 understands theory and practice as dialectically unified: theory is always already embedded in practical social activity; practice always already contains theoretical assumptions. The concept of hegemony \u2014 the role of ideas and culture in maintaining social domination \u2014 is the political development of the Theses\u2019 insight that changing the world requires changing how people think.' },
        { philosopher: 'J\u00fcrgen Habermas', text: 'Habermas\u2019s Knowledge and Human Interests (1968) engages with the Theses as the founding statement of a tradition that conflates theoretical knowledge with technical control: Marx\u2019s concept of praxis reduces all human interests to the interest in controlling nature through labour. Habermas argues that this misses the communicative and emancipatory dimensions of human rationality that cannot be reduced to technical practice.' }
    ],
    modernRelevance: 'The Theses on Feuerbach are the founding statement of the tradition of critical theory, which insists that genuine social knowledge is inseparable from social transformation. The concept of praxis has been central to the Frankfurt School (Adorno, Horkheimer, Marcuse, Habermas), to liberation theology (Gutierrez), to feminist theory (the insistence that theory must be grounded in practical experience and directed toward liberation), and to contemporary discussions of engaged scholarship, public philosophy, and the relationship between academic knowledge and political practice. The eleventh thesis has been quoted more often than any other sentence in modern philosophy.',
    context: 'Written in Brussels in the spring of 1845. Marx moved to Brussels after being expelled from Paris by the French government in February 1845. The Theses were jotted in a notebook and not published by Marx. Engels published them in 1888 as an appendix to his Ludwig Feuerbach and the End of Classical German Philosophy, noting that they were hastily written and not intended for publication but invaluable as a concise statement of the new outlook. The standard text is in Marx-Engels Werke, Vol. 3.',
    relatedWorks: ['economic-philosophical-manuscripts', 'german-ideology', 'communist-manifesto', 'capital-vol1']
}

);
