// ============================================================
// BERKELEY — Part A (Verified Data)
// Principles of Human Knowledge, Three Dialogues, New Theory of Vision
// Quotes verified against Luce/Jessop Works (W) edition
// ============================================================

window.WORKS.push(

// ────────────────────────────────────────────────────────────
// 1. A TREATISE CONCERNING THE PRINCIPLES OF HUMAN KNOWLEDGE (1710)
// ────────────────────────────────────────────────────────────
{
    id: 'principles-human-knowledge',
    title: 'A Treatise Concerning the Principles of Human Knowledge',
    greekTitle: 'A Treatise Concerning the Principles of Human Knowledge',
    philosopher: 'berkeley',
    category: 'metaphysics',
    categoryLabel: 'Metaphysics & Epistemology',
    date: '1710 AD',
    dateSort: 1710,
    emoji: '\uD83D\uDC41\uFE0F',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 35000,
    shortDesc: 'The book that abolished matter \u2014 Berkeley\u2019s systematic demonstration that the physical world consists entirely of ideas in minds, that esse est percipi, and that the very notion of unperceived material substance is an incoherent abstraction.',
    summary: 'The Treatise Concerning the Principles of Human Knowledge, published in Dublin by Aaron Rhames for Jeremy Pepyat in 1710, is one of the most audacious philosophical texts ever written. Berkeley was twenty-five. His central thesis \u2014 that material substance does not exist, that the objects of the physical world are collections of ideas perceived by minds, and that for a sensible thing to exist is simply for it to be perceived (esse est percipi) \u2014 struck his contemporaries as absurd. Yet the arguments he advances are among the most rigorous in early modern philosophy.\n\nBerkeley begins from Locke\u2019s epistemology \u2014 that the immediate objects of the mind are ideas \u2014 and asks the devastating question Locke never adequately answered: if all we ever perceive are our own ideas, what grounds have we for believing that material objects exist behind or beyond those ideas? Locke had posited \u201cmaterial substance\u201d as the substratum supporting sensible qualities, but Berkeley demonstrates that this notion is empty: we have no idea of material substance whatsoever, and the very concept of an idea existing unperceived involves a contradiction.\n\nThe famous \u201cmaster argument\u201d of \u00A7\u00A722\u201323 turns on exactly this point: it is impossible even to conceive of something existing unconceived, because the act of conception is itself a form of perception. To conceive of an unperceived tree is to perceive it in conception \u2014 the supposed \u201cunconceived thing\u201d is therefore always already conceived (W II, 50\u201351).\n\nFrom the impossibility of unperceived material existence Berkeley draws his positive metaphysics: reality consists of minds (spirits) and ideas. Ideas are passive \u2014 they have no causal power. Their order, regularity, and vivacity require an explanation: God, the infinite mind who perceives all ideas at all times, sustaining the physical world in continuous existence and guaranteeing its order through what we call the \u201claws of nature.\u201d\n\nThe Principles also contains Berkeley\u2019s attack on abstract general ideas (\u00A7\u00A76\u201325, drawing on and radicalising Locke\u2019s nominalism), his philosophy of mathematics (\u00A7\u00A7118\u2013134), and his critique of Newtonian absolute space, time, and motion (\u00A7\u00A7110\u2013117) \u2014 arguments that would influence Mach and, through Mach, Einstein. The second part, which was to address moral philosophy and natural philosophy, was reportedly lost during Berkeley\u2019s travels in Italy (1716\u201320) and never rewritten.',
    themes: ['immaterialism', 'esse est percipi', 'the critique of material substance', 'the critique of abstract ideas', 'God as infinite perceiver', 'idealism', 'the master argument', 'the critique of Newtonian absolute space', 'philosophy of mathematics'],
    keyCharacters: [],
    concepts: [
        'Esse est percipi (vel percipere) \u2014 to be is to be perceived (or to perceive); existence for sensible things is perception (Principles \u00A73; W II, 42)',
        'The master argument \u2014 it is impossible to conceive of an unconceived object, because conceiving is itself perceiving (Principles \u00A7\u00A722\u201323; W II, 50\u201351)',
        'The critique of abstract ideas \u2014 there is no such thing as an abstract general idea; all ideas are particular; abstraction is an illusion generated by the misuse of language (Principles, Introduction \u00A7\u00A76\u201325; W II, 25\u201340)',
        'Ideas as passive \u2014 ideas have no causal power; they are inert objects of perception; only spirits (minds) are active (Principles \u00A725; W II, 52)',
        'Spirit (mind) as the only substance \u2014 only minds are genuine substances; minds are active, perceiving beings; ideas are their passive contents (Principles \u00A7\u00A726\u201333; W II, 52\u201356)',
        'God as infinite perceiver \u2014 God sustains the physical world by perceiving all ideas continuously; the \u201claws of nature\u201d are the grammar of God\u2019s visual language (Principles \u00A7\u00A729\u201333; W II, 53\u201356)',
        'Primary and secondary qualities collapsed \u2014 Berkeley denies Locke\u2019s distinction; all sensible qualities are ideas in the mind (Principles \u00A7\u00A79\u201315; W II, 44\u201347)',
        'Material substance as meaningless \u2014 the concept of an unperceived substratum supporting qualities is incoherent; \u201cmatter\u201d is a word without an idea (Principles \u00A7\u00A716\u201324; W II, 47\u201351)',
        'The divine visual language \u2014 the regularities of nature are a language through which God communicates with finite minds (Principles \u00A7\u00A7108\u2013109; W II, 91\u201392)'
    ],
    structure: 'Introduction (\u00A7\u00A71\u201325): The critique of abstract ideas\n\u2014 The source of philosophical error: the belief in abstract general ideas\n\u2014 Berkeley\u2019s alternative: all ideas are particular\n\nPart One (\u00A7\u00A71\u2013156):\n\u00A7\u00A71\u201333: The esse est percipi thesis; the master argument; the impossibility of material substance\n\u00A7\u00A734\u201384: Objections and replies \u2014 Berkeley anticipates and answers every major criticism\n\u00A7\u00A785\u2013100: The nature of spirit; God as the cause of ideas\n\u00A7\u00A7101\u2013134: Mathematics, infinity, and the critique of abstract ideas applied to geometry and arithmetic\n\u00A7\u00A7135\u2013156: Application to natural philosophy; the critique of absolute space, time, and motion\n\nPart Two: [Lost during Berkeley\u2019s Italian travels; never rewritten]',
    quote: 'Some truths there are so near and obvious to the mind, that a man need only open his eyes to see them. Such I take this important one to be, to wit, that all the choir of heaven and furniture of the earth, in a word all those bodies which compose the mighty frame of the world, have not any subsistence without a mind \u2014 that their being is to be perceived or known.',
    additionalQuotes: [
        { text: 'But say you, surely there is nothing easier than to imagine trees, for instance, in a park, or books existing in a closet, and nobody by to perceive them. I answer, you may so, there is no difficulty in it: but what is all this, I beseech you, more than framing in your mind certain ideas which you call books and trees, and at the same time omitting to frame the idea of any one that may perceive them? But do not you yourself perceive or think of them all the while?', citation: 'Principles \u00A723; W II, 50\u201351' },
        { text: 'It is indeed an opinion strangely prevailing amongst men that houses, mountains, rivers, and in a word all sensible objects have an existence natural or real, distinct from their being perceived by the understanding.', citation: 'Principles \u00A74; W II, 42' },
        { text: 'The table I write on, I say, exists \u2014 that is, I see and feel it; and if I were out of my study I should say it existed \u2014 meaning thereby that if I was in my study I might perceive it, or that some other spirit actually does perceive it.', citation: 'Principles \u00A73; W II, 42' },
        { text: 'In short, if there were external bodies, it is impossible we should ever come to know it; and if there were not, we might have the very same reasons to think there were that we have now.', citation: 'Principles \u00A720; W II, 49\u201350' }
    ],
    commentary: [
        { philosopher: 'Samuel Johnson', text: 'Boswell records the most famous \u201crefutation\u201d of the Principles: Johnson striking his foot against a large stone and declaring \u201cI refute it thus\u201d (Life of Johnson, 6 August 1763). Berkeley had anticipated this objection in \u00A7\u00A734\u201340: kicking a stone proves only that certain tactile ideas follow certain visual ones in a regular sequence \u2014 exactly what immaterialism predicts.' },
        { philosopher: 'David Hume', text: 'Hume\u2019s verdict in the Enquiry Concerning Human Understanding (1748), Section XII: \u201cBerkeley\u2019s arguments admit of no answer and produce no conviction.\u201d Hume meant that the arguments are logically impeccable \u2014 no step can be identified as fallacious \u2014 yet the conclusion is one that no sane person actually believes.' },
        { philosopher: 'Immanuel Kant', text: 'Kant distinguished his \u201ctranscendental idealism\u201d from Berkeley\u2019s \u201cdogmatic idealism\u201d in the Critique of Pure Reason (B274\u2013275), adding a \u201cRefutation of Idealism\u201d in the second edition (1787). Kant insisted that his position grants \u201cempirical reality\u201d to physical objects while denying them existence as things in themselves \u2014 though Berkeley had specifically denied that he was making the world illusory.' },
        { philosopher: 'Karl Popper', text: 'Popper\u2019s \u201cA Note on Berkeley as Precursor of Mach and Einstein\u201d (British Journal for the Philosophy of Science, 1953) identified the Principles\u2019 critique of absolute space as its most scientifically significant contribution, arguing that Berkeley should be recognized as the originator of the relational theory of space that the twentieth century vindicated.' },
        { philosopher: 'A.A. Luce', text: 'Luce\u2019s Berkeley\u2019s Immaterialism (1945) did more than any other work to rescue the Principles from misreading. Berkeley was not denying the reality of the physical world \u2014 he was denying one particular philosophical theory about what that reality consists in. His world is the world of common experience; the difference is that he correctly identifies what it consists in: ideas in minds.' }
    ],
    modernRelevance: 'Berkeley\u2019s immaterialism has experienced a remarkable revival. His arguments against \u201cmatter\u201d have been compared to difficulties quantum mechanics poses for classical realism: the observer-dependence of quantum measurement echoes Berkeley\u2019s thesis that existence requires perception. His critique of abstract ideas anticipates nominalism in philosophy of mathematics and the later Wittgenstein. His attack on absolute space influenced Mach, who influenced Einstein. In philosophy of perception, the debate between direct realism, representationalism, and idealism is conducted in terms Berkeley established. His thesis that the physical world is fundamentally informational has been compared to John Wheeler\u2019s \u201cit from bit\u201d hypothesis and to contemporary digital physics.',
    context: 'Published in Dublin by Aaron Rhames for Jeremy Pepyat in 1710. Berkeley wrote it at Trinity College Dublin between 1708 and 1709, drawing on the Philosophical Commentaries (notebooks kept since 1707). He was twenty-five. The reception was devastating: readers assumed it was a joke, a provocation, or insanity. Berkeley later said that when he arrived in London, the \u201cmob of people who write and read and talk about philosophy\u201d had already decided his book was absurd without having read it. The poor reception led him to restate the arguments in the Three Dialogues (1713). A second edition of the Principles appeared in 1734 with a new preface. The lost second part was reportedly destroyed during Berkeley\u2019s Italian travels (1716\u201320).',
    relatedWorks: ['three-dialogues', 'essay-towards-new-theory-vision', 'de-motu', 'alciphron', 'philosophical-commentaries']
},

// ────────────────────────────────────────────────────────────
// 2. THREE DIALOGUES BETWEEN HYLAS AND PHILONOUS (1713)
// ────────────────────────────────────────────────────────────
{
    id: 'three-dialogues',
    title: 'Three Dialogues between Hylas and Philonous',
    greekTitle: 'Three Dialogues between Hylas and Philonous',
    philosopher: 'berkeley',
    category: 'metaphysics',
    categoryLabel: 'Metaphysics & Epistemology',
    date: '1713 AD',
    dateSort: 1713,
    emoji: '\uD83D\uDCAC',
    cardSize: 'wide',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 45000,
    shortDesc: 'The most beautifully written philosophical dialogue since Plato \u2014 Berkeley restates his immaterialism through a dramatic conversation in which the materialist Hylas is led, step by devastating step, to the conclusion that matter does not exist.',
    summary: 'The Three Dialogues between Hylas and Philonous, published in London by Henry Clements in 1713, is Berkeley\u2019s masterpiece of philosophical argumentation and one of the finest dialogues in the history of philosophy. Written because the Principles had been universally misunderstood, the Three Dialogues restates the case for immaterialism with dramatic vividness and argumentative patience the treatise form could not achieve.\n\nThe two characters \u2014 Hylas (from the Greek hyl\u0113, \u201cmatter\u201d), who defends materialism, and Philonous (from philos nous, \u201clover of mind\u201d), who is Berkeley himself \u2014 meet on three successive mornings in a college garden.\n\nThe First Dialogue systematically dismantles the distinction between primary and secondary qualities. Hylas begins by asserting that at least some qualities (extension, figure, motion, solidity) belong to objects independently of perception. Philonous shows through the argument from perceptual relativity that primary qualities are as perceiver-dependent as secondary ones. Hylas retreats successively \u2014 from naive realism to representative realism to the material substrate theory \u2014 and each retreat is shown to be untenable.\n\nThe Second Dialogue presents the positive doctrine: if there is no material substance, what sustains the physical world? Philonous argues that God, the infinite mind, perceives all things at all times. The \u201claws of nature\u201d are the regular grammar of God\u2019s ideas.\n\nThe Third Dialogue addresses a battery of objections: that immaterialism makes the world an illusion, that it contradicts the senses, that it cannot account for creation before human beings existed, that it cannot distinguish reality from hallucination. Each is met with extraordinary subtlety. The dialogue concludes with Hylas\u2019s full conversion \u2014 and his recognition that materialism, not immaterialism, leads to skepticism.',
    themes: ['immaterialism restated', 'primary and secondary qualities', 'the argument from perceptual relativity', 'God as infinite perceiver', 'the divine visual language', 'anti-skepticism', 'the dialogue form', 'the reality of the sensible world'],
    keyCharacters: [
        { name: 'Hylas', role: 'The materialist \u2014 from the Greek hyl\u0113 (matter); defends material substance with intelligence and persistence; his successive retreats constitute the dramatic architecture of the work' },
        { name: 'Philonous', role: 'The lover of mind \u2014 Berkeley\u2019s spokesman; his arguments move from the negative (the incoherence of matter) to the positive (God as sustaining perceiver) with patience and literary grace' }
    ],
    concepts: [
        'The argument from perceptual relativity \u2014 the same object produces different sensory ideas in different conditions, proving all sensible qualities are mind-dependent (First Dialogue; W II, 175\u2013194)',
        'The collapse of the primary/secondary quality distinction \u2014 extension, figure, and motion are as perceiver-dependent as colour and temperature (First Dialogue; W II, 187\u2013194)',
        'The incoherence of material substrate \u2014 the idea of a substance that supports qualities but has no qualities of its own is an empty abstraction (First Dialogue; W II, 197\u2013199)',
        'God as guarantor of continuity \u2014 objects continue to exist when no finite mind perceives them because God perceives them always (Second Dialogue; W II, 210\u2013212)',
        'The divine visual language \u2014 the regularities of nature are God\u2019s communication with finite minds (Second Dialogue; W II, 213\u2013215)',
        'Anti-skepticism \u2014 immaterialism is not skepticism but its cure; materialism, by interposing an unknowable substance between us and reality, is the true source of doubt (Third Dialogue; W II, 228\u2013230)',
        'Real things vs chimeras \u2014 real ideas are vivid, ordered, involuntary, and coherent; hallucinations and fantasies lack these features (Third Dialogue; W II, 235\u2013236)'
    ],
    structure: 'First Dialogue: The dismantling of materialism\n\u2014 Heat, colour, taste, sound as ideas in the mind\n\u2014 Extension, figure, motion equally mind-dependent\n\u2014 The failure of representative realism\n\u2014 Hylas\u2019s successive retreats\n\nSecond Dialogue: The positive doctrine\n\u2014 God as infinite perceiver\n\u2014 Nature as the language of God\n\u2014 Creation, duration, and continuity\n\nThird Dialogue: Objections and replies\n\u2014 Is immaterialism an illusion doctrine?\n\u2014 Can it account for creation before human beings?\n\u2014 How does it distinguish reality from hallucination?\n\u2014 Hylas\u2019s conversion and the vindication of common sense',
    quote: 'I am not for changing things into ideas, but rather ideas into things; since those immediate objects of perception, which according to you are only appearances of things, I take to be the real things themselves.',
    additionalQuotes: [
        { text: 'PHILONOUS: Can a real thing in itself invisible be like a colour; or a real thing which is not audible be like a sound? In a word, can anything be like a sensation or idea, but another sensation or idea?', citation: 'Three Dialogues, First Dialogue; W II, 206' },
        { text: 'PHILONOUS: The same principles which, at first view, lead to scepticism, pursued to a certain point, bring men back to common sense.', citation: 'Three Dialogues, Third Dialogue; W II, 263' },
        { text: 'PHILONOUS: Look! are not the fields covered with a delightful verdure? Is there not something in the woods and groves, in the rivers and clear springs, that soothes, that delights, that transports the soul? How should those principles be entertained that lead us to think all the visible beauty of the creation a false imaginary glare?', citation: 'Three Dialogues, Third Dialogue; W II, 210' },
        { text: 'PHILONOUS: I do not pretend to be a setter-up of new notions. My endeavours tend only to unite, and place in a clearer light, that truth which was before shared between the vulgar and the philosophers.', citation: 'Three Dialogues, Third Dialogue; W II, 262' }
    ],
    commentary: [
        { philosopher: 'David Hume', text: 'Hume\u2019s assessment in the Enquiry (Section XII) applies equally to the Three Dialogues: \u201cBerkeley\u2019s arguments admit of no answer and produce no conviction.\u201d The paradox Hume identifies \u2014 logically impeccable arguments leading to an unbelievable conclusion \u2014 is the central puzzle of Berkeley scholarship.' },
        { philosopher: 'J.L. Austin', text: 'Austin\u2019s Sense and Sensibilia (1962) takes Berkeley as a primary target but acknowledges that the Three Dialogues\u2019 arguments against material substance are \u201cmore powerful than most philosophers have been willing to admit.\u201d Austin\u2019s own method \u2014 the precise analysis of ordinary language \u2014 owes something to the Dialogues\u2019 technique of tracking the materialist\u2019s retreats.' },
        { philosopher: 'G.J. Warnock', text: 'Warnock\u2019s Berkeley (1953) identified the Three Dialogues as Berkeley\u2019s supreme achievement: \u201ca work that combines the rigour of a treatise with the life of a drama \u2014 one of the very few philosophical works that can genuinely be called beautiful.\u201d' },
        { philosopher: 'Michael Ayers', text: 'Ayers argued that Berkeley is the most underestimated major philosopher in the Western tradition and that the Three Dialogues contains arguments against representationalist epistemology that have never been adequately answered.' }
    ],
    modernRelevance: 'The Three Dialogues\u2019 arguments against \u201cmaterial substance\u201d have gained new life in contemporary philosophy of perception. The debate between direct realism, representationalism, and phenomenalism is conducted in Berkeleyan terms. The argument from perceptual relativity remains one of the central problems. Berkeley\u2019s contention that science describes regularities in experience rather than uncovering hidden machinery of a mind-independent world has been compared to structural realism and to instrumentalist interpretations of quantum mechanics.',
    context: 'Published in London by Henry Clements in 1713. Berkeley wrote it in London in 1712\u201313, determined to gain a wider hearing for the Principles\u2019 doctrines. The dialogue form allowed him to dramatise conversion, anticipate objections in real time, and deploy his considerable literary charm. The Three Dialogues was far better received than the Principles \u2014 praised for its style even by those who rejected its conclusions. Published the same year Berkeley met Swift, Pope, and Addison. A second edition appeared in 1725; a third in 1734.',
    relatedWorks: ['principles-human-knowledge', 'essay-towards-new-theory-vision', 'de-motu', 'alciphron']
},

// ────────────────────────────────────────────────────────────
// 3. AN ESSAY TOWARDS A NEW THEORY OF VISION (1709)
// ────────────────────────────────────────────────────────────
{
    id: 'essay-towards-new-theory-vision',
    title: 'An Essay towards a New Theory of Vision',
    greekTitle: 'An Essay towards a New Theory of Vision',
    philosopher: 'berkeley',
    category: 'natural-philosophy',
    categoryLabel: 'Natural Philosophy',
    date: '1709 AD',
    dateSort: 1709,
    emoji: '\uD83D\uDD2D',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 30000,
    shortDesc: 'Berkeley\u2019s revolutionary first work \u2014 a theory of visual perception that demolished geometrical optics and showed that distance is not seen but learned through association, laying the philosophical foundations for immaterialism.',
    summary: 'The Essay towards a New Theory of Vision, published in Dublin by Aaron Rhames for Jeremy Pepyat in 1709, is Berkeley\u2019s first published philosophical work and one of the most original contributions to the philosophy and psychology of perception ever written. Berkeley was twenty-four.\n\nIts immediate topic is how we perceive distance, magnitude, and situation by sight. The prevailing theory (Descartes, Malebranche, the geometrical opticians) treated this as a problem of geometry: the mind unconsciously calculates distance from the angle of convergence of the two eyes and the angle subtended by the object on the retina.\n\nBerkeley demolishes this. He shows that the angles and lines of geometrical optics are not themselves perceived \u2014 they are theoretical constructs never experienced by the perceiver. A person born blind and suddenly made to see (the Molyneux problem) would have no idea of distance at all. Distance is not a visual datum but something learned through the habitual correlation of visual ideas with tactile ideas over time.\n\nFrom this Berkeley draws a conclusion of enormous significance: the objects of sight and the objects of touch are entirely different. A visible square and a tangible square are not two perceptions of the same object but two different ideas that have been habitually associated. There is no \u201ccommon sensible\u201d \u2014 no single quality perceived by both sight and touch.\n\nThe Essay was Berkeley\u2019s most immediately successful work. Its central claims about learned association became standard doctrine in empiricist psychology from Condillac through Helmholtz. It also laid the philosophical groundwork for the Principles: if visual objects are ideas in the mind, and this is true of one sense, the argument generalises to all senses \u2014 yielding immaterialism.',
    themes: ['visual perception', 'distance perception', 'the Molyneux problem', 'the heterogeneity of sight and touch', 'the critique of geometrical optics', 'the divine visual language', 'the origins of spatial perception', 'empiricist psychology'],
    keyCharacters: [],
    concepts: [
        'Distance is not immediately perceived by sight \u2014 it is learned through habitual association of visual and tactile experience (NTV \u00A7\u00A72\u201328; W I, 171\u2013185)',
        'The Molyneux problem \u2014 a person born blind and made to see could not immediately identify shapes by sight alone; visual and tactile ideas are heterogeneous (NTV \u00A7\u00A7132\u2013133; W I, 224\u2013225)',
        'The heterogeneity thesis \u2014 the objects of sight and the objects of touch are entirely different ideas, not two perceptions of one object (NTV \u00A7\u00A7121\u2013148; W I, 219\u2013232)',
        'Geometrical optics refuted \u2014 the lines and angles of optical theory are mathematical abstractions, not perceived data (NTV \u00A7\u00A712\u201315; W I, 175\u2013177)',
        'The divine visual language \u2014 visual ideas are signs God uses to communicate information about the tangible world to finite minds (NTV \u00A7\u00A7147\u2013148; W I, 231\u2013232)',
        'Minimum visibile \u2014 the smallest visible point; Berkeley argues there is a lower limit to visual perception (NTV \u00A7\u00A780\u201386; W I, 204\u2013208)',
        'Suggestion and association \u2014 the mechanism by which visual cues come to be interpreted as indicating distance and magnitude (NTV \u00A7\u00A716\u201321; W I, 177\u2013180)'
    ],
    structure: '\u00A7\u00A71\u201328: Distance is not immediately seen; refutation of geometrical optics\n\u00A7\u00A729\u201351: How we learn to perceive distance \u2014 convergence, confusion, faintness as learned cues\n\u00A7\u00A752\u201387: The magnitude of objects \u2014 visible and tangible magnitude are distinct\n\u00A7\u00A788\u2013120: Situation \u2014 how we learn that objects are upright (the inverted retinal image problem)\n\u00A7\u00A7121\u2013159: The heterogeneity of sight and touch; the visual world as a divine language\nAppendix (1732 edition): Berkeley\u2019s mature reflections connecting the essay to immaterialism',
    quote: 'We never see and feel one and the same object. That which is seen is one thing, and that which is felt is another. If the visible figure and extension be not the same with the tangible figure and extension, we are not to infer that one and the same thing has different extensions.',
    additionalQuotes: [
        { text: 'Those lines and angles have no real existence in nature, being only an hypothesis framed by the mathematicians, and by them introduced into optics, that they might treat of that science in a geometrical way.', citation: 'NTV \u00A712; W I, 175' },
        { text: 'Upon the whole, I think we may fairly conclude that the proper objects of vision constitute a universal language of the Author of Nature, whereby we are instructed how to regulate our actions in order to attain those things that are necessary to the preservation and well-being of our bodies.', citation: 'NTV \u00A7147; W I, 231' },
        { text: 'Sitting in my study I hear a coach drive along the street; I look through the casement and see it; I walk out and enter into it. Thus, common speech would incline one to think I heard, saw, and touched the same thing, to wit, the coach. It is nevertheless certain the ideas intromitted by each sense are widely different.', citation: 'NTV \u00A746; W I, 192' }
    ],
    commentary: [
        { philosopher: 'Hermann von Helmholtz', text: 'Helmholtz credited Berkeley as the first philosopher to see clearly that spatial perception is not an immediate deliverance of the senses but a construction. His own theory of unconscious inference \u2014 that the visual system arrives at its perception of distance by an inference process below the threshold of consciousness \u2014 is the physiological version of Berkeley\u2019s philosophical argument.' },
        { philosopher: 'J.J. Gibson', text: 'Gibson\u2019s ecological optics was developed in explicit opposition to \u201cBerkeley\u2019s theory.\u201d Gibson argued that distance is not inferred from cues but directly specified by the optic array. Berkeley asked the right question; Gibson offered a different answer.' },
        { philosopher: 'Margaret Atherton', text: 'Atherton\u2019s Berkeley\u2019s Revolution in Vision (1990) argued that the New Theory of Vision is the philosophical laboratory in which Berkeley developed the conceptual tools that would produce immaterialism. The heterogeneity thesis is the first step toward esse est percipi.' }
    ],
    modernRelevance: 'Berkeley\u2019s theory of vision has been a touchstone for three centuries. His claim that spatial perception is learned was apparently confirmed by cataract patients given sight in adulthood (Cheselden 1728; Sinha 2011). However, contemporary research on infant spatial cognition suggests some aspects of spatial perception are innate, challenging Berkeley\u2019s pure associationism. The heterogeneity thesis has influenced discussions of cross-modal perception and the binding problem in consciousness research. The idea that vision constitutes a \u201clanguage\u201d anticipates semiotic approaches to perception and the computational theory of vision.',
    context: 'Published in Dublin by Aaron Rhames for Jeremy Pepyat in 1709. Berkeley\u2019s first published work. Immediately recognised as a major contribution to optics and perception \u2014 Voltaire praised it in the Letters on England. Its central claims were incorporated into empiricist psychology from Condillac to Helmholtz. Berkeley later regarded it as incomplete, arguing in the 1732 edition that the divine visual language thesis pointed toward immaterialism. The standard edition is in W I, 171\u2013239 (Luce/Jessop).',
    relatedWorks: ['principles-human-knowledge', 'three-dialogues', 'de-motu', 'alciphron']
}

);

