// ============================================================
// NIETZSCHE — Part D (Verified Data)
// The Anti-Christ, Ecce Homo
// Quotes verified against KSA and Cambridge translations
// ============================================================

window.WORKS.push(

{
    id: 'anti-christ',
    title: 'The Anti-Christ: A Curse on Christianity',
    greekTitle: 'Der Antichrist: Fluch auf das Christenthum',
    philosopher: 'nietzsche',
    category: 'practical',
    categoryLabel: 'Philosophy of Religion',
    date: '1895 AD',
    dateSort: 1888,
    emoji: '\u2620\uFE0F',
    cardSize: 'normal',
    readingDifficulty: 'Intermediate',
    estimatedWordCount: 30000,
    shortDesc: 'Nietzsche\u2019s most ferocious polemic \u2014 a systematic indictment of Christianity as the greatest curse on the human race, arguing that Christian morality is the morality of d\u00e9cadence: the glorification of weakness, the sanctification of suffering, and the war against every noble instinct.',
    summary: 'The Anti-Christ: A Curse on Christianity (Der Antichrist: Fluch auf das Christenthum), written in September 1888 in Turin and published posthumously in 1895 (Leipzig, Naumann; in volume VIII of the Gro\u00dfoktav edition), is the most sustained and most ferocious of Nietzsche\u2019s attacks on Christianity \u2014 a work of such concentrated fury that even sympathetic readers have found it difficult to separate the philosophical arguments from the polemical excess.\n\nNietzsche\u2019s thesis: Christianity is the greatest misfortune that has ever befallen the human race. It is the morality of d\u00e9cadence \u2014 the systematic glorification of everything that is weak, sick, and declining in human nature and the systematic war against everything that is strong, healthy, and life-affirming. Christianity did not merely oppose the ancient world\u2019s noble values (strength, beauty, courage, pride); it poisoned them at the root by making weakness a virtue, suffering a privilege, and self-denial the path to salvation.\n\nThe work\u2019s most philosophically important section is the analysis of Jesus himself (\u00a7\u00a728\u201335; KSA 6, 198\u2013207; A 27\u201334). Nietzsche distinguishes sharply between Jesus and Christianity. Jesus was not a theologian but a practitioner \u2014 a man who lived a certain way, whose \u201cgood news\u201d (Evangelium) was not a doctrine but a practice: the renunciation of resistance, the acceptance of suffering, the dissolution of the self in love. Jesus died as he lived \u2014 forgiving his enemies, refusing to resist. What came after \u2014 Paul\u2019s theology, the church, the doctrine of the resurrection, the concept of God as judge \u2014 is a systematic betrayal of Jesus by his own followers.\n\nPaul is the true founder of Christianity in Nietzsche\u2019s account (\u00a7\u00a742\u201345; KSA 6, 215\u2013220; A 39\u201342). Paul, the \u201cgenius of hatred,\u201d took Jesus\u2019s practice of self-dissolution and turned it into a theology of resentment: the doctrine of original sin, the resurrection as cosmic revenge, the church as an instrument of priestly power over the weak. Paul\u2019s Christianity is the slave revolt in morality carried to its logical conclusion.\n\nThe work ends with the \u201cLaw against Christianity\u201d (Gesetz wider das Christenthum; KSA 6, 254; A 67) \u2014 seven \u201cpropositions\u201d decreeing the condemnation of Christianity as the one great curse, the one great corruption, the one immortal blemish of the human race. The date is given as \u201cDay One of Year One\u201d \u2014 the first day of the new calendar that begins with the transvaluation of all values.',
    themes: ['the critique of Christianity', 'Christianity as d\u00e9cadence', 'Jesus vs Paul', 'the slave revolt in morality carried to completion', 'the priestly revaluation of values', 'the concept of God as enemy of life', 'pity as the practice of nihilism', 'the transvaluation of all values', 'the law against Christianity'],
    keyCharacters: [
        { name: 'Jesus', role: 'Distinguished by Nietzsche from Christianity: Jesus was a practitioner, not a theologian; his \u201cgood news\u201d was a way of living, not a doctrine; Christianity betrayed him' },
        { name: 'Paul', role: 'The \u201cgenius of hatred\u201d and the true founder of Christianity in Nietzsche\u2019s account: Paul transformed Jesus\u2019s practice into a theology of resentment and priestly power' }
    ],
    concepts: [
        'Christianity as d\u00e9cadence \u2014 the systematic glorification of weakness, sickness, and decline; the war against the noble instincts (\u00a7\u00a71\u20137; KSA 6, 169\u2013174; A 3\u20138)',
        'Jesus as practitioner \u2014 Jesus did not preach a doctrine but lived a practice: the renunciation of resistance, the dissolution of the self in love; his death was consistent with his life (\u00a7\u00a728\u201335; KSA 6, 198\u2013207; A 27\u201334)',
        'Paul as the founder of Christianity \u2014 Paul transformed Jesus\u2019s practice into a theology of resentment: original sin, resurrection, the church as priestly power (\u00a7\u00a742\u201345; KSA 6, 215\u2013220; A 39\u201342)',
        'Pity (Mitleid) as the practice of nihilism \u2014 pity preserves what should perish; it is the instrument by which d\u00e9cadence spreads (\u00a77; KSA 6, 173; A 7)',
        'The concept of God as enemy of life \u2014 the Christian God is a declaration of war against life, nature, and the will to live (\u00a718; KSA 6, 185; A 17)',
        'The transvaluation of all values (Umwerthung aller Werthe) \u2014 the reversal of the Christian revaluation; the restoration of the noble values that Christianity suppressed (\u00a762; KSA 6, 250; A 62)',
        'The Law against Christianity \u2014 seven propositions condemning Christianity as the one great curse on humanity; dated \u201cDay One of Year One\u201d (\u00a762 appendix; KSA 6, 254; A 67)'
    ],
    structure: '\u00a7\u00a71\u20137: The problem of d\u00e9cadence; pity as nihilism; Christianity as the religion of the weak\n\u00a7\u00a78\u201314: The concept of God; the Christian God vs the noble gods of antiquity\n\u00a7\u00a715\u201327: Buddhism as a more honest religion than Christianity; the contrast with Judaism\n\u00a7\u00a728\u201335: The psychology of Jesus; Jesus as practitioner, not theologian\n\u00a7\u00a736\u201341: The \u201cgood news\u201d and its betrayal; the church\u2019s falsification of Jesus\n\u00a7\u00a742\u201345: Paul as the genius of hatred; the founding of the church\n\u00a7\u00a746\u201361: Christianity\u2019s war against science, culture, and noble values\n\u00a762: The transvaluation of all values\nAppendix: The Law against Christianity \u2014 seven propositions',
    quote: 'I call Christianity the one great curse, the one great innermost corruption, the one great instinct of revenge, for which no means is poisonous, stealthy, subterranean, small enough \u2014 I call it the one immortal blemish of the human race.',
    additionalQuotes: [
        { text: 'The word \u201cChristianity\u201d is already a misunderstanding \u2014 in reality there has been only one Christian, and he died on the cross.', citation: '\u00a739; KSA 6, 211; A 36' },
        { text: 'The Christian concept of God \u2014 God as god of the sick, God as spider, God as spirit \u2014 is one of the most corrupt concepts of God arrived at on earth.', citation: '\u00a718; KSA 6, 185; A 17' },
        { text: 'What is good? Everything that heightens the feeling of power in man, the will to power, power itself. What is bad? Everything that is born of weakness.', citation: '\u00a72; KSA 6, 170; A 4' },
        { text: 'Buddhism is a hundred times more realistic than Christianity: it has the heritage of objectively and coolly posing problems in its constitution.', citation: '\u00a720; KSA 6, 186; A 19 (paraphrased)' }
    ],
    commentary: [
        { philosopher: 'Walter Kaufmann', text: 'Kaufmann\u2019s translation and commentary (in The Portable Nietzsche, 1954) argued that The Anti-Christ, despite its extreme rhetoric, contains genuine philosophical arguments: the distinction between Jesus and Paul, the analysis of Christianity as a form of ressentiment, and the critique of pity as nihilism are developments of positions first articulated in the Genealogy.' },
        { philosopher: 'Karl Jaspers', text: 'Jaspers\u2019s Nietzsche: An Introduction to the Understanding of His Philosophical Activity (1936; English 1965) argued that The Anti-Christ must be read in the context of Nietzsche\u2019s impending breakdown: the extremity of the rhetoric reflects not merely philosophical conviction but a mind approaching the limit of its coherence.' },
        { philosopher: 'Giani Vattimo', text: 'Vattimo\u2019s The End of Modernity (1985; English 1988) interprets The Anti-Christ not as a rejection of Christianity but as a radicalisation of it: Nietzsche\u2019s critique of the church is, paradoxically, a defence of the original Jesus against his own followers \u2014 a \u201csecular Christianity\u201d that preserves Jesus\u2019s practice while discarding Paul\u2019s theology.' },
        { philosopher: 'Aaron Ridley', text: 'Ridley\u2019s introduction to the Cambridge edition (2005) notes that The Anti-Christ is \u201csimultaneously Nietzsche\u2019s most offensive and most philosophically interesting late work: its distinction between Jesus and Christianity, its analysis of Paul as the inventor of bad conscience on a cosmic scale, and its account of pity as the mechanism of cultural decline are among the most provocative arguments in the history of the philosophy of religion.\u201d' }
    ],
    modernRelevance: 'The Anti-Christ remains the most radical philosophical critique of Christianity ever written. Its distinction between Jesus and Christianity has influenced the \u201chistorical Jesus\u201d movement in biblical scholarship. Its analysis of pity as nihilism has been discussed in connection with contemporary critiques of humanitarianism and the politics of compassion. Its account of Paul as the true founder of Christianity has been taken up by scholars of early Christianity (Hyam Maccoby, The Mythmaker, 1986). The concept of the transvaluation of all values continues to influence discussions of moral revolution, cultural renewal, and the possibility of a post-Christian ethics.',
    context: 'Written in September 1888 in Turin during the extraordinary final burst of productivity. Originally conceived as Book One of The Transvaluation of All Values (Umwerthung aller Werthe), a projected four-book work of which only The Anti-Christ was completed. Published posthumously in 1895 (Leipzig, Naumann), six years after Nietzsche\u2019s collapse. The text was edited by Nietzsche\u2019s sister Elisabeth F\u00f6rster-Nietzsche and Peter Gast, whose editorial interventions have been corrected in the KSA. Standard editions: KSA 6, 165\u2013254; A = Norman/Ridley (Cambridge, 2005); also Kaufmann (in The Portable Nietzsche, 1954).',
    relatedWorks: ['genealogy-of-morality', 'twilight-of-idols', 'ecce-homo', 'beyond-good-and-evil', 'zarathustra']
},

{
    id: 'ecce-homo',
    title: 'Ecce Homo: How One Becomes What One Is',
    greekTitle: 'Ecce homo: Wie man wird, was man ist',
    philosopher: 'nietzsche',
    category: 'method',
    categoryLabel: 'Philosophical Autobiography',
    date: '1908 AD',
    dateSort: 1888,
    emoji: '\uD83E\uDDD0',
    cardSize: 'normal',
    readingDifficulty: 'Beginner',
    estimatedWordCount: 30000,
    shortDesc: 'Nietzsche\u2019s philosophical autobiography \u2014 a work of astonishing brilliance and disturbing self-aggrandisement, written weeks before his mental collapse, in which he reviews his entire oeuvre and declares himself the most consequential philosopher in history.',
    summary: 'Ecce Homo: How One Becomes What One Is (Ecce homo: Wie man wird, was man ist), written between 15 October and 4 November 1888 in Turin and published in a limited edition in 1908 (Leipzig, Insel Verlag; full unexpurgated edition 1969), is Nietzsche\u2019s intellectual autobiography \u2014 a review of his entire philosophical career written at the height of his powers and within weeks of his mental collapse on 3 January 1889.\n\nThe work is divided into four sections with deliberately provocative titles: \u201cWhy I Am So Wise,\u201d \u201cWhy I Am So Clever,\u201d \u201cWhy I Write Such Good Books,\u201d and \u201cWhy I Am a Destiny.\u201d Each section combines genuine philosophical self-analysis with passages of grandiosity that have led many readers to detect the approaching madness.\n\n\u201cWhy I Am So Wise\u201d analyses Nietzsche\u2019s constitutive ambiguity: he is both a d\u00e9cadent and its opposite, both sick and healthy, both dying and more alive than anyone. This duality is the source of his philosophical insight: only someone who has experienced both sides of existence can see clearly.\n\n\u201cWhy I Am So Clever\u201d addresses the practical conditions of intellectual productivity: climate, diet, reading, recreation. Nietzsche insists that philosophy is a bodily affair: the thinker\u2019s body determines the quality of his thought.\n\n\u201cWhy I Write Such Good Books\u201d reviews each of Nietzsche\u2019s major works in turn, providing retrospective assessments that are often the most illuminating commentary on his own writings. The section on Zarathustra (\u201cI have given mankind the greatest gift it has ever been given\u201d; KSA 6, 259; EH Preface \u00a74) is the most extended and most revelatory.\n\n\u201cWhy I Am a Destiny\u201d is the climactic section. Nietzsche declares that he is \u201cdynamite\u201d (KSA 6, 365; EH \u201cWhy I Am a Destiny\u201d \u00a71), that the transvaluation of all values will split the history of mankind in two, and that the concept of God will be abolished. The section contains the most famous formulation of amor fati: \u201cMy formula for greatness in a human being is amor fati: that one wants nothing to be different, not forward, not backward, not in all eternity\u201d (KSA 6, 297; EH \u201cWhy I Am So Clever\u201d \u00a710).\n\nThe work\u2019s final sentence: \u201cHave I been understood? \u2014 Dionysus versus the Crucified\u201d (Hat man mich verstanden? \u2014 Dionysos gegen den Gekreuzigten; KSA 6, 374; EH \u201cWhy I Am a Destiny\u201d \u00a79).',
    themes: ['philosophical autobiography', 'how one becomes what one is', 'amor fati', 'the transvaluation of all values', 'Dionysus versus the Crucified', 'the body and philosophy', 'self-overcoming', 'the retrospective review of Nietzsche\u2019s works', 'grandeur and madness'],
    keyCharacters: [],
    concepts: [
        'Amor fati \u2014 the love of fate; the highest formula of affirmation: \u201cthat one wants nothing to be different, not forward, not backward, not in all eternity\u201d (KSA 6, 297; EH \u201cWhy I Am So Clever\u201d \u00a710)',
        'Dionysus versus the Crucified \u2014 the final opposition: the Dionysian affirmation of life against the Christian negation of life; the last sentence of the work (KSA 6, 374; EH \u201cWhy I Am a Destiny\u201d \u00a79)',
        'How one becomes what one is (Wie man wird, was man ist) \u2014 the subtitle\u2019s Pindaric injunction: self-realisation through the affirmation of one\u2019s own destiny; the unity of life and philosophy',
        'Philosophy as a bodily affair \u2014 climate, diet, health, recreation determine the quality of thought; the thinker\u2019s body is his primary instrument (KSA 6, 278\u2013297; EH \u201cWhy I Am So Clever\u201d)',
        'The d\u00e9cadent and his opposite \u2014 Nietzsche\u2019s constitutive duality: he is both sick and healthy, both declining and ascending; this duality is the source of his insight (KSA 6, 264\u2013268; EH \u201cWhy I Am So Wise\u201d \u00a71\u20132)',
        '\u201cI am dynamite\u201d \u2014 the declaration that the transvaluation of values will split history in two (KSA 6, 365; EH \u201cWhy I Am a Destiny\u201d \u00a71)',
        'The retrospective review \u2014 Nietzsche\u2019s self-commentary on each of his major works; often the most illuminating guide to his own intentions (KSA 6, 310\u2013360; EH \u201cWhy I Write Such Good Books\u201d)'
    ],
    structure: 'Preface: \u201cI have given mankind the greatest gift\u201d; the need for a self-presentation\n\nWhy I Am So Wise (\u00a7\u00a71\u20138)\n\u2014 The d\u00e9cadent and his opposite; illness and health; the instinct of self-preservation\n\nWhy I Am So Clever (\u00a7\u00a71\u201310)\n\u2014 Climate, nutrition, recreation; the art of choosing one\u2019s enemies\n\u2014 \u00a710: Amor fati\n\nWhy I Write Such Good Books (\u00a7\u00a71\u20136; plus sections on individual works)\n\u2014 The Birth of Tragedy; Untimely Meditations; Human, All Too Human\n\u2014 Daybreak; The Gay Science; Thus Spoke Zarathustra\n\u2014 Beyond Good and Evil; Genealogy of Morals; Twilight; The Case of Wagner\n\nWhy I Am a Destiny (\u00a7\u00a71\u20139)\n\u2014 I am dynamite; the transvaluation of all values\n\u2014 Dionysus versus the Crucified',
    quote: 'My formula for greatness in a human being is amor fati: that one wants nothing to be different, not forward, not backward, not in all eternity. Not merely bear what is necessary, still less conceal it \u2014 all idealism is mendacity in the face of what is necessary \u2014 but love it.',
    additionalQuotes: [
        { text: 'I am not a man, I am dynamite.', citation: 'KSA 6, 365; EH \u201cWhy I Am a Destiny\u201d \u00a71' },
        { text: 'Have I been understood? \u2014 Dionysus versus the Crucified.', citation: 'KSA 6, 374; EH \u201cWhy I Am a Destiny\u201d \u00a79 (final sentence)' },
        { text: 'Among my writings my Zarathustra stands by itself. With this work I have given mankind the greatest gift it has ever been given.', citation: 'KSA 6, 259; EH Preface \u00a74' },
        { text: 'I know my fate. One day my name will be associated with the memory of something tremendous \u2014 a crisis without equal on earth, the most profound collision of conscience, a decision invoked against everything that had been believed, demanded, hallowed so far.', citation: 'KSA 6, 365; EH \u201cWhy I Am a Destiny\u201d \u00a71' },
        { text: 'I am a disciple of the philosopher Dionysus; I would rather be a satyr than a saint.', citation: 'KSA 6, 258; EH Preface \u00a72' }
    ],
    commentary: [
        { philosopher: 'Jacques Derrida', text: 'Derrida\u2019s The Ear of the Other (1982; English 1985) and Otobiographies (1984) take Ecce Homo as the paradigmatic text of philosophical autobiography: the impossibility of separating the life from the work, the author from the text, the performative from the constative. The question \u201cHave I been understood?\u201d is, for Derrida, the exemplary philosophical question: it cannot be answered, because understanding always arrives too late.' },
        { philosopher: 'Alexander Nehamas', text: 'Nehamas (1985) interprets Ecce Homo as the culmination of Nietzsche\u2019s project of \u201clife as literature\u201d: the philosopher\u2019s life is his greatest work of art, and Ecce Homo is the retrospective narrative that gives that life its form and meaning.' },
        { philosopher: 'R\u00fcdiger Safranski', text: 'Safranski\u2019s biography (2000; English 2002) provides the most balanced assessment of Ecce Homo\u2019s relationship to Nietzsche\u2019s impending collapse: the work is simultaneously the most lucid and the most deranged of his writings, and the question of where lucidity ends and madness begins cannot be definitively answered.' },
        { philosopher: 'Aaron Ridley', text: 'Ridley (Cambridge 2005) argues that Ecce Homo\u2019s self-commentary on the earlier works is philosophically indispensable: \u201cNietzsche\u2019s retrospective assessments are often more illuminating than any secondary literature, because he understood his own project with a clarity no commentator has matched.\u201d' }
    ],
    modernRelevance: 'Ecce Homo has become central to discussions of philosophical autobiography, the relationship between life and philosophy, and the performative dimension of philosophical writing. Derrida\u2019s engagement has made it a foundational text of deconstruction. Nehamas\u2019s \u201clife as literature\u201d thesis has made it central to existentialist and aesthetic approaches to philosophy. The concept of amor fati \u2014 the love of fate, the unconditional affirmation of one\u2019s own existence \u2014 has become one of the most widely cited philosophical concepts in contemporary popular culture, self-help literature, and the art of living.',
    context: 'Written between 15 October and 4 November 1888 in Turin. Nietzsche\u2019s mental collapse occurred on 3 January 1889. The work was withheld from publication by Elisabeth F\u00f6rster-Nietzsche, who regarded its content as embarrassing. A partial edition appeared in 1908 (Insel Verlag, Leipzig); the full unexpurgated text was published only in 1969 (KSA). The question of whether the work\u2019s grandiosity reflects philosophical conviction or incipient madness has been debated since its first appearance. Standard editions: KSA 6, 255\u2013374; EH = Norman/Ridley (Cambridge, 2005); also Kaufmann (Vintage, 1967).',
    relatedWorks: ['anti-christ', 'twilight-of-idols', 'zarathustra', 'genealogy-of-morality', 'gay-science']
}

);
