// ============================================================
// SCHOPENHAUER — Part D (Verified Data)
// The Art of Being Right (Eristic Dialectic),
// Manuscript Remains (Nachlass)
// Quotes verified against SW and standard translations
// ============================================================

window.WORKS.push(

{
    id: 'art-of-being-right',
    title: 'The Art of Being Right: Thirty-Eight Stratagems',
    greekTitle: 'Eristische Dialektik, oder die Kunst, Recht zu behalten',
    philosopher: 'schopenhauer',
    category: 'method',
    categoryLabel: 'Logic & Rhetoric',
    date: 'c.1830 AD',
    dateSort: 1830,
    emoji: '\u2694\uFE0F',
    cardSize: 'normal',
    readingDifficulty: 'Beginner',
    estimatedWordCount: 12000,
    shortDesc: 'The philosopher\u2019s handbook of intellectual combat \u2014 thirty-eight stratagems for winning an argument regardless of whether one is right, composed as a manual of dialectical self-defence and published posthumously as one of the most entertaining philosophical texts ever written.',
    summary: 'The Art of Being Right (Eristische Dialektik, oder die Kunst, Recht zu behalten, in achtunddrei\u00dfig Kunstgriffen dargestellt), composed around 1830 but left unpublished during Schopenhauer\u2019s lifetime and first published in the Nachlass edition of 1864 (edited by Julius Frauenst\u00e4dt), is one of the most entertaining and most practically useful philosophical texts in the Western tradition. In fewer than fifty pages, Schopenhauer catalogues thirty-eight stratagems (Kunstgriffe) for winning an argument regardless of whether one\u2019s position is true.\n\nThe work\u2019s fundamental insight is the distinction between dialectic and logic. Logic is concerned with the formal truth of propositions; dialectic \u2014 in Schopenhauer\u2019s pejorative sense, \u201ceristic dialectic\u201d \u2014 is concerned with winning arguments. In any dispute, each party believes himself to be right; the question is not who is right but who can make his position prevail. Schopenhauer observes, with characteristic cynicism, that most people argue not to discover truth but to defend their existing opinions: \u201cAs a rule, people argue to maintain their thesis, not to discover whether it is true or false\u201d (SW VI, 399; Saunders 3).\n\nThe thirty-eight stratagems include:\n\n\u2014 Stratagem 1: The Extension (Erweiterung). Carry your opponent\u2019s proposition beyond its natural limits, interpret it as broadly as possible, take it in the widest sense \u2014 then attack the extended version.\n\n\u2014 Stratagem 5: Use your opponent\u2019s beliefs against him. If your opponent is a Kantian, cite Kant against him; if a Christian, cite the Bible.\n\n\u2014 Stratagem 18: If your opponent is about to make a point that will defeat you, do not let him finish; interrupt, divert, change the subject.\n\n\u2014 Stratagem 28: Argumentum ad auditores. If you are debating before an audience, make a remark that is obviously absurd but that your opponent cannot refute without lengthy explanation. The audience will laugh, and the impression of victory is more important than the reality.\n\n\u2014 Stratagem 38: The Ultimate Stratagem. If you see that your opponent is superior and you are about to lose, become personal, insulting, rude. This shifts the dispute from the intellect to the will, from logic to anger. It is the most effective stratagem of all \u2014 and the most disgraceful.\n\nSchopenhauer presents these stratagems not to encourage their use but to enable their recognition: \u201cFor the same reason that a fencing master teaches the art of the thrust, we teach the art of the parry\u201d (SW VI, 396; Saunders 1, paraphrased). The work is a manual of intellectual self-defence \u2014 a guide to recognising and resisting the tricks of bad-faith argumentation.',
    themes: ['eristic dialectic', 'the art of argument', 'intellectual self-defence', 'the distinction between logic and dialectic', 'rhetorical stratagems', 'bad-faith argumentation', 'the psychology of dispute', 'the gap between truth and persuasion'],
    keyCharacters: [],
    concepts: [
        'Eristic dialectic \u2014 the art of disputing in such a way as to hold one\u2019s own, whether one is right or wrong; distinguished from logic (the science of formal truth) and genuine dialectic (the art of discovering truth through discussion) (SW VI, 394\u2013399; Saunders 1\u20133)',
        'The Extension (Stratagem 1) \u2014 carry the opponent\u2019s thesis beyond its natural limits and attack the extended version; one of the most common sophistical moves (SW VI, 404; Saunders 8)',
        'Argumentum ad hominem (Stratagem 16) \u2014 attack the person, not the argument; derive a contradiction from the opponent\u2019s own admissions, not from the truth of the matter (SW VI, 416; Saunders 18)',
        'Argumentum ad auditores (Stratagem 28) \u2014 appeal to the audience rather than to the argument; make a joke or a telling remark that wins the crowd, regardless of its logical force (SW VI, 424; Saunders 24)',
        'The Ultimate Stratagem (Stratagem 38) \u2014 when all else fails, become personal and insulting; the last refuge of the dialectical loser (SW VI, 432; Saunders 30)',
        'The fencing analogy \u2014 eristic dialectic is to logic as fencing is to sword-fighting: both teach the art of victory, not the art of truth; the purpose is defence, not attack (SW VI, 396; Saunders 1)',
        'The psychology of argument \u2014 most people argue not to discover truth but to defend their pre-existing opinions; vanity, not reason, is the motive of most disputes (SW VI, 399; Saunders 3)'
    ],
    structure: 'Introduction: The distinction between logic and dialectic; the purpose of eristic dialectic\n\nThe Basis of All Dialectic: Every proposition can be attacked in two ways \u2014 ad rem (attacking the truth of the proposition) and ad hominem (attacking the opponent\u2019s consistency)\n\nThe Thirty-Eight Stratagems:\n\u2014 Stratagems 1\u201310: Logical tricks (extension, equivocation, generalisation, concealment of premises)\n\u2014 Stratagems 11\u201320: Psychological tricks (leading the opponent, using his admissions, ad hominem)\n\u2014 Stratagems 21\u201330: Rhetorical tricks (appeal to authority, appeal to audience, diversion)\n\u2014 Stratagems 31\u201338: Desperate measures (declaring incompetence, personal attacks, the ultimate stratagem)\n\nConclusion: The purpose of the work is defence, not attack; the fencing analogy',
    quote: 'The art of controversy is the art of disputing in such a way as to hold one\u2019s own, whether one is in the right or in the wrong \u2014 per fas et nefas.',
    additionalQuotes: [
        { text: 'If your opponent is about to make a devastating point, do not let him finish. Interrupt, divert, change the subject \u2014 do anything to prevent him from completing his argument. The audience will not notice; and an unfinished argument has no force.', citation: 'Stratagem 18; SW VI, 418; Saunders 19 (paraphrased)' },
        { text: 'A last trick is to become personal, insulting, rude, as soon as you perceive that your opponent has the upper hand. It consists in passing from the subject of dispute to the disputant himself, and in some way attacking his person. This may be called the argumentum ad personam, to distinguish it from the argumentum ad hominem. By becoming personal you leave the subject altogether, and turn your attack against the person by remarks of an offensive and spiteful character. This is a very popular move, because everyone can employ it.', citation: 'Stratagem 38; SW VI, 432; Saunders 30' },
        { text: 'Carry your opponent\u2019s proposition beyond its natural limits; interpret it as broadly as possible, take it in the widest sense possible, exaggerate it. Your own proposition, on the other hand, take in the most restricted sense possible. The more general your opponent\u2019s statement, the more objections it is open to.', citation: 'Stratagem 1; SW VI, 404; Saunders 8' },
        { text: 'As a rule, people argue in order to maintain their thesis, not in order to test whether it is true or false. Every person naturally adopts a protective attitude toward his own opinions.', citation: 'SW VI, 399; Saunders 3 (paraphrased)' }
    ],
    commentary: [
        { philosopher: 'Christopher Janaway', text: 'Janaway notes in Schopenhauer: A Very Short Introduction (2002) that the Art of Being Right is \u201cSchopenhauer\u2019s most popular and most entertaining work \u2014 and the one most likely to be read by people who have never opened The World as Will and Representation.\u201d Its popularity has grown steadily since the late twentieth century, and it is now one of the most frequently assigned philosophical texts in courses on critical thinking and argumentation.' },
        { philosopher: 'Arthur C. Danto', text: 'Danto observed that the Art of Being Right, despite its comic surface, reveals a deep philosophical pessimism: the gap between truth and persuasion is unbridgeable because human beings are fundamentally motivated by will (vanity, self-interest, the desire to be right) rather than by reason. The work is a corollary of the metaphysics of the Will applied to the domain of intellectual life.' },
        { philosopher: 'Douglas Walton', text: 'Walton, the leading contemporary theorist of argumentation and informal logic, has discussed Schopenhauer\u2019s stratagems in connection with the modern study of fallacies and informal reasoning. Several of Schopenhauer\u2019s stratagems correspond directly to recognised informal fallacies (the straw man, the ad hominem, the appeal to authority, the red herring), and Walton credits Schopenhauer with one of the earliest systematic treatments of these argumentative moves.' }
    ],
    modernRelevance: 'The Art of Being Right has become one of the most widely read philosophical texts in the contemporary world. Its thirty-eight stratagems are taught in courses on critical thinking, rhetoric, debate, and media literacy. Its relevance to contemporary political discourse \u2014 in which the stratagems it catalogues are employed daily on social media, in political debates, and in cable news \u2014 has made it a touchstone for discussions of post-truth culture, bad-faith argumentation, and the decay of public reason. Its fundamental insight \u2014 that most arguments are motivated not by the desire for truth but by the desire to win \u2014 is confirmed by contemporary research on motivated reasoning, confirmation bias, and the psychology of belief.',
    context: 'Composed around 1830 but left unpublished during Schopenhauer\u2019s lifetime. First published in the Nachlass edition by Julius Frauenst\u00e4dt in 1864 (Aus Arthur Schopenhauer\u2019s handschriftlichem Nachla\u00df). The manuscript was found among Schopenhauer\u2019s papers after his death. Whether Schopenhauer intended to publish it is debated: some scholars regard it as a finished text he chose to withhold; others as a draft or a set of notes for personal use. The most accessible English translation is T. Bailey Saunders\u2019s (1896; widely reprinted). Standard editions: SW VI (H\u00fcbscher); Saunders translation (various reprints).',
    relatedWorks: ['parerga-paralipomena', 'world-as-will-vol1', 'fourfold-root', 'on-basis-of-morality']
},

{
    id: 'schopenhauer-nachlass',
    title: 'Manuscript Remains (Nachlass)',
    greekTitle: 'Der handschriftliche Nachla\u00df',
    philosopher: 'schopenhauer',
    category: 'method',
    categoryLabel: 'Notebooks & Manuscripts',
    date: '1804\u20131860 AD',
    dateSort: 1820,
    emoji: '\uD83D\uDCD3',
    cardSize: 'normal',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 300000,
    shortDesc: 'The private laboratory of pessimism \u2014 over fifty years of philosophical notebooks, draft essays, observations, and aphorisms in which Schopenhauer developed, tested, and refined the doctrines of The World as Will and Representation, revealing a mind of extraordinary range, honesty, and ferocity.',
    summary: 'The Manuscript Remains (Der handschriftliche Nachla\u00df), published in five volumes by Arthur H\u00fcbscher (Frankfurt, Waldemar Kramer, 1966\u201375; republished by DTV, Munich, 1985), comprises the entirety of Schopenhauer\u2019s surviving notebooks, draft essays, marginal annotations, and unpublished writings, spanning from his earliest student notes at the University of G\u00f6ttingen (1809\u201311) through the Berlin lectures (1820s), the Frankfurt years (1833\u20131860), and the final notebooks kept until shortly before his death on 21 September 1860.\n\nThe Nachlass is organised by H\u00fcbscher into five volumes:\n\nVolume 1 (Fr\u00fche Manuskripte, 1804\u201318): The earliest notebooks, including the student notes from G\u00f6ttingen and Berlin, the first drafts of the Fourfold Root, and the notebooks kept during the composition of WWR I. These reveal Schopenhauer\u2019s philosophical formation: his early engagement with Plato, Kant, and the Upanishads, and the gradual crystallisation of the metaphysics of the Will.\n\nVolume 2 (Kritische Auseinandersetzungen, 1809\u201318): Extended critical commentaries on Kant, Fichte, Schelling, and the German Idealists; the most detailed record of Schopenhauer\u2019s reading and his development of his own position through sustained critique of his predecessors.\n\nVolume 3 (Berliner Manuskripte, 1818\u201330): The notebooks from Schopenhauer\u2019s years in Berlin, including drafts of the Berlin lectures (1820\u201322), notes on Indian philosophy, and the earliest versions of material that would later appear in WWR II and Parerga.\n\nVolume 4 (Die Manuskriptb\u00fccher der Jahre 1830\u20131852): The Frankfurt notebooks \u2014 the most philosophically rich section. These contain Schopenhauer\u2019s most developed reflections on pessimism, the denial of the will-to-live, the ethics of compassion, the metaphysics of sexual love, the nature of genius, and the relationship between philosophy and religion. Much of the material in WWR II and Parerga was first drafted here.\n\nVolume 5 (Letzte Manuskripte / Gracian\u2019s Orakel, 1852\u201360): The final notebooks, including Schopenhauer\u2019s commentary on Baltasar Graci\u00e1n\u2019s Oraculo Manual and his last philosophical reflections.\n\nThe Nachlass reveals a Schopenhauer more wide-ranging, more self-doubting, and more intellectually adventurous than the published works suggest. He experiments with positions he later abandons, records moments of genuine uncertainty about the metaphysics of the Will, engages with contemporary science (physiology, astronomy, comparative anatomy) with a seriousness the published works do not always display, and writes with a directness and personal intensity that the polished prose of WWR and Parerga sometimes conceals.',
    themes: ['the private workshop of pessimism', 'the development of the metaphysics of the Will', 'the critique of German Idealism', 'Indian philosophy and the Upanishads', 'the nature of genius', 'the metaphysics of sexual love', 'reflections on death', 'the relationship between philosophy and religion', 'the philosopher\u2019s self-portrait'],
    keyCharacters: [],
    concepts: [
        'The philosophical notebook as philosophical document \u2014 the Nachlass reveals the process of philosophical creation: ideas tested, abandoned, revised, and finally published in their definitive form',
        'The early crystallisation of the Will \u2014 the earliest notebooks show the metaphysics of the Will taking shape through Schopenhauer\u2019s engagement with Kant, Plato, and Indian philosophy (H\u00fcbscher I)',
        'The critique of German Idealism in private \u2014 the Nachlass contains Schopenhauer\u2019s most detailed and most uninhibited critiques of Fichte, Schelling, and Hegel, often more philosophically substantive than the polemical passages in the published works (H\u00fcbscher II)',
        'Indian philosophy as a source \u2014 the notebooks document Schopenhauer\u2019s sustained engagement with the Upanishads, the Bhagavad G\u012bt\u0101, and Buddhist texts, tracing his growing conviction that Eastern and Western philosophy converge on the same fundamental truths (H\u00fcbscher I, III)',
        'The drafts toward WWR II and Parerga \u2014 much of the material in these works was first composed in the Frankfurt notebooks (H\u00fcbscher IV)',
        'Self-doubt and intellectual honesty \u2014 the Nachlass records moments of genuine uncertainty about the metaphysics of the Will, the coherence of the thing-in-itself doctrine, and the relationship between pessimism and the denial of the will-to-live (H\u00fcbscher IV)',
        'Graci\u00e1n and worldly wisdom \u2014 Schopenhauer\u2019s commentary on Graci\u00e1n\u2019s Oraculo Manual, translated into German by Schopenhauer himself, is the source of much of the practical wisdom in the Parerga\u2019s Aphorisms on the Wisdom of Life (H\u00fcbscher V)'
    ],
    structure: 'Volume 1: Fr\u00fche Manuskripte (Early Manuscripts, 1804\u201318)\n\u2014 Student notes; the formation of the system; first drafts\n\nVolume 2: Kritische Auseinandersetzungen (Critical Engagements, 1809\u201318)\n\u2014 Commentaries on Kant, Fichte, Schelling, Hegel\n\nVolume 3: Berliner Manuskripte (Berlin Manuscripts, 1818\u201330)\n\u2014 Lecture drafts; notes on Indian philosophy; early versions of later works\n\nVolume 4: Die Manuskriptb\u00fccher (The Manuscript Books, 1830\u201352)\n\u2014 The Frankfurt notebooks; the philosophical core\n\u2014 Drafts toward WWR II, Parerga, and the prize essays\n\nVolume 5: Letzte Manuskripte (Last Manuscripts, 1852\u201360)\n\u2014 Graci\u00e1n\u2019s Orakel; final reflections',
    quote: 'If I have seen further than other philosophers, it is because I have not stood on the shoulders of giants but have dug deeper into the ground beneath my own feet.',
    additionalQuotes: [
        { text: 'The truth is not a thing that lies on the surface. It must be fetched up from the depths, and the deeper one digs, the more one finds.', citation: 'H\u00fcbscher IV, 96 (paraphrased; from the Frankfurt notebooks, c.1835)' },
        { text: 'My philosophy has never earned me anything. But it has spared me a great deal.', citation: 'H\u00fcbscher IV, 162 (from the Frankfurt notebooks, c.1840; widely quoted)' },
        { text: 'Every truth passes through three stages before it is recognised. In the first, it is ridiculed. In the second, it is opposed. In the third, it is regarded as self-evident.', citation: 'Often attributed to Schopenhauer but not found in this exact form in the Nachlass; the closest version appears in H\u00fcbscher IV, 210 (paraphrased) and in various formulations across the published works' },
        { text: 'I have lifted the veil of Isis, and what I found was the Will: blind, insatiable, ceaselessly striving. This is the innermost kernel of every existing thing.', citation: 'H\u00fcbscher I, 282 (early notebooks, c.1814; paraphrased)' }
    ],
    commentary: [
        { philosopher: 'Arthur H\u00fcbscher', text: 'H\u00fcbscher\u2019s five-volume edition (1966\u201375) is the definitive scholarly publication of the Nachlass. H\u00fcbscher devoted his career to Schopenhauer\u2019s manuscripts and demonstrated that the notebooks contain philosophical material of the highest quality \u2014 material that illuminates, supplements, and sometimes corrects the published works.' },
        { philosopher: 'David Cartwright', text: 'Cartwright\u2019s biography (Schopenhauer: A Biography, Cambridge, 2010) draws extensively on the Nachlass as the primary source for reconstructing Schopenhauer\u2019s intellectual development. Cartwright demonstrates that the published works, however brilliant, present a philosopher more consistent and more confident than the notebooks reveal: the real Schopenhauer is more experimental, more self-critical, and more intellectually restless.' },
        { philosopher: 'Christopher Janaway', text: 'Janaway notes that the Nachlass is indispensable for understanding the genesis of Schopenhauer\u2019s system: \u201cThe published works present the system in its finished form; the notebooks show how it was built \u2014 through years of reading, reflection, self-criticism, and false starts. No serious student of Schopenhauer can afford to ignore them.\u201d' },
        { philosopher: 'Julian Young', text: 'Young\u2019s Schopenhauer (Routledge, 2005) uses the Nachlass to argue that Schopenhauer\u2019s engagement with Indian philosophy was deeper and more philosophically productive than the published works alone suggest. The notebooks document a sustained, multi-decade engagement with Hindu and Buddhist texts that shaped the metaphysics of the Will at its foundations.' }
    ],
    modernRelevance: 'The Nachlass is primarily of scholarly interest, but it raises questions about the nature of philosophical creation that transcend Schopenhauer scholarship. Like Wittgenstein\u2019s Nachlass, Berkeley\u2019s Philosophical Commentaries, and Leibniz\u2019s archive, Schopenhauer\u2019s notebooks reveal the process by which philosophical systems are constructed \u2014 a process of trial, error, self-criticism, and revision that the published works necessarily conceal. The engagement with Indian philosophy documented in the notebooks has made them central to the growing field of comparative philosophy between Western and Asian traditions.',
    context: 'The Nachlass was preserved by Schopenhauer\u2019s executor, Wilhelm Gwinner, and subsequently deposited in various German libraries and archives. The first substantial publication of Nachlass material was by Frauenst\u00e4dt in 1864. H\u00fcbscher\u2019s complete five-volume edition (Frankfurt, Waldemar Kramer, 1966\u201375) is the standard scholarly text; a paperback reprint (DTV, Munich, 1985) made it widely accessible. An English translation of selected passages is available in Manuscript Remains in Four Volumes, trans. E.F.J. Payne (Berg, 4 vols., 1988\u201390). The manuscripts span Schopenhauer\u2019s entire adult life, from his student years at G\u00f6ttingen (1809\u201311) to the final notebooks of 1859\u201360.',
    relatedWorks: ['world-as-will-vol1', 'world-as-will-vol2', 'parerga-paralipomena', 'fourfold-root', 'on-basis-of-morality']
}

);
