// ============================================================
// HEGEL — Part A (Verified Data)
// Phenomenology of Spirit, Science of Logic, Encyclopedia
// Quotes verified against GW, W, M/PM, GL, EL editions
// ============================================================

window.WORKS.push(

{
    id: 'phenomenology-of-spirit',
    title: 'Phenomenology of Spirit',
    greekTitle: 'Ph\u00e4nomenologie des Geistes',
    philosopher: 'hegel',
    category: 'metaphysics',
    categoryLabel: 'Metaphysics & Epistemology',
    date: '1807 AD',
    dateSort: 1807,
    emoji: '\uD83C\uDF00',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 180000,
    shortDesc: 'The most extraordinary philosophical narrative ever written \u2014 Hegel\u2019s account of consciousness\u2019s journey from naive sense-certainty through self-consciousness, reason, spirit, and religion to absolute knowledge, containing the master-slave dialectic and the most ambitious theory of human experience in the Western tradition.',
    summary: 'The Phenomenology of Spirit (Ph\u00e4nomenologie des Geistes), published in Bamberg by Joseph Anton Goebhardt in 1807, is one of the most ambitious, most difficult, and most influential philosophical works ever written. Completed in Jena in October 1806 as Napoleon\u2019s troops occupied the city after the battle of Jena-Auerstedt (14 October 1806), it traces the development of consciousness from its most immediate and impoverished form \u2014 sense-certainty, the mere \u201cthis\u201d and \u201cnow\u201d \u2014 through an ascending sequence of shapes (Gestalten) to the standpoint of absolute knowledge, in which Spirit (Geist) fully comprehends itself and its world.\n\nThe work proceeds through several major divisions. Consciousness (sense-certainty, perception, understanding) shows how the attempt to grasp the object immediately leads to ever more complex mediations. Self-Consciousness introduces the master-slave dialectic (\u00a7\u00a7178\u2013196; M 111\u2013119; PM 109\u2013116) \u2014 the most famous passage in the entire Hegelian corpus \u2014 in which two self-consciousnesses engage in a \u201clife-and-death struggle\u201d for recognition, resulting in the asymmetric relation of lord and bondsman. The bondsman, through the discipline of labour, achieves a higher form of self-consciousness than the lord who merely consumes. This section has generated an entire tradition of political and social philosophy, from Marx (alienated labour) through Koj\u00e8ve (the end of history) to Fanon (colonial consciousness) and Honneth (recognition theory).\n\nReason traces the development of rational consciousness through observing reason, active reason, and legislative reason. Spirit (Geist) \u2014 the longest section \u2014 traces the development of ethical life through the ancient Greek polis, the Roman legal order, the Enlightenment, the French Revolution (which Hegel interprets as \u201cabsolute freedom and terror\u201d: the attempt to realise abstract freedom directly, without institutional mediation, resulting in the Terror), and morality (Kant and Fichte). Religion traces the development of religious consciousness from natural religion through art-religion (Greek tragedy) to revealed religion (Christianity). Absolute Knowledge is the concluding chapter in which Spirit comprehends its entire history as the progressive self-revelation of the Absolute.\n\nThe Preface \u2014 written last, after the rest of the work was completed \u2014 contains some of Hegel\u2019s most famous formulations, including the claim that \u201cthe True is the whole\u201d (das Wahre ist das Ganze; \u00a720; M 11; PM 15), the critique of Schelling\u2019s Absolute as \u201cthe night in which all cows are black\u201d (\u00a716; M 9; PM 13), and the programme of philosophy as \u201cthe science of the experience of consciousness.\u201d',
    themes: ['the dialectic of consciousness', 'the master-slave dialectic', 'recognition', 'Spirit and its shapes', 'absolute knowledge', 'the French Revolution as absolute freedom and terror', 'the True is the whole', 'the experience of consciousness', 'Bildung', 'the unhappy consciousness'],
    keyCharacters: [],
    concepts: [
        'Sense-certainty (sinnliche Gewi\u00dfheit) \u2014 the most immediate form of consciousness: the bare awareness of \u201cthis\u201d and \u201cnow\u201d; shown to be the poorest, not the richest, form of knowledge (\u00a7\u00a790\u2013110; M 58\u201366; PM 58\u201365)',
        'The master-slave dialectic (Herrschaft und Knechtschaft) \u2014 two self-consciousnesses engage in a life-and-death struggle for recognition; the bondsman, through labour, achieves a higher self-consciousness than the lord (\u00a7\u00a7178\u2013196; M 111\u2013119; PM 109\u2013116)',
        'Recognition (Anerkennung) \u2014 self-consciousness requires the recognition of another self-consciousness; the structure of recognition is the foundation of all social relations (\u00a7\u00a7178\u2013184; M 111\u2013114; PM 109\u2013112)',
        'The unhappy consciousness (das ungl\u00fcckliche Bewu\u00dftsein) \u2014 the consciousness divided against itself: longing for an infinite being it can never reach; the phenomenological form of medieval religiosity (\u00a7\u00a7207\u2013230; M 126\u2013138; PM 123\u2013135)',
        'Spirit (Geist) \u2014 not individual mind but the totality of a culture\u2019s shared forms of life: institutions, practices, norms, and self-understanding (\u00a7\u00a7438\u2013671; M 263\u2013409; PM 256\u2013399)',
        'Absolute freedom and terror \u2014 the French Revolution as the attempt to realise abstract freedom directly, without institutional mediation; the result is the Terror (\u00a7\u00a7582\u2013595; M 355\u2013363; PM 349\u2013356)',
        'The True is the whole (das Wahre ist das Ganze) \u2014 truth is not a fixed proposition but the entire process of its development; the whole is the result together with its becoming (\u00a720; M 11; PM 15)',
        'Aufhebung (sublation) \u2014 the dialectical movement of simultaneously cancelling, preserving, and raising to a higher level; the fundamental operation of Hegel\u2019s logic',
        'Bildung \u2014 the formation or cultivation of Spirit through its successive shapes; the process by which consciousness becomes what it is',
        'Absolute knowledge (absolutes Wissen) \u2014 the standpoint at which Spirit comprehends its entire history as the self-revelation of the Absolute (\u00a7\u00a7788\u2013808; M 479\u2013493; PM 466\u2013480)'
    ],
    structure: 'Preface: The programme of the Phenomenology; \u201cthe True is the whole\u201d; the critique of Schelling\nIntroduction: The concept of the experience of consciousness\n\nA. Consciousness\n\u2014 Sense-certainty; Perception; Understanding\n\nB. Self-Consciousness\n\u2014 The life-and-death struggle; the master-slave dialectic\n\u2014 Stoicism, Skepticism, the Unhappy Consciousness\n\nC(AA). Reason\n\u2014 Observing Reason; Active Reason; Legislative Reason\n\nC(BB). Spirit\n\u2014 The ethical world (the Greek polis); Culture and the Enlightenment\n\u2014 Absolute freedom and terror (the French Revolution); Morality (Kant/Fichte)\n\nC(CC). Religion\n\u2014 Natural religion; Art-religion; Revealed religion\n\nC(DD). Absolute Knowledge',
    quote: 'The True is the whole. But the whole is nothing other than the essence consummating itself through its development.',
    additionalQuotes: [
        { text: 'To judge a thing that has substance and solid worth is quite easy, to comprehend it is much harder, and to blend judgment and comprehension in a definitive description is the hardest thing of all.', citation: 'Preface \u00a73; M 1\u20132; PM 3\u20134' },
        { text: 'With the absolute, as we said, it would be the night in which, as the saying goes, all cows are black. That is the na\u00efvet\u00e9 of emptiness in cognition.', citation: 'Preface \u00a716; M 9; PM 13 (the critique of Schelling)' },
        { text: 'Self-consciousness exists in and for itself when and by the fact that it exists for another; that is, it exists only as recognised.', citation: '\u00a7178; M 111; PM 109' },
        { text: 'The life of Spirit is not the life that shrinks from death and keeps itself untouched by devastation, but rather the life that endures it and maintains itself in it.', citation: 'Preface \u00a732; M 19; PM 21' },
        { text: 'The owl of Minerva begins its flight only with the falling of dusk.', citation: 'Not from the Phenomenology but from the Philosophy of Right Preface (W 7, 28; PR 23); frequently misattributed to the Phenomenology' }
    ],
    commentary: [
        { philosopher: 'Alexandre Koj\u00e8ve', text: 'Koj\u00e8ve\u2019s Introduction to the Reading of Hegel (lectures 1933\u201339; published 1947) reinterpreted the master-slave dialectic as the key to the entire Phenomenology and, through it, to the meaning of human history. Koj\u00e8ve argued that history is the history of the struggle for recognition, and that history \u201cends\u201d when mutual recognition is achieved in the universal and homogeneous state. His reading influenced Sartre, Merleau-Ponty, Lacan, and Fukuyama.' },
        { philosopher: 'Karl Marx', text: 'Marx\u2019s Economic and Philosophical Manuscripts (1844) acknowledged the Phenomenology as the \u201ctrue birthplace and secret of Hegel\u2019s philosophy.\u201d Marx adopted the master-slave dialectic as the model for his theory of alienated labour: the worker, like Hegel\u2019s bondsman, achieves consciousness through the discipline of labour but is alienated from the product of that labour.' },
        { philosopher: 'Martin Heidegger', text: 'Heidegger\u2019s Hegel\u2019s Phenomenology of Spirit (lectures 1930\u201331; published 1980) interpreted the Phenomenology as an ontological work: not merely a theory of consciousness but an inquiry into the being of beings. Heidegger argued that Hegel\u2019s concept of experience (Erfahrung) is the movement by which consciousness discovers that its object is not what it took it to be \u2014 and thereby transforms itself.' },
        { philosopher: 'Terry Pinkard', text: 'Pinkard\u2019s Hegel\u2019s Phenomenology: The Sociality of Reason (1994) interprets the Phenomenology as a social epistemology: each shape of consciousness is a form of social practice, and the transitions between shapes are driven by the internal inadequacy of each practice\u2019s self-understanding. Pinkard\u2019s 2018 translation (Cambridge) is the most recent complete English version.' },
        { philosopher: 'Robert Pippin', text: 'Pippin\u2019s Hegel\u2019s Idealism (1989) argues that the Phenomenology completes the project of Kantian epistemology by showing that the categories through which we constitute experience are not fixed a priori but develop historically through the dialectical process Hegel traces.' }
    ],
    modernRelevance: 'The Phenomenology remains one of the most actively studied and most fiercely debated texts in philosophy. The master-slave dialectic has influenced every major current of modern thought: Marxism (alienated labour), existentialism (Sartre\u2019s being-for-others), psychoanalysis (Lacan\u2019s mirror stage), critical theory (Honneth\u2019s recognition), postcolonial theory (Fanon\u2019s Black Skin, White Masks), and feminist philosophy (Beauvoir\u2019s Other). The concept of Bildung \u2014 the formation of the self through encounter with otherness \u2014 is the philosophical foundation of the humanities. The analysis of the French Revolution as \u201cabsolute freedom and terror\u201d is one of the most penetrating philosophical interpretations of political violence ever produced.',
    context: 'Completed in Jena in October 1806 as Napoleon\u2019s troops were entering the city. Hegel reportedly saw Napoleon riding through Jena on 13 October 1806 and wrote to his friend Niethammer: \u201cI saw the Emperor \u2014 this world-soul \u2014 riding through the city on reconnaissance. It is indeed a wonderful sensation to see such an individual, concentrated here on a single point, sitting on a horse, reaching out over the world and dominating it\u201d (letter to Niethammer, 13 October 1806; Briefe I, 120). Published by Goebhardt in Bamberg in 1807. The publisher threatened to withhold payment if Hegel did not deliver the final pages, which were reportedly sent off as French cannons could be heard. Standard editions: GW 9 (critical edition); W 3 (Suhrkamp); M (Miller, Oxford 1977); PM (Pinkard, Cambridge 2018).',
    relatedWorks: ['science-of-logic', 'encyclopedia-philosophical-sciences', 'philosophy-of-right', 'lectures-philosophy-history']
},

{
    id: 'science-of-logic',
    title: 'Science of Logic',
    greekTitle: 'Wissenschaft der Logik',
    philosopher: 'hegel',
    category: 'metaphysics',
    categoryLabel: 'Logic & Metaphysics',
    date: '1812\u201316 AD',
    dateSort: 1812,
    emoji: '\u267E\uFE0F',
    cardSize: 'wide',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 250000,
    shortDesc: 'The most ambitious work of pure philosophy since Aristotle \u2014 Hegel\u2019s systematic derivation of all the categories of thought from the most abstract (Being, Nothing, Becoming) to the most concrete (the Absolute Idea), demonstrating that logic, metaphysics, and ontology are one and the same science.',
    summary: 'The Science of Logic (Wissenschaft der Logik), published in three volumes \u2014 the Doctrine of Being (1812), the Doctrine of Essence (1813), and the Doctrine of the Concept (1816) \u2014 with a substantially revised first volume in 1831 (the year of Hegel\u2019s death), is the most ambitious work of pure philosophy in the Western tradition since Aristotle\u2019s Metaphysics. It undertakes to derive the entire system of categories \u2014 all the fundamental concepts through which reality is intelligible \u2014 from a single starting point: pure, indeterminate Being (reines Sein).\n\nThe famous opening argues that pure Being, thought without any determination whatsoever, is indistinguishable from Nothing (Nichts). Being and Nothing are not identical (they are thought as different) but they pass immediately into each other: the truth of both is Becoming (Werden) \u2014 the movement from Being to Nothing and from Nothing to Being. This opening triad \u2014 Being, Nothing, Becoming \u2014 is the germ of the entire Logic: every subsequent category arises through the same dialectical movement in which a concept reveals its own inadequacy, passes into its opposite, and is reconciled in a higher, more concrete concept.\n\nThe Doctrine of Being traces the categories of quality, quantity, and measure. The Doctrine of Essence traces the categories of reflection: identity and difference, ground, existence, actuality, substance and causality, and reciprocity. The Doctrine of the Concept \u2014 the culmination \u2014 traces the categories of the concept, judgment, syllogism, mechanism, chemism, teleology, life, cognition, and the Absolute Idea.\n\nThe Absolute Idea is not a supreme being or a theological concept but the fully self-determined, self-comprehending concept: the concept that has grasped the entire process of its own development and recognised itself in every one of its categories. It is the logical form of what the Phenomenology called absolute knowledge.\n\nThe Logic is Hegel\u2019s most technically demanding work and the one he regarded as his most important. He described it as containing \u201cthe thoughts of God before the creation of the world\u201d (die Darstellung Gottes, wie er in seinem ewigen Wesen vor der Erschaffung der Natur und eines endlichen Geistes ist) \u2014 not a theological claim but a metaphysical one: the Logic presents the pure categorial structure of reality prior to its embodiment in nature and spirit (GW 21, 34; GL 29).',
    themes: ['the dialectic of pure thought', 'Being, Nothing, Becoming', 'the categories of thought', 'the identity of logic and metaphysics', 'Aufhebung', 'the Absolute Idea', 'the Doctrine of Being', 'the Doctrine of Essence', 'the Doctrine of the Concept', 'the thoughts of God before creation'],
    keyCharacters: [],
    concepts: [
        'Being (Sein) \u2014 the most abstract and most indeterminate category; pure Being without any further determination is indistinguishable from Nothing (GW 21, 68\u201369; GL 59)',
        'Nothing (Nichts) \u2014 equally indeterminate; the same as Being in its complete lack of determination (GW 21, 69; GL 59)',
        'Becoming (Werden) \u2014 the truth of Being and Nothing: the movement from one to the other; the first concrete category (GW 21, 69\u201370; GL 59\u201360)',
        'Aufhebung (sublation) \u2014 the triple movement of cancelling, preserving, and elevating; the fundamental operation of dialectical logic (GW 21, 94\u201395; GL 81\u201382)',
        'Determinate Being (Dasein) \u2014 Being with a determination; the first category of quality (GW 21, 97; GL 83)',
        'Essence (Wesen) \u2014 the truth of Being; the domain of reflection, where categories appear in pairs: identity/difference, ground/existence, actuality/possibility (GW 11; GL 337\u2013503)',
        'The Concept (Begriff) \u2014 not a mere representation but the self-determining, self-particularising universal; the truth of both Being and Essence (GW 12; GL 505\u2013753)',
        'The Absolute Idea \u2014 the fully self-comprehending concept; the logical form of absolute knowledge; the concept that has grasped the entire process of its own development (GW 12, 236\u2013253; GL 735\u2013753)',
        'The thoughts of God before creation \u2014 Hegel\u2019s characterisation of the Logic: the pure categorial structure of reality prior to nature and spirit (GW 21, 34; GL 29)',
        'Contradiction (Widerspruch) \u2014 not a mere logical error but the moving principle of all development; \u201ccontradiction is the root of all movement and life\u201d (GW 11, 286; GL 439)'
    ],
    structure: 'Volume One: The Doctrine of Being (1812; revised 1831)\n\u2014 Quality: Being, Nothing, Becoming; Determinate Being; Being-for-itself\n\u2014 Quantity: Pure Quantity; Quantum; Quantitative Ratio\n\u2014 Measure: Specific Quantity; Real Measure; The Becoming of Essence\n\nVolume Two: The Doctrine of Essence (1813)\n\u2014 Reflection: Identity, Difference, Contradiction, Ground\n\u2014 Appearance: Existence, Appearance, Essential Relation\n\u2014 Actuality: The Absolute, Actuality, Absolute Necessity (Substance, Causality, Reciprocity)\n\nVolume Three: The Doctrine of the Concept (1816)\n\u2014 Subjectivity: Concept, Judgment, Syllogism\n\u2014 Objectivity: Mechanism, Chemism, Teleology\n\u2014 The Idea: Life, Cognition, The Absolute Idea',
    quote: 'This science presents the exposition of God as he is in his eternal essence before the creation of nature and a finite spirit.',
    additionalQuotes: [
        { text: 'Being, pure Being \u2014 without any further determination. In its indeterminate immediacy it is equal only to itself, and is also not unequal with respect to anything else; it has no diversity within itself, nor any outwardly. If any determination or content were distinguished in it, or if it were posited by this determination or content as distinct from another, it would thereby fail to be held fast in its purity. It is pure indeterminacy and emptiness.', citation: 'GW 21, 68\u201369; GL 59 (opening of the Logic)' },
        { text: 'Contradiction is the root of all movement and life; only insofar as something has a contradiction within it does it move, does it have impulse and activity.', citation: 'GW 11, 286; GL 439 (Doctrine of Essence)' },
        { text: 'The Absolute Idea alone is being, imperishable life, self-knowing truth, and it is all truth.', citation: 'GW 12, 236; GL 735 (opening of the Absolute Idea chapter)' },
        { text: 'What is rational is actual, and what is actual is rational.', citation: 'Not from the Logic but from the Philosophy of Right Preface (W 7, 24; PR 20); frequently cited in connection with the Logic' }
    ],
    commentary: [
        { philosopher: 'Karl Marx', text: 'Marx wrote in the 1844 Manuscripts that the Logic is \u201cthe money of the spirit\u201d \u2014 the abstract expression of human productive activity in alienated form. Marx proposed to \u201cinvert\u201d Hegel\u2019s Logic: where Hegel begins with pure Being and derives the concrete from the abstract, Marx begins with concrete material production and derives the abstract categories of political economy from the real movement of history.' },
        { philosopher: 'V.I. Lenin', text: 'Lenin\u2019s Philosophical Notebooks (1914\u201315; published 1929\u201330) contain extensive annotations on the Science of Logic. Lenin wrote that \u201cit is impossible completely to understand Marx\u2019s Capital, and especially its first chapter, without having thoroughly studied and understood the whole of Hegel\u2019s Logic.\u201d' },
        { philosopher: 'Robert Brandom', text: 'Brandom\u2019s A Spirit of Trust (2019) interprets the Logic as an account of the inferential articulation of conceptual content: each category specifies the inferential relations that constitute the meaning of the concepts it contains. The Logic is, on Brandom\u2019s reading, the first systematic semantics.' },
        { philosopher: 'Stephen Houlgate', text: 'Houlgate\u2019s The Opening of Hegel\u2019s Logic (2006) provides the most detailed modern analysis of the transition from Being through Nothing to Becoming, arguing that Hegel\u2019s opening is genuinely presuppositionless: it begins from pure indeterminate thought and derives the first categories through the internal inadequacy of pure Being itself.' }
    ],
    modernRelevance: 'The Science of Logic has experienced a major revival in the twenty-first century. Robert Brandom\u2019s inferentialist interpretation, Stephen Houlgate\u2019s close readings, and the \u201cPittsburgh Hegelians\u201d (Brandom, McDowell, Pippin) have made the Logic central to contemporary debates in semantics, metaphysics, and the philosophy of mind. The concept of Aufhebung has influenced structuralism, deconstruction (Derrida), and systems theory (Luhmann). The Logic\u2019s programme of deriving categories from pure thought \u2014 without empirical presuppositions \u2014 has been compared to the project of formal ontology in analytic philosophy.',
    context: 'Published in three volumes by the Schrag publishing house in Nuremberg: the Doctrine of Being in 1812, the Doctrine of Essence in 1813, the Doctrine of the Concept in 1816. A substantially revised first volume appeared in 1831, the year of Hegel\u2019s death; he did not live to revise the second and third volumes. Written during Hegel\u2019s years as rector of the Aegidiengymnasium in Nuremberg (1808\u20131816), the most intellectually productive but professionally frustrating period of his life. Standard editions: GW 11, 12, 21 (critical edition); W 5\u20136 (Suhrkamp); GL = George di Giovanni translation (Cambridge, 2010).',
    relatedWorks: ['phenomenology-of-spirit', 'encyclopedia-philosophical-sciences', 'philosophy-of-right', 'lectures-history-philosophy']
},

{
    id: 'encyclopedia-philosophical-sciences',
    title: 'Encyclopedia of the Philosophical Sciences',
    greekTitle: 'Enzyklop\u00e4die der philosophischen Wissenschaften im Grundrisse',
    philosopher: 'hegel',
    category: 'metaphysics',
    categoryLabel: 'Systematic Philosophy',
    date: '1817/1827/1830 AD',
    dateSort: 1817,
    emoji: '\uD83D\uDCD6',
    cardSize: 'normal',
    readingDifficulty: 'Advanced',
    estimatedWordCount: 120000,
    shortDesc: 'The complete Hegelian system in miniature \u2014 the only work in which Hegel presents his entire philosophy (Logic, Nature, Spirit) as a single, unified, self-enclosed circle, designed as a textbook for his students at Heidelberg and Berlin.',
    summary: 'The Encyclopedia of the Philosophical Sciences in Outline (Enzyklop\u00e4die der philosophischen Wissenschaften im Grundrisse), first published in Heidelberg by August O\u00dfwald in 1817 and substantially expanded in second (1827) and third (1830) editions, is the only work in which Hegel presents his complete philosophical system as a unified whole. It is divided into three parts, corresponding to the three moments of the Absolute: Logic, Nature, and Spirit.\n\nPart One: The Encyclopedia Logic (Logik) is a condensed version of the Science of Logic, presenting the same dialectical derivation of the categories from Being through Essence to the Concept, but in a compressed, textbook form with numbered paragraphs (\u00a7\u00a719\u2013244) and explanatory Zusätze (additions compiled from student lecture notes). The Encyclopedia Logic is often more accessible than the longer Science of Logic and is the version of Hegel\u2019s logic most frequently studied by students.\n\nPart Two: The Philosophy of Nature (\u00a7\u00a7245\u2013376) is Hegel\u2019s least studied and most controversial work. It presents nature as the \u201cIdea in the form of otherness\u201d (die Idee in der Form des Andersseins; \u00a7247; EPN 13) \u2014 the Absolute externalised in space and time. Hegel analyses nature through three stages: mechanics (space, time, matter, motion, gravity), physics (the elements, magnetism, electricity, chemical process), and organics (the geological organism, the vegetable organism, the animal organism). The Philosophy of Nature has been widely criticised for its speculative excesses but has attracted renewed attention in the context of ecological philosophy and the new materialism.\n\nPart Three: The Philosophy of Spirit (\u00a7\u00a7377\u2013577) presents the Absolute\u2019s return to itself from its alienation in nature. It traces Spirit through three stages: Subjective Spirit (anthropology, phenomenology, psychology), Objective Spirit (right, morality, ethical life \u2014 a compressed version of the Philosophy of Right), and Absolute Spirit (art, religion, philosophy). The final paragraph (\u00a7577) presents the three syllogisms of the entire system, in which Logic, Nature, and Spirit are shown to be mutually mediating moments of a single self-enclosed whole.\n\nThe Encyclopedia is the text through which most students encounter Hegel\u2019s system and the one most frequently assigned in courses on Hegel.',
    themes: ['the complete system', 'Logic, Nature, Spirit', 'the Absolute as self-enclosed circle', 'the Encyclopedia Logic', 'the Philosophy of Nature', 'the Philosophy of Spirit', 'the textbook form', 'Zusätze', 'the three syllogisms'],
    keyCharacters: [],
    concepts: [
        'The three parts of the system \u2014 Logic (the Idea in itself), Nature (the Idea in the form of otherness), Spirit (the Idea returning to itself from otherness); the Absolute is the unity of all three (\u00a718; EL 29)',
        'The Encyclopedia Logic \u2014 the compressed version of the Science of Logic; the dialectical derivation of the categories in textbook form (\u00a7\u00a719\u2013244; EL 29\u2013307)',
        'Nature as the Idea in the form of otherness \u2014 the Absolute externalised in space and time (\u00a7247; EPN 13)',
        'Spirit as the Idea returning to itself \u2014 the Absolute that has alienated itself in nature and returns to self-knowledge through the development of subjective, objective, and absolute Spirit (\u00a7381; EPS 7)',
        'Subjective Spirit \u2014 anthropology (the soul), phenomenology (consciousness), psychology (the mind) (\u00a7\u00a7387\u2013482; EPS 25\u2013227)',
        'Objective Spirit \u2014 right, morality, ethical life (Sittlichkeit): the realisation of freedom in institutions (\u00a7\u00a7483\u2013552; EPS 228\u2013279)',
        'Absolute Spirit \u2014 art, religion, philosophy: the Absolute\u2019s self-knowledge in increasingly adequate forms (\u00a7\u00a7553\u2013577; EPS 280\u2013315)',
        'The three syllogisms (\u00a7577) \u2014 the concluding paragraph presents the system as three mutually mediating syllogisms: Logic-Nature-Spirit, Nature-Spirit-Logic, Spirit-Logic-Nature (EPS 313\u2013315)',
        'The Zusätze (additions) \u2014 explanatory notes compiled from student lecture notes; not written by Hegel himself but approved by him and often clearer than the main text'
    ],
    structure: 'Part One: The Encyclopedia Logic (\u00a7\u00a71\u2013244)\n\u2014 Preliminary Conception: The three attitudes to objectivity\n\u2014 The Doctrine of Being (\u00a7\u00a784\u2013111)\n\u2014 The Doctrine of Essence (\u00a7\u00a7112\u2013159)\n\u2014 The Doctrine of the Concept (\u00a7\u00a7160\u2013244)\n\nPart Two: The Philosophy of Nature (\u00a7\u00a7245\u2013376)\n\u2014 Mechanics: space, time, matter, motion\n\u2014 Physics: elements, magnetism, electricity, chemical process\n\u2014 Organics: geological, vegetable, animal organism\n\nPart Three: The Philosophy of Spirit (\u00a7\u00a7377\u2013577)\n\u2014 Subjective Spirit: anthropology, phenomenology, psychology\n\u2014 Objective Spirit: right, morality, ethical life\n\u2014 Absolute Spirit: art, religion, philosophy\n\u2014 \u00a7577: The three syllogisms',
    quote: 'Philosophy forms a circle. It has a beginning, which, since it is a beginning, has not been proved and is not a result. But the beginning of philosophy is immediately a relative result, since it is only at the end that it is known as the true beginning. In this way philosophy appears as a circle returning upon itself.',
    additionalQuotes: [
        { text: 'The Absolute is Spirit \u2014 this is the highest definition of the Absolute.', citation: '\u00a7384; EPS 12' },
        { text: 'Nature is to be regarded as a system of stages, one arising necessarily from the other and being the proximate truth of the stage from which it results.', citation: '\u00a7249; EPN 19' },
        { text: 'What is rational is actual, and what is actual is rational.', citation: 'Repeated from the Philosophy of Right Preface; often cited in connection with the Encyclopedia\u2019s programme' }
    ],
    commentary: [
        { philosopher: 'Michael Inwood', text: 'Inwood\u2019s Hegel (1983) identifies the Encyclopedia as the best point of entry into Hegel\u2019s system for new readers: \u201cIt is the only work that gives the whole system, and its textbook format, with numbered paragraphs and explanatory additions, makes it more navigable than any of the longer works.\u201d' },
        { philosopher: 'Michael Wolff', text: 'Wolff\u2019s work on the Encyclopedia Logic has been central to the revival of interest in Hegel\u2019s logic in the analytic tradition, demonstrating that Hegel\u2019s dialectical logic is a genuine logic \u2014 not a mystical substitute for formal logic but an attempt to exhibit the internal connections among the fundamental categories of thought.' },
        { philosopher: 'Alison Stone', text: 'Stone\u2019s Petrified Intelligence: Nature in Hegel\u2019s Philosophy (2005) is the most important recent study of the Philosophy of Nature, arguing that Hegel\u2019s speculative treatment of nature, while scientifically superseded, raises genuine philosophical questions about the relationship between nature and reason that remain unresolved.' }
    ],
    modernRelevance: 'The Encyclopedia is the text most frequently used in teaching Hegel and the one most accessible to students encountering his system for the first time. The Encyclopedia Logic has become central to the analytic Hegel revival (Brandom, McDowell, Pippin). The Philosophy of Nature has attracted renewed interest in the context of ecological philosophy, the new materialism, and the question of whether nature has intrinsic value. The Philosophy of Spirit\u2019s account of Sittlichkeit (ethical life) \u2014 the realisation of freedom through the institutions of family, civil society, and the state \u2014 continues to influence communitarian political philosophy.',
    context: 'First edition published in Heidelberg by O\u00dfwald in 1817, shortly after Hegel\u2019s appointment to the University of Heidelberg. Second edition (1827) and third edition (1830) published in Berlin by Duncker und Humblot, substantially expanded. The work was designed as a textbook for Hegel\u2019s students: the numbered paragraphs provided the structure for his lectures, which filled out the compressed arguments with examples and illustrations. The Zus\u00e4tze were compiled from student lecture notes by Hegel\u2019s editors (primarily Leopold von Henning, Karl Ludwig Michelet, and Ludwig Boumann) after his death and published in the 1840s. Standard editions: GW 13, 19, 20 (critical edition); W 8\u201310 (Suhrkamp); EL = Geraets/Suchting/Harris (Hackett, 1991); EPN = Petry (3 vols., 1970) or Miller (Oxford, 2004); EPS = Wallace/Miller (Oxford, 2007).',
    relatedWorks: ['science-of-logic', 'phenomenology-of-spirit', 'philosophy-of-right', 'lectures-aesthetics', 'lectures-philosophy-religion']
}

);
